### ISSUE TITLE
Middleware state saved in request.dpd_content_handler -> ContentCollector is lost when used with Wagtail StreamField

### ISSUE THREAD

**Issue by yurman-cc** [GibbsConsulting/django-plotly-dash#101]
django_plotly_dash.middleware collects the information about which js modules are required for the apps loaded on the page. It saves this information in the request.dpd_content_handler member. These lines importing js are later substituted in place of the place-holder string inserted by the {% plotly_footer %} template tag.

The problem is that some django content management systems (specifically, wagtail) create a new dummy request object for the purpose of implementing their advanced page preview features and the like. This causes the state saved in the old request object to be lost. When a new (dummy) request object is created, the only arbitrary request fields (like dpd_content_handler above) that can be arranged to get copied over to the new request have to come from the request.META dict.

I got this problem fixed by changing the BaseMiddleware.__call__ method like below:

    def __call__(self, request):

        meta = request.META
        if not 'dpd_content_handler' in meta:
            meta['dpd_content_handler'] = ContentCollector()

        request.dpd_content_handler = meta['dpd_content_handler']
        response = self.get_response(request)
        response = request.dpd_content_handler.adjust_response(response)

        return response

**Comment by yurman-cc** [comment]
You can see a Dash app running with Wagtail here: https://xcms.helium.red/xcmsblog/2019/01/06/launching-data-new-orbit-belka-and-strelka-/

**Comment by GibbsConsulting** [comment]
Django's approach seems to be (a) ``request.META`` is for the http headers and (b) Middleware sets ``request.some_property`` directly on the request object - based on the [request-response](https://docs.djangoproject.com/en/dev/ref/request-response/) docs.

As such, it seems that the CMS that copies only a subset of the request object is the source of the problem. I think in the first instance that fixing their code is the best route to try.

**Comment by yurman-cc** [comment]
Yes, by default, wagtail drops most of the request fields for the preview. There is already a way to request copying specific fields but from META only (used mostly for HTTP headers, as you mentioned). Overriding Page.dummy_request() on the page model and calling Page.default_preview_mode.update() does that like in the code below:

    def dummy_request(self, original_request=None, **meta):
        if 'dpd_content_handler' in original_request.META:
            meta.update({'dpd_content_handler': original_request.META['dpd_content_handler']})
        return super().dummy_request(original_request, **meta)

There is probably a valid reason why they don't copy the entire request though.. I'm going to open an issue with them referencing this thread and let's see what is the best way of solving this.

**Comment by yurman-cc** [comment]
I can't open an issue with them (the button is missing, need to register somehow?)..
https://github.com/search?q=wagtail&type=Issues
if you know how to escalate with them please do. Thanks

**Comment by GibbsConsulting** [comment]
Perhaps the link you need is [here](https://github.com/wagtail/wagtail/issues)

**Comment by yurman-cc** [comment]
oops, my bad

Got it [filed](https://github.com/wagtail/wagtail/issues/4983) now, thanks

**Comment by GibbsConsulting** [comment]
This appears to be something for Wagtail to deal with, so closing this issue.

**Comment by yurman-cc** [comment]
On the other hand, it's trivial to fix it in this project (like in the code above) and I see no adverse effects for such a fix, in wagtail - it's an interface level change. To make it backwards compatible would require an ugly hack of passing an additional field in **meta holding request fields that need to be copied. I doubt I could have such a change merged which leaves me with having to fork django-plotly-dash (
