### ISSUE TITLE
Key Error [Question]

### ISSUE THREAD

**Issue by vantaka2** [GibbsConsulting/django-plotly-dash#102]
Just starting out and can't seem to insert dash into one of my django Applications. I followed the installation and simple usage guide.  

I have done the following: 

added `'django_plotly_dash.apps.DjangoPlotlyDashConfig'` to INSTALLED_APPS in settings. 
added `'django_plotly_dash.middleware.BaseMiddleware',` to MIDDLEWARE in settings

added `path('django_plotly_dash/', include('django_plotly_dash.urls')),` to my projects urls.py file

Successfully updated the database

created dash app nammed 'dash_app.py' and its located in the same folder as the projects settings.py and urls.py file. 

Updated template to include 
`{%load plotly_dash%}
{%plotly_app name="SimpleExample"%}`

and lastly my view.py file looks like this:
`class HomePage2(ListView):
    model = main_kpi
    template_name = 'home\home.html'
    context_object_name = 'list_of_kpis'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        dash_context = self.request.session.get("django_plotly_dash", dict())
        dash_context['django_to_dash_context'] = "I am Dash receiving context from Django"
        self.request.session['django_plotly_dash'] = dash_context
        return context
`

When I bring up the application in debug mode I get the following error:
`KeyError at /home/
'Unable to find stateless DjangoApp called simpleexample'`

Is there something i'm missing? Happy to update docs with a straight forward how to guide for beginners if I can get this figured out.

**Comment by vantaka2** [comment]
After a lot trial and error I think I found what I did wrong. in url.py I never imported my dash file: 

`from . import dash_app`


This is even stated in the 'Simple Useage'
`The example Django application in the demo subdirectory achieves this through an import in the main urls.py file`

Might be a bit easier for beginners to show the actual import? I can submit a pull request if you think that would be worthwhile. 

Thanks!

**Comment by brylie** [comment]
Yeah, many books and tutorials will also show the necessary imports in the code examples. The idea is to not have very much tacit knowledge. 

Drawing the line of necessary tacit knowledge is, admittedly, difficult.

**Comment by schlich** [comment]
This update is still not in the latest documentation

**Comment by sercankiyak** [comment]
May I point out that it is still not in the documentation. As a non-computer scientist trying some web development, Django_plotly_dash was the hardest thing (as far as deciphering the documentation go) I attempted so far. Also, it feels very bad to understand now that just one additional line of code to the installation guide could have saved me so much work.

**Comment by brylie** [comment]
I opened another pull request to clarify how to register the Plotly app with Dash in the Installation document.

**Comment by brylie** [comment]
The pull request was merged. Please let me know if the addition in the Installation document sufficiently describes how to register the Plotly app with Dash.

**Comment by sercankiyak** [comment]
Thanks! I think the added note normally clarifies things very well but it seems to me that a word is missing from the sentence, see: An easy way to ensure the Plotly app (works?) is to import it into views.py or urls.py as in the following example...
Also, not to start another question but I did not know one could import the library to views.py as well. Is it practically the same as importing it to the urls.py ?

**Comment by brylie** [comment]
> An easy way to ensure the Plotly app (works?) is to import it into views.py or urls.py as in the following example...

That sounds like a good basis for a pull request. Would you mind improving the documentation with your suggestion? It is fairly straightforward to edit the documentation directly on GitHub. 

In this case, just click the "Edit on GitHub" link and then click the little pencil icon to open the text editor, which takes you to the following page:

https://github.com/GibbsConsulting/django-plotly-dash/edit/master/docs/installation.rst

After you make your changes, give a brief description in the "Propose changes" section (towards the bottom of the page) and click the green "Propose changes" button (as can be seen in the following picture).

![image](https://user-images.githubusercontent.com/17307/118390314-03509000-b637-11eb-889e-46a7b759cb0f.png)

In this way, the documentation becomes richer as there are more contributors :-)

**Comment by sercankiyak** [comment]
Ok thanks, great idea. I tried to correct it and add a line (based on my experience). Modify as you fit. Best
