### ISSUE TITLE
Using Bootstraps grid within a dash app

### ISSUE THREAD

**Issue by vantaka2** [GibbsConsulting/django-plotly-dash#105]
I'm attempting to place a formatted dash application into my django site. For the rest of my web application I'm using bootstrap 4.1.3 via CDN. 
`<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">`

I figured if I use  {%plotly_direct name="SimpleExample" %}  to embed my app I should be able to use bootstraps grid system to position the various parts of my application. 

Here I have two div's a graph and a dropdown menu that are meant to each take up half the space: 
```
app.layout = html.Div(children=[
    html.Div([
    html.Div([
        dcc.Graph(
                id='graph_one',
                style={"height": "90%", "width": "98%"},
                config={'modeBarButtonsToRemove':['sendDataToCloud','zoom2d','pan2d','select2d','lasso2d','toggleSpikelines',
                'zoomIn2d','zoomOut2d','autoScale2d','resetScale2d','hoverClosestCartesian','hoverCompareCartesian'],
                'displaylogo':False})],className='col-md-6')
    ,
        html.Div([
    dcc.Dropdown(
    options=[
        {'label': 'New York City', 'value': 'NYC'},
        {'label': 'Montréal', 'value': 'MTL'},
        {'label': 'San Francisco', 'value': 'SF'}
    ],
    value='MTL'
    )],className='col-md-6')
],className='row',)
])
```
This is the result: It seems height of the entire div is being set really small by something. 

![image](https://user-images.githubusercontent.com/16373636/51006582-8f06fe80-1509-11e9-9b92-acad68dbf1db.png)

I then removed div with className='row' from my code and got the following result: 

```
app.layout = html.Div(children=[
    html.Div([
    html.Div([
        dcc.Graph(
                id='graph_one',
                style={"height": "90%", "width": "98%"},
                config={'modeBarButtonsToRemove':['sendDataToCloud','zoom2d','pan2d','select2d','lasso2d','toggleSpikelines',
                'zoomIn2d','zoomOut2d','autoScale2d','resetScale2d','hoverClosestCartesian','hoverCompareCartesian'],
                'displaylogo':False})],className='col-md-6')
    ,
        html.Div([
    dcc.Dropdown(
    options=[
        {'label': 'New York City', 'value': 'NYC'},
        {'label': 'Montréal', 'value': 'MTL'},
        {'label': 'San Francisco', 'value': 'SF'}
    ],
    value='MTL'
    )],className='col-md-6')
],)
])
```
![image](https://user-images.githubusercontent.com/16373636/51006797-76e3af00-150a-11e9-895c-ec5de6e5c5f3.png)

This time the graph shows up completely but then the requirements for them to be next to each other is ignored. 

Then I thought it might just need to be wrapped in a 'row' class within the django template: 

```
    <div class='row'>
    
        {%plotly_direct name="SimpleExample" %}
   
    </div>
```

When i do this, this is the result: 

![image](https://user-images.githubusercontent.com/16373636/51006989-4c462600-150b-11e9-90fd-69bc82a676a3.png)

I'm just starting out with django-plotly-dash, so i'm not sure if this is an actual issue or if i'm just not following best practices here. 

If its not possible to use the bootstrap grid to position components  of my dash app, how would I go about doing that?

**Comment by brylie** [comment]
This might be e a good question for the Dash community forum or StackOverflow, since it isn't specific to `django-plotly-dash`.

https://community.plot.ly/t/bootstrap-rows-columns-with-dash/10590

https://community.plot.ly/t/show-and-tell-dash-bootstrap-components/16614

That said, there is an open issue here regarding compatibility with Dash Bootstrap components:

https://github.com/GibbsConsulting/django-plotly-dash/issues/84

**Comment by vantaka2** [comment]
Appropriate the reply @brylie  - I'll ask the Dash community and post the results on here if I solve it.

**Comment by GibbsConsulting** [comment]
The [template tags](https://django-plotly-dash.readthedocs.io/en/latest/template_tags.html) allow you to set a ratio between the height and width of the rendered dash app - this is how the size of the app is determined. Try maing the ratio higher to have a bigger app.

There is also issue #35 which looks to enable alternative ways of specifying the size of an app.

**Comment by vantaka2** [comment]
So still not sure why its happening, but this is occurring because I styled the graph; 
Removing this gives me the desired output, so as pointed out above this is an dash issue. 
```
**style={"height": "90%", "width": "98%"},**
```

**Comment by cjmcclellan** [comment]
Just want to add my experience.

I was trying to use Bootstrap with my Dash-Django app and found I could not get the proper formatting.  I eventually figured out that using the html iframe was the issue.  I switched to using the direct app embedding (demo 5) which worked nicely.

I don't think this is an Dash issue as when I tried Bootstrap formatting in demo 1, I could not get the proper behavior.  The iframe does not seem to import any css imported using a CDN.

**Comment by GibbsConsulting** [comment]
@cjmcclellan is the issue an absence of css inside the iframe (should not be the case), or that you wanted to use bootstrap layout/structural features inside the iframe in conjunction with related ones on the outside (which won't work).

For the latter case, I'm thinking of something along the lines of a bootstrap grid layout in the outer template and a member of that layout (eg a row or card or similar) inside the dash app.

**Comment by cjmcclellan** [comment]
It was an absence of css inside the iframe, perhaps I'm not importing the css properly?

Essentially, I was trying to use bootstrap classes with Dash:
`html.Div(className='col-sm', ...)`

but the style was not importing into the iframe.  Direct HTML insertion worked fine, as would be expected.  I'm importing bootstrap using a CDN in the header tag.
