### ISSUE TITLE
Multiple plotly_direct apps in one html file

### ISSUE THREAD

**Issue by Motta23** [GibbsConsulting/django-plotly-dash#110]
Is it possible to include multiple Dash apps through the plotly_direct tag? When I test this out, I only get an output for one plotly_direct app. The rest of the apps stays on "Loading...". 

I don't have this issue when I use the plotly_app tag, as all the apps are shown in the html file. I'd rather use plotly_direct though, as it gives me more freedom in using one CSS file for the whole site etc. Many thanks!

Simple example to show that it doesn't work:

**html-file:**
```
<html>
<body>
    {% load plotly_dash %}
    {% plotly_header %}
    {% plotly_direct name="test1"%}
    {% plotly_direct name="test2"%}
    {% plotly_footer %}
</body>
</html>

```

**test1 app:**
```
from django_plotly_dash import DjangoDash
import dash_html_components as html
import dash_core_components as dcc


app = DjangoDash('test1')   # replaces dash.Dash


app.layout = html.Div(children=[
    html.H1(children='Hello Dash'),

    html.Div(children='''
        Dash: A web application framework for Python.
    '''),

    dcc.Graph(
        id='example-graph',
        figure={
            'data': [
                {'x': [1, 2, 3], 'y': [4, 1, 2], 'type': 'bar', 'name': 'SF'},
                {'x': [1, 2, 3], 'y': [2, 4, 5], 'type': 'bar', 'name': u'Montréal'},
            ],
            'layout': {
                'title': 'Dash Data Visualization'
            }
        }
    )
])

```

**test2 app:**
```
from django_plotly_dash import DjangoDash
import dash_html_components as html
import dash_core_components as dcc


app = DjangoDash('test2')   # replaces dash.Dash


app.layout = html.Div(children=[
    html.H1(children='Hello Dash'),

    html.Div(children='''
        Dash: A web application framework for Python.
    '''),

    dcc.Graph(
        id='example-graph',
        figure={
            'data': [
                {'x': [1, 2, 3], 'y': [4, 1, 2], 'type': 'bar', 'name': 'SF'},
                {'x': [1, 2, 3], 'y': [2, 4, 5], 'type': 'bar', 'name': u'Montréal'},
            ],
            'layout': {
                'title': 'Dash Data Visualization'
            }
        }
    )
])

```

**Comment by vantaka2** [comment]
I do not believe this is possible according to the docs: https://django-plotly-dash.readthedocs.io/en/stable/template_tags.html

"This tag should not appear more than once on a page. This rule however is not enforced at present."

**Comment by brylie** [comment]
I believe you can have multiple Dash apps in the same template if you use the [plotly_app template tag](https://django-plotly-dash.readthedocs.io/en/latest/template_tags.html#the-plotly-app-template-tag).

**Comment by Motta23** [comment]
Yes @brylie, I could get that to work. As it's not possible, I'll be going for that. Thanks for the replies!
