### ISSUE TITLE
Unable to find stateless DjangoApp called simpleexample

### ISSUE THREAD

**Issue by VimalRughani** [GibbsConsulting/django-plotly-dash#116]
Hi All,

Greetings Vimal Rughani, 

First of all Thank You very much for great work, Since while I was looking for such django app :+1: 

Here is my issue, I have followed up your instruction and tried to integrate Simple Example demo https://django-plotly-dash.readthedocs.io/en/latest/simple_use.html#simple-usage in my existing project. 

But when I executed code, it throws error **'Unable to find stateless DjangoApp called simpleexample',**

I am using Django 2.1.3 with python 3.6 , is something related to code issue or I have missed somthing ? 

Please let me on that, also it will be great if you can suggest some video tutorial or ebook for django-plotly-dash app. 

Thanks

**Comment by vantaka2** [comment]
Hi, 

I had the same issue when I was going through that tutorial. 

Check out the solutions here:  https://github.com/GibbsConsulting/django-plotly-dash/issues/102

**Comment by VimalRughani** [comment]
Thanks @vantaka2 and @GibbsConsulting  for helping me out on that issue. I am able to resolved that issue.  Thanks again for your kind support.  @GibbsConsulting I feel you should do some videos and blog for advance integration of your app. Its really powerful app.

**Comment by GibbsConsulting** [comment]
@vantaka2 please do! Contributions, either in the form of pull requests or external items such as blog posts, are most welcome.

Closing this issue as @VimalRughani reports that his issue is resolved.
