### ISSUE TITLE
NoReverseMatch - 'the_django_plotly_dash' is not a registered namespace

### ISSUE THREAD

**Issue by garry-sharp** [GibbsConsulting/django-plotly-dash#117]
I get the following error when trying to run load an index page (I followed your example with the exception or using re_path over url in the urls.py).

What am I doing wrong here?

FYI the page renders fine when using the {%load plotly_dash%} tag. It's the SimpleExample one that throws it.

**Comment by garry-sharp** [comment]
<img width="1063" alt="screenshot 2019-02-08 at 16 45 47" src="https://user-images.githubusercontent.com/1861862/52489070-9f220480-2bc1-11e9-8486-17f954de792b.png">

FYI verisons are
dash                                  0.36.0    
dash-core-components  0.43.0    
dash-html-components  0.13.5  
django-plotly-dash          0.9.8     

End game is to have this up on AWS servers but for now I'm using a Mac

**Comment by GibbsConsulting** [comment]
If you're running a modified version of the demo, then one approach would be to retrace your steps back to a working demo and find out what change caused the error. This app name is only used within the django-plotly-dash code, which suggests that this could be related to any difference between your import of the the urls and the approach used in the demo, namely
```
    url('^django_plotly_dash/', include('django_plotly_dash.urls')),
```
Note that this approach uses the name defined within django-plotly-dash for the namespace name.

**Comment by garry-sharp** [comment]
Hi, I'm not, I based a clean example off of the demo but did not clone any demo code, tracing through the code the line "the_django_plotly_dash" is in the app_name parameter of the django_plotly_dash directory in the packages that are installed. Somehow I am trying to load in code from that app but I have no idea how. Code lines as follows

Project Dashboard
settings.py
`"""
Django settings for dashboard project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'v8&*@zxj52$9ljppc2p-=*s)1hxxx-le9u(wdbd=h7rqy6r(%5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
    'django_plotly_dash.apps.DjangoPlotlyDashConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_plotly_dash.middleware.BaseMiddleware',
]

ROOT_URLCONF = 'dashboard.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dashboard.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
`

urls.py
`from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
	re_path(r'^', include("main.urls")),
]
`

"main" app
urls.py
`from django.contrib import admin
from django.urls import path, re_path
from main import views
#from main.dash import SimpleExample


import main.plotly_apps
from django.views.generic import TemplateView



urlpatterns = [
    re_path(r'^$', TemplateView.as_view(template_name='index.html'))
]

`

views.py
`from django.shortcuts import render
from django.views.generic import TemplateView
from main import models
from main import plotly_apps

def index_view(request, template_name="index.html", **kwargs):
    'Example view that inserts content into the dash context passed to the dash application'

    context = {}

    # create some context to send over to Dash:
    '''
    dash_context = request.session.get("django_plotly_dash", dict())
    dash_context['django_to_dash_context'] = "I am Dash receiving context from Django"
    request.session['django_plotly_dash'] = dash_context
	'''
    return render(request, template_name=template_name, context=context)
`

plotly_apps.py
`import dash
import dash_core_components as dcc
import dash_html_components as html

from django_plotly_dash import DjangoDash
#from main import DjangoDash

app = DjangoDash('SimpleExample2')

app.layout = html.Div([
	html.H1(children="Hello World")
])`

index.html
`<html>
<head></head>
<body>

{%load plotly_dash%}
{%plotly_app name="SimpleExample2"%}
<p></p>

</body>
</html>
`

**Comment by GibbsConsulting** [comment]
OK, so it looks like you're not registering ``django_plotly_dash.urls`` in any of your urlpatterns. This is why the namespace can't be found. If you add this set of urls as per my previous comment then the templates should work.

**Comment by garry-sharp** [comment]
Hi,

I see, it does indeed work, I thought originally that referencing django_plotly_dash.urls was just to load in the demo app.

Thanks for your help!

**Comment by gunad** [comment]
Hi,

Had the same problem and worked with the solution provided above.
Thanks 👍

**Comment by deniskristak** [comment]
Same problem here, maybe you enrich the documentation by the fact that it's indeed not user's app name, but is required for the dash to work ? But at least this issue was quick to fix the problem :-)  :+1:

**Comment by deniskristak** [comment]
@GibbsConsulting 
I opened a PR myself, lmk what you think about it :) https://github.com/GibbsConsulting/django-plotly-dash/pull/439

**Comment by delsim** [comment]
@gbwlucite  If its not the same as above (ie you need to make sure the urls are imported; you haven't actually told us what error you are getting) then best to open a new issue..
