### ISSUE TITLE
Cannot increase graph height

### ISSUE THREAD

**Issue by s-hood** [GibbsConsulting/django-plotly-dash#118]
I have the following in my views.py
```
app = DjangoDash('test')
app.layout = html.Div(children=[
    html.H1(children='Dash Tutorials'),
    dcc.Graph(
        id='example',
        figure={
            'data': [
                {'x': [1, 2, 3, 4, 5], 'y': [9, 6, 2, 1, 5], 'type': 'line', 'name': 'Boats'},
                {'x': [1, 2, 3, 4, 5], 'y': [8, 7, 2, 7, 3], 'type': 'bar', 'name': 'Cars'},
            ],
            'layout': {
                'title': 'Basic Dash Example',
            }
        }
    )
])
```
The html is:
```
{% load plotly_dash %}
<div">
{% plotly_app name="test" %}
</div>
```
When I open this in the browser the graph has a size of 830x83 and I can only see the top of the graph unless I scroll down within the graph window. 

![screenshot from 2019-02-12 03-36-55](https://user-images.githubusercontent.com/19922693/52610072-7e82d480-2e77-11e9-8772-6f43293014f2.png)

I'm sure its a simple fix but I can't spot my error.

**Comment by s-hood** [comment]
This occurs even with the app layout:
app.layout = html.Div([
    html.P('testing'),
    html.P('testing'),
    html.P('testing'),
    html.P('testing'),
    html.P('testing'),
])

Only the top two are visible and I must scroll through the small window to see the rest. 

This is the html generated in place of the line {% plotly_app name="test" %}

<div style="
    position: relative;
    padding-bottom: 10.0%;
    height: 0;
    overflow:hidden;
    ">
  <iframe src="/django_plotly_dash/app/test/" style="
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    " frameborder="0"></iframe>
</div>

**Comment by s-hood** [comment]
SOLVED:
With
```
{% plotly_app name="test" ratio=1%}
```

**Comment by tiwansh** [comment]
> SOLVED:
> With
> 
> ```
> {% plotly_app name="test" ratio=1%}
> ```

You just saved my day! Thanks for posting this answer : D
