### ISSUE TITLE
serving css and js locally and adding local css files to dash [Question/ possible issue?]

### ISSUE THREAD

**Issue by yosiz** [GibbsConsulting/django-plotly-dash#121]
setting serve_locally to True when creating DjangoDash seems to result in an error,
is there anything that needs to be done for this to work?

Also,
was trying to add local css files which doesn't seem to work - not sure what is the correct way of doing it

Tried:
app.css.append_css('/static/loader.css')

(to load the 'loading...' animation for long callbacks)

**Comment by GibbsConsulting** [comment]
This is similar to #37 and needs coding - hence #122

As a workaround until a fix is available, you could use the not-in-iframe approach and add the css to your page template.

**Comment by GibbsConsulting** [comment]
@yosiz can you provide more colour on your comments regarding `serve_locally` not working? For component constituents (as opposed to extra content in an application assets subdirectory) this should be working.

**Comment by yosiz** [comment]
It might be that I'm not doing it correctly,
Do I need to generate the just scripts and css locally for the serve locally to work?
I just set it to true and it couldn't find all the assets

**Comment by GibbsConsulting** [comment]
At the moment, the `serve_locally` flag works for components, up to limitations from the underlying Dash implementation. Hence the workaround in #84

Independently of this flag, django-plotly-dash does not currently serve any local assets (from the assets subdirectory or similar), hence #122 

Until that is done, your best workaround is to use your own template - ie something based on the [plotly-direct](https://django-plotly-dash.readthedocs.io/en/latest/template_tags.html#the-plotly-direct-template-tag) template tag

**Comment by GibbsConsulting** [comment]
Local assets should now work as #133 has been merged to trunk and released in 0.9.9, although the documentation is not as good as one might wish.
Each component should be picked up by the static files finders, as should each `assets` directory associated with a `DjangoDash` instance.
