### ISSUE TITLE
Replace dash layout and callbacks for each django view call

### ISSUE THREAD

**Issue by ivan-katkov** [GibbsConsulting/django-plotly-dash#130]
In my application django view function generates dataset which will be used for Dash dashboard. The problem is that different datasets have different number of objects, therefore dash layout and callback functions have to be different for each dataset (depending on number of objects).

The following mechanisms i) passing context by using `expanded_callback`; or ii) passing dataset via cache before dash component registering; do not work because for the next view call the new layout and new set of callbacks will be required. There is no way to generate new callbacks within callback. All callbacks have to be registered before dash app stars (see [Dynamic Controls and Dynamic Output Components](https://community.plot.ly/t/dynamic-controls-and-dynamic-output-components/5519)).

Is there way to start dash app for each new view call (and stop it later)?

I would be very appreciated any advices and thoughts!

**Comment by eddy-ojb** [comment]
I am not sure I understand the problem. You mentioned that "django view function generates dataset". Why not move this logic to a callback? You could return a layout in a callback depending on the objects created in that function

**Comment by ivan-katkov** [comment]
Thanks for comment! 

This is exactly that I'm doing now. But depending on the datasets my layout should contain different number of plotly graph objects and dedicated callbacks (they all have to be interact between each other). Therefore, I need to register a given number of callbacks before I will obtain access to my dataset in one of the `expanded_callbacks`. 

My plain current solution is to make an exceeded number of empty and hidden graph objects with the dedicated callbacks. I know maximum number of objects among all my datasets. Then update first N graph objects according to the given dataset.

**Comment by GibbsConsulting** [comment]
@ivan-katkov are you trying to have what is essentially multiple components within a single page? If so then there are a number of levels where the different layout could be handled - within a single Dash component (which is what I think you are describing), multiple Dash tabs, or multiple non-Dash tabs each containing one or more Dash components. Communicating between the different views will dictate which of these is the best/easiest/cleanest way forward.

If session state is a good choice for this communication then django-plotly-dash with multiple Dash components is probably a good fit. However, dynamically changing the layout doesn't sound that pleasant in the underlying Dash library and I don't think it will work well when confronted with the django-plotly-dash wrapper.
