### ISSUE TITLE
Use case - Django Plotly Dash vs Rendering Plotly Directly?

### ISSUE THREAD

**Issue by leekocytes** [GibbsConsulting/django-plotly-dash#131]
Hi all,

I have a somewhat general question regarding what the best fit for using django-plotly-dash to render dashboards with Django vs simply rendering Plotly directly with Django views. I know this potentially crosses into a Dash vs Plotly conversations as well, but from a high level when would you recommend using django-plotly-dash vs using Plotly? 

It seems to me if you need ability to add real time components as well as more easily make graphs interactive with callbacks then django-plotly-dash enables more sophisticated functionally. More simple use cases may make more sense for Plotly?

Thanks for any guidance!

**Comment by GibbsConsulting** [comment]
This is discussed in the documentation [here](https://django-plotly-dash.readthedocs.io/en/latest/introduction.html) - the goal of django-plotly-dash is to enable the use of Dash from Django, given that the use of Django has already been decided. If you don't need any of the features that are offered by either Django or django-plotly-dash, then you probably do not want the added complexity of using either of them.

**Comment by leekocytes** [comment]
Thanks!
