### ISSUE TITLE
ConnectionRefusedError, Error 10061 on demo project

### ISSUE THREAD

**Issue by NosWiz** [GibbsConsulting/django-plotly-dash#136]
Hello,

I am using a Windows 10 PC from my workplace and invested some hours to get all install scripts etc. working. I finally managed to get everything installed and can run the Django server.

I can connect to the server via localhost:8000 and see the main page. Though, the connection does not work with http://127.0.0.1:8000. It seems like Django is running without problems, but when I go to any example page, the server console always outputs a ConnectionRefusedError. When I go to the page of example 2, it even shows error 10061 ([ConnectionError at _demo-two.pdf](https://github.com/GibbsConsulting/django-plotly-dash/files/3063549/ConnectionError.at._demo-two.pdf)). After any of these errors occurs, the server does not work anymore and needs to be restarted.

It seems like the ports are blocked or something similar. I found related issues, but they did not state this exact problem. Inputting this into the requirements.txt and dev_requirements.txt did also not help: https://github.com/GibbsConsulting/django-plotly-dash/issues/126#issuecomment-472019350

Next, I tried to resolve all version conflicts and downgrade several versions of different packages, but then, the server did not even start anymore.

I tried out the server without any network connection, inside the company's internal and external network.

One thing that I can not change is that there is McAfee Endpoint Security installed. It cannot be closed or deactivated (or I just did not find a way to do that with my Admin privileges).

This are the batch files i wrote for installation and starting the server:

installer.bat

`
@echo off
cd %~dp0
echo.
echo Welcome!
echo.
echo This is a Windows install script for Python, Django and Django Plotly Dash.
echo.
echo.
echo.
echo Current directory: %CD%
echo.
:directory
set /P c=Did you run this script from the desired installation directory? [Y/N]
if /I "%c%" EQU "Y" goto :directory_yes
if /I "%c%" EQU "N" goto :directory_no
goto :directory

:directory_no
echo.
echo Please move this file to the desired installation directory.
echo Press any key to exit.
pause
exit

:directory_yes
echo.
echo.
:python
set /P c=Is Python 3 installed? [Y/N]
if /I "%c%" EQU "Y" goto :python_yes
if /I "%c%" EQU "N" goto :python_no
goto :python

:python_no
echo.
echo Please download and install Python 3.
start "" https://www.python.org/downloads/
echo.
echo.
goto :python

:python_yes
echo.
echo.
:cpp
set /P c=Are the Visual C^+^+ Build Tools installed? [Y/N]
if /I "%c%" EQU "Y" goto :cpp_yes
if /I "%c%" EQU "N" goto :cpp_no
goto :cpp

:cpp_no
echo.
echo.
echo Please download the Visual C^+^+ Build Tools:
echo Go to: Tools for Visual Studio 2019 -^> Build Tools for Visual Studio 2019.
echo.
echo Download and run the application
echo Install: Workloads -^> C^+^+-Buildtools
timeout /t 3 /nobreak > NUL
start "" https://visualstudio.microsoft.com/de/downloads/
echo.
echo.
goto :cpp

:cpp_yes
echo.
echo.
echo Current directory: %CD%
:project
set /P c=Did you download and unzip the GIT project into this folder? [Y/N]
if /I "%c%" EQU "Y" goto :project_yes
if /I "%c%" EQU "N" goto :project_no
goto :project

:project_no
echo.
echo.
echo Please download the project:
echo Click on 'Clone or download -^> Download ZIP.
echo.
echo When finished, unzip the archive to:
echo %cd%
timeout /t 3 /nobreak > NUL
start "" https://github.com/GibbsConsulting/django-plotly-dash
echo.
echo.
goto :project

:project_yes
IF NOT EXIST django-plotly-dash-master\ GOTO folder_no
echo.
echo.
echo Starting Installation
echo.
CD django-plotly-dash-master
echo moved to: %CD%
echo.

pip install virtualenv

virtualenv -p python env

:: this call runs the following script in the virtualenv:
::
:: call env\Scripts\activate
:: pip install -r requirements.txt
:: pip install -r dev_requirements.txt
:: pip install pypiwin32
:: python setup.py develop
cmd /k "cd env\Scripts & activate & cd../.. &pip install -r requirements.txt & pip install -r dev_requirements.txt & pip install pypiwin32 & python setup.py develop & exit"
echo.
echo.
echo Successfully installed the environment in virtualenv
echo.
echo Note: The test server can be started by running "start_server.bat".
echo.
echo Press any key to exit.
echo.
pause
exit

:folder_no
echo.
echo.
echo the folder "django-plotly-dash-master" was not found. Are you in the right directory?
echo Please unzip the GIT files into this folder.
echo.
echo Current directory: %CD%
echo.
echo.
goto :project
`

start_demo_server.bat - run as administrator

`
@echo off
cd %~dp0
:: This batch runs the following script:
:: 
:: cd demo
:: python manage.py migrate
:: python manage.py shell < configdb.py
:: python manage.py collectstatic -i "*.py" -i "*.pyc" --noinput --link
:: python manage.py runserver

:: Check if the project folder exists.
:project_yes
IF NOT EXIST django-plotly-dash-master\ GOTO folder_no
cd django-plotly-dash-master

:: Run the script
cmd /k "cd env\Scripts & activate & cd ../../demo & echo %CD% & python manage.py migrate & python manage.py shell < configdb.py & python manage.py collectstatic -i "*.py" -i "*.pyc" --noinput --link & python manage.py runserver & deactivate"

exit

:folder_no
echo.
echo.
echo The folder "django-plotly-dash-master" was not found.
echo This file needs to be in the parent folder of "django-plotly-dash-master".
echo.
echo.
echo For more information, please run "install.bat" first.
echo.
echo Current directory: %CD%
echo.
echo Press any key to exit.
pause
exit
`

**Comment by GibbsConsulting** [comment]
That connection error is because you don't have Redis running.

See [this part](https://django-plotly-dash.readthedocs.io/en/latest/installation.html#extra-steps-for-live-state) of the documentation for the installation instructions.

**Comment by NosWiz** [comment]
thank you for the information, i will try that out.

If running Redis is required, then why is it not included in the manual for the demo project? Or does this issue only exist on Windows?

**Comment by NosWiz** [comment]
Okay, so now I ran:
`pip install channels daphne redis django-redis channels-redis`
I added the following line to the Installer:
`docker pull redis:4`
I changed the server starter batch like this:
`cmd /k "env\Scripts\activate & docker run -p 6379:6379 -d redis & [...] & python manage.py runserver & deactivate"`

I uninstalled everything, then I installed Docker Desktop for Windows and downloaded the up to date version of this git with the correct versions in requirements.txt.

I reinstalled everything, but the apps are still not working. Instead of the 10061 error, now the demo-two page is loading, but the server halts with the following output line:


49d71551be57bdfd9ebf268f148e7bd83f048101c0fae94874a8353356c94e9f
C:\Users\christian.weitzel\Documents\400 - Eclipse\django-plotly-dash-master
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, django_plotly_dash, sessions
Running migrations:
  No migrations to apply.
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
now exiting InteractiveConsole...

[...]

0 static files symlinked to 'C:\Users\christian.weitzel\Documents\400 - Eclipse\django-plotly-dash-master\demo\staticfiles', 180 unmodified.
Performing system checks...

System check identified no issues (0 silenced).
April 11, 2019 - 11:55:12
Django version 2.1.8, using settings 'demo.settings'
Starting ASGI/Channels version 2.1.7 development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
HTTP GET / 200 [0.24, 127.0.0.1:59236]
HTTP GET /demo-two 200 [0.16, 127.0.0.1:59236]
IN INTERPOLATE INDEX
IN INTERPOLATE INDEX

[...]

HTTP GET /django_plotly_dash/instance/simpleexample-1/initial/dpd-initial-args-d4fb4447380e46d181fb33f376beba97/ 200 [0.05, 127.0.0.1:59237]
HTTP GET /django_plotly_dash/instance/simpleexample-1/ 200 [0.05, 127.0.0.1:59236]
HTTP GET /django_plotly_dash/instance/simpleexample-1/initial/dpd-initial-args-d4fb4447380e46d181fb33f376beba97/_dash-component-suites/dash_renderer/react@15.4.2.min.js?v=0.19.0&m=1554892012 302 [0.03, 127.0.0.1:59236]
HTTP GET /django_plotly_dash/instance/simpleexample-1/initial/dpd-initial-args-d4fb4447380e46d181fb33f376beba97/_dash-component-suites/dash_html_components/dash_html_components.min.js?v=0.13.5&m=1554892113 302 [0.03, 127.0.0.1:59238]
HTTP GET /django_plotly_dash/instance/simpleexample-1/initial/dpd-initial-args-d4fb4447380e46d181fb33f376beba97/_dash-component-suites/dash_renderer/react-dom@15.4.2.min.js?v=0.19.0&m=1554892012 302 [0.04, 127.0.0.1:59237]
HTTP GET /django_plotly_dash/instance/simpleexample-1/initial/dpd-initial-args-d4fb4447380e46d181fb33f376beba97/_dash-component-suites/dash_bootstrap_components/_components/dash_bootstrap_components.min.js?v=0.4.0&m=1554892070 302 [0.04, 127.0.0.1:59236]
HTTP GET /django_plotly_dash/instance/simpleexample-1/initial/dpd-initial-args-d4fb4447380e46d181fb33f376beba97/_dash-component-suites/dpd_components/bundle.js?v=0.1.0&m=1554892070 302 [0.02, 127.0.0.1:59238]
HTTP GET /django_plotly_dash/instance/simpleexample-1/initial/dpd-initial-args-d4fb4447380e46d181fb33f376beba97/_dash-component-suites/dash_core_components/plotly-1.44.3.min.js?v=0.43.1&m=1554892009 302 [0.02, 127.0.0.1:59237]
HTTP GET /django_plotly_dash/instance/simpleexample-1/initial/dpd-initial-args-d4fb4447380e46d181fb33f376beba97/_dash-component-suites/dash_core_components/dash_core_components.min.js?v=0.43.1&m=1554892009 302 [0.02, 127.0.0.1:59236]
HTTP GET /django_plotly_dash/instance/simpleexample-1/initial/dpd-initial-args-d4fb4447380e46d181fb33f376beba97/_dash-component-suites/dash_renderer/dash_renderer.min.js?v=0.19.0&m=1554892012 302 [0.02, 127.0.0.1:59238]
HTTP GET /django_plotly_dash/instance/simpleexample-1/_dash-component-suites/dash_renderer/react@15.4.2.min.js?v=0.19.0&m=1554892012 302 [0.02, 127.0.0.1:59237]
HTTP GET /django_plotly_dash/instance/simpleexample-1/_dash-component-suites/dash_renderer/react-dom@15.4.2.min.js?v=0.19.0&m=1554892012 302 [0.04, 127.0.0.1:59236]
HTTP GET /django_plotly_dash/instance/simpleexample-1/_dash-component-suites/dash_bootstrap_components/_components/dash_bootstrap_components.min.js?v=0.4.0&m=1554892070 302 [0.02, 127.0.0.1:59237]
HTTP GET /django_plotly_dash/instance/simpleexample-1/_dash-component-suites/dash_html_components/dash_html_components.min.js?v=0.13.5&m=1554892113 302 [0.03, 127.0.0.1:59238]
HTTP GET /django_plotly_dash/instance/simpleexample-1/_dash-component-suites/dash_core_components/plotly-1.44.3.min.js?v=0.43.1&m=1554892009 302 [0.02, 127.0.0.1:59237]
HTTP GET /django_plotly_dash/instance/simpleexample-1/_dash-component-suites/dpd_components/bundle.js?v=0.1.0&m=1554892070 302 [0.02, 127.0.0.1:59236]
HTTP GET /django_plotly_dash/instance/simpleexample-1/_dash-component-suites/dash_core_components/dash_core_components.min.js?v=0.43.1&m=1554892009 302 [0.03, 127.0.0.1:59238]
HTTP GET /static/dash/component/dash_renderer/react@15.4.2.min.js 404 [0.01, 127.0.0.1:59236]
HTTP GET /static/dash/component/dash_html_components/dash_html_components.min.js 404 [0.01, 127.0.0.1:59238]
HTTP GET /django_plotly_dash/instance/simpleexample-1/_dash-component-suites/dash_renderer/dash_renderer.min.js?v=0.19.0&m=1554892012 302 [0.02, 127.0.0.1:59237]
HTTP GET /static/dash/component/dash_bootstrap_components/_components/dash_bootstrap_components.min.js 404 [0.01, 127.0.0.1:59238]
HTTP GET /static/dash/component/dash_renderer/react-dom@15.4.2.min.js 404 [0.02, 127.0.0.1:59236]
HTTP GET /static/dash/component/dpd_components/bundle.js 404 [0.02, 127.0.0.1:59237]
HTTP GET /static/dash/component/dash_renderer/dash_renderer.min.js 404 [0.01, 127.0.0.1:59237]
HTTP GET /static/dash/component/dash_core_components/plotly-1.44.3.min.js 404 [0.02, 127.0.0.1:59238]
HTTP GET /static/dash/component/dash_core_components/dash_core_components.min.js 404 [0.02, 127.0.0.1:59236]
HTTP GET /static/dash/component/dash_renderer/react@15.4.2.min.js 404 [0.02, 127.0.0.1:59237]
HTTP GET /static/dash/component/dash_bootstrap_components/_components/dash_bootstrap_components.min.js 404 [0.01, 127.0.0.1:59236]
HTTP GET /static/dash/component/dash_html_components/dash_html_components.min.js 404 [0.02, 127.0.0.1:59238]
HTTP GET /static/dash/component/dash_renderer/react-dom@15.4.2.min.js 404 [0.01, 127.0.0.1:59237]
HTTP GET /static/dash/component/dpd_components/bundle.js 404 [0.02, 127.0.0.1:59236]
HTTP GET /django_plotly_dash/instance/simpleexample-1/initial/dpd-initial-args-d4fb4447380e46d181fb33f376beba97/_dash-component-suites/dash_html_components/dash_html_components.min.js?v=0.13.5&m=1554892113 302 [0.04, 127.0.0.1:59238]
HTTP GET /static/dash/component/dash_core_components/plotly-1.44.3.min.js 404 [0.02, 127.0.0.1:59245]
HTTP GET /static/dash/component/dash_renderer/dash_renderer.min.js 404 [0.02, 127.0.0.1:59244]
HTTP GET /django_plotly_dash/instance/simpleexample-1/_dash-component-suites/dash_html_components/dash_html_components.min.js?v=0.13.5&m=1554892113 302 [0.03, 127.0.0.1:59237]
HTTP GET /static/dash/component/dash_core_components/dash_core_components.min.js 404 [0.03, 127.0.0.1:59246]
HTTP GET /static/dash/component/dash_html_components/dash_html_components.min.js 404 [0.01, 127.0.0.1:59244]
HTTP GET /static/dash/component/dash_html_components/dash_html_components.min.js 404 [0.01, 127.0.0.1:59244]
HTTP GET /django_plotly_dash/instance/simpleexample-1/initial/dpd-initial-args-d4fb4447380e46d181fb33f376beba97/_dash-component-suites/dash_bootstrap_components/_components/dash_bootstrap_components.min.js?v=0.4.0&m=1554892070 302 [0.02, 127.0.0.1:59246]
HTTP GET /django_plotly_dash/instance/simpleexample-1/_dash-component-suites/dash_bootstrap_components/_components/dash_bootstrap_components.min.js?v=0.4.0&m=1554892070 302 [0.01, 127.0.0.1:59244]
HTTP GET /static/dash/component/dash_bootstrap_components/_components/dash_bootstrap_components.min.js 404 [0.01, 127.0.0.1:59246]
HTTP GET /static/dash/component/dash_bootstrap_components/_components/dash_bootstrap_components.min.js 404 [0.01, 127.0.0.1:59246]
HTTP GET /django_plotly_dash/instance/simpleexample-1/initial/dpd-initial-args-d4fb4447380e46d181fb33f376beba97/_dash-component-suites/dpd_components/bundle.js?v=0.1.0&m=1554892070 302 [0.01, 127.0.0.1:59244]
HTTP GET /django_plotly_dash/instance/simpleexample-1/_dash-component-suites/dpd_components/bundle.js?v=0.1.0&m=1554892070 302 [0.01, 127.0.0.1:59246]
HTTP GET /static/dash/component/dpd_components/bundle.js 404 [0.01, 127.0.0.1:59244]
HTTP GET /static/dash/component/dpd_components/bundle.js 404 [0.01, 127.0.0.1:59244]
HTTP GET /django_plotly_dash/instance/simpleexample-1/initial/dpd-initial-args-d4fb4447380e46d181fb33f376beba97/_dash-component-suites/dash_core_components/plotly-1.44.3.min.js?v=0.43.1&m=1554892009 302 [0.01, 127.0.0.1:59246]
HTTP GET /static/dash/component/dash_core_components/plotly-1.44.3.min.js 404 [0.01, 127.0.0.1:59244]
HTTP GET /django_plotly_dash/instance/simpleexample-1/_dash-component-suites/dash_core_components/plotly-1.44.3.min.js?v=0.43.1&m=1554892009 302 [0.02, 127.0.0.1:59246]
HTTP GET /static/dash/component/dash_core_components/plotly-1.44.3.min.js 404 [0.01, 127.0.0.1:59246]
HTTP GET /django_plotly_dash/instance/simpleexample-1/initial/dpd-initial-args-d4fb4447380e46d181fb33f376beba97/_dash-component-suites/dash_core_components/dash_core_components.min.js?v=0.43.1&m=1554892009 302 [0.02, 127.0.0.1:59244]
HTTP GET /static/dash/component/dash_core_components/dash_core_components.min.js 404 [0.01, 127.0.0.1:59246]
HTTP GET /django_plotly_dash/instance/simpleexample-1/_dash-component-suites/dash_core_components/dash_core_components.min.js?v=0.43.1&m=1554892009 302 [0.01, 127.0.0.1:59244]
HTTP GET /static/dash/component/dash_core_components/dash_core_components.min.js 404 [0.01, 127.0.0.1:59246]
HTTP GET /django_plotly_dash/instance/simpleexample-1/initial/dpd-initial-args-d4fb4447380e46d181fb33f376beba97/_dash-component-suites/dash_renderer/dash_renderer.min.js?v=0.19.0&m=1554892012 302 [0.01, 127.0.0.1:59244]
HTTP GET /static/dash/component/dash_renderer/dash_renderer.min.js 404 [0.01, 127.0.0.1:59246]
HTTP GET /django_plotly_dash/instance/simpleexample-1/_dash-component-suites/dash_renderer/dash_renderer.min.js?v=0.19.0&m=1554892012 302 [0.01, 127.0.0.1:59244]
HTTP GET /static/dash/component/dash_renderer/dash_renderer.min.js 404 [0.00, 127.0.0.1:59244]

**Comment by GibbsConsulting** [comment]
So that looks like missing static files. Did you replicate all of the steps in the ``prepare_demo`` script?

**Comment by esloch** [comment]
Same problem here: 'dash/component/dash_core_components/highlight.pack.js' could not be found".

**Comment by scythargon** [comment]
`dash_bootstrap_components.min.js` not found:(

**Comment by apiljic** [comment]
I have the same issue:

> GET http://0.0.0.0:8000/static/dash/component/dash_core_components/highlight.pack.js net::ERR_ABORTED 404 (Not Found)

Haven't been able to fix it so far.

**Comment by kartom** [comment]
Same problem here, Django serves all static files, except those in the dash library.
I.e: /static/admin/css/base.css works fine, 
but /static/dash/dash_renderer/dash_renderer.dev.js does not although both files exists in the static directory.
I suppose django_plotly_dash somehow redirects that direcoty to some other place, but here ends my knowledge of the system...

**Comment by GibbsConsulting** [comment]
The various errors quoted here are all consistent with missing static files and suggest that at least one of the installation and configuration steps has either been missed or has failed.

If anyone is in a position to describe how the issue can be replicated, that would be most helpful. Otherwise it is impossible to diagnose further.

**Comment by kartom** [comment]
I was running on windows and missed the --nostatic option to runserver. Adding that and everything worked fine.

However, i suspect there is something wrong with the serving of static files. The collect static files finds the necesseary js files for dash_bootstrap_components, but the static files finders does not manage to serve them. So in order to get it working you have to collect the static files and turn off the static file finders, wich is a bit cumbersome. Could this be fixed so that the boostrap components can work "out of the box" as the other components?

**Comment by GibbsConsulting** [comment]
@kartom In order to determine if there is a problem, rather than just incorrect configuration, it would be helpful if you could supply some information about the installation and configuration steps that you have taken. Without that, it is not possible to comment further.

For example, the settings [here](https://django-plotly-dash.readthedocs.io/en/latest/configuration.html#configuration-options) and also [here](https://django-plotly-dash.readthedocs.io/en/latest/local_assets.html#local-assets) impact the serving of these assets.
