### ISSUE TITLE
AttributeError after manage.py migrate

### ISSUE THREAD

**Issue by codycrossley** [GibbsConsulting/django-plotly-dash#14]
I followed the installation steps [here](https://django-plotly-dash.readthedocs.io/en/latest/installation.html). When I run `manage.py migrate`, I receive the following error:

> AttributeError: 'Settings' object has no attribute 'PLOTLY_DASH'

Can you either help me understand why this error is occurring or check to see if this is just a bug?

I've attached my requirements.txt here if you need my specific versioning.
[requirements.txt](https://github.com/GibbsConsulting/django-plotly-dash/files/2208252/requirements.txt)

**Comment by codycrossley** [comment]
I got the error to go away by adding

`PLOTLY_DASH = ''`

to my settings.py file. Can you help me understand why this worked—and also what I _should_ set `PLOTLY_DASH` equal to?

**Comment by GibbsConsulting** [comment]
Its a bug, as the code should just use defaults with no values set - thanks for the
report. The workaround is to set
`
PLOTLY_DASH = { }
`
which will cause the default values to be used.
Will push a fix soon - note that the workaround will remain valid.

**Comment by GibbsConsulting** [comment]
Fixed with PR #24 which is part of the upcoming 0.5.1 prerelease
