### ISSUE TITLE
updating to latest dash version seems to break the app

### ISSUE THREAD

**Issue by yosiz** [GibbsConsulting/django-plotly-dash#142]
Can you specify which version are supported?

i upgraded to the following and the app fails to load:
it is stuck on the 'Loading...' text (no error in the server log)

installed versions:
dash                            0.41.0    
dash-bootstrap-components       0.3.4     
dash-core-components            0.46.0    
dash-dangerously-set-inner-html 0.0.2     
dash-daq                        0.1.4     
dash-html-components            0.15.0    
dash-renderer                   0.22.0    
dash-table                      3.6.0
django-plotly-dash              0.9.9     
dpd-components                  0.1.0     
dpd-static-support              0.0.2  
plotly                          3.8.0     

errors from the browses console:
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.

**Comment by GibbsConsulting** [comment]
The file [frozen_dev.txt](https://github.com/GibbsConsulting/django-plotly-dash/blob/master/frozen_dev.txt) contains all the packages that were present in the environment when the release was packaged.
Is this the demo app or something else?

**Comment by Lucianovici** [comment]
Not sure if you have the same issue as me, but since the docs are not yet finalised, make sure you have the correct `STATICFILES_FINDERS` and `PLOTLY_COMPONENTS`, then run the `collectstatic`.

[Demo settings example here](https://github.com/GibbsConsulting/django-plotly-dash/blob/c50decc7028f0dc8825632e551da94212afb8027/demo/demo/settings.py#L182-L201).

You can get inspire from https://github.com/GibbsConsulting/django-plotly-dash/blob/master/prepare_demo#L7

**Comment by yosiz** [comment]
i tested with the latest demo app
the following demos are stuck on "Loading..."

Demo 5- Direct App Embedding
Demo 6 - Simple embedding


`
pip list
Package                         Version 
------------------------------- --------
aioredis                        1.2.0   
alabaster                       0.7.12  
argh                            0.26.2  
asgiref                         3.1.2   
astroid                         2.2.5   
async-timeout                   3.0.1   
atomicwrites                    1.3.0   
attrs                           19.1.0  
autobahn                        19.3.3  
Automat                         0.7.0   
Babel                           2.6.0   
bleach                          3.1.0   
bootstrap4                      0.1.0   
certifi                         2019.3.9
channels                        2.2.0   
channels-redis                  2.4.0   
chardet                         3.0.4   
Click                           7.0     
colorama                        0.4.1   
constantly                      15.1.0  
coverage                        4.5.3   
daphne                          2.3.0   
dash                            0.42.0  
dash-bootstrap-components       0.5.0   
dash-core-components            0.47.0  
dash-dangerously-set-inner-html 0.0.2   
dash-daq                        0.1.4   
dash-html-components            0.16.0  
dash-renderer                   0.23.0  
dash-table                      3.6.0   
decorator                       4.4.0   
Django                          2.2     
django-bootstrap4               0.0.8   
django-plotly-dash              0.9.10  
django-redis                    4.10.0  
docopt                          0.6.2   
docutils                        0.14    
dpd-components                  0.1.0   
dpd-static-support              0.0.3   
et-xmlfile                      1.0.1   
Flask                           1.0.2   
Flask-Compress                  1.4.0   
grip                            4.5.2   
hiredis                         1.0.0   
hyperlink                       19.0.0  
idna                            2.8     
imagesize                       1.1.0   
incremental                     17.5.0  
ipython-genutils                0.2.0   
isort                           4.3.17  
itsdangerous                    1.1.0   
jdcal                           1.4.1   
Jinja2                          2.10.1  
jsonschema                      3.0.1   
jupyter-core                    4.4.0   
lazy-object-proxy               1.3.1   
livereload                      2.6.0   
Markdown                        3.1     
MarkupSafe                      1.1.1   
mccabe                          0.6.1   
more-itertools                  7.0.0   
msgpack                         0.6.1   
nbformat                        4.4.0   
numpy                           1.16.3  
openpyxl                        2.6.2   
packaging                       19.0    
pandas                          0.24.2  
path-and-address                2.0.1   
pathtools                       0.1.2   
pip                             9.0.1   
pkginfo                         1.5.0.1 
plotly                          3.8.1   
pluggy                          0.9.0   
port-for                        0.3.1   
py                              1.8.0   
Pygments                        2.3.1   
PyHamcrest                      1.9.0   
pylint                          2.3.1   
pymongo                         3.8.0   
pyparsing                       2.4.0   
pypiwin32                       223     
pyrsistent                      0.15.1  
pytest                          4.4.1   
pytest-cov                      2.6.1   
pytest-django                   3.4.8   
python-coveralls                2.9.1   
python-dateutil                 2.8.0   
pytz                            2019.1  
pywin32                         224     
PyYAML                          5.1     
readme-renderer                 24.0    
redis                           3.2.1   
requests                        2.21.0  
requests-toolbelt               0.9.1   
retrying                        1.3.3   
setuptools                      41.0.1  
six                             1.12.0  
snowballstemmer                 1.2.1   
Sphinx                          2.0.1   
sphinx-autobuild                0.7.1   
sphinxcontrib-applehelp         1.0.1   
sphinxcontrib-devhelp           1.0.1   
sphinxcontrib-htmlhelp          1.0.2   
sphinxcontrib-jsmath            1.0.1   
sphinxcontrib-qthelp            1.0.2   
sphinxcontrib-serializinghtml   1.1.3   
sqlparse                        0.3.0   
tornado                         6.0.2   
tqdm                            4.31.1  
traitlets                       4.3.2   
twine                           1.13.0  
Twisted                         19.2.0  
txaio                           18.8.1  
typed-ast                       1.3.5   
urllib3                         1.24.2  
watchdog                        0.9.0   
webencodings                    0.5.1   
Werkzeug                        0.15.2  
whitenoise                      4.1.2   
Whoosh                          2.7.4   
wrapt                           1.11.1  
XlsxWriter                      1.1.7   
zope.interface                  4.6.0   
`

**Comment by GibbsConsulting** [comment]
This should now be fixed in v0.9.11 following the merge of PR #151
