### ISSUE TITLE
Replace use of websocketbridge.js

### ISSUE THREAD

**Issue by delsim** [GibbsConsulting/django-plotly-dash#148]
The underlying `channels` library has a backwards-incompatible change in v2.1.4 - the file `websocketbridge.js` was removed.

The workaround is to require v2.1.3 of this package, but a better fix is to replace the use of websocketbridge.js in the messaging [template](https://github.com/GibbsConsulting/django-plotly-dash/blob/master/django_plotly_dash/templates/django_plotly_dash/plotly_messaging.html).

**Comment by scythargon** [comment]
@delsim Hi! To replace with what?

**Comment by GibbsConsulting** [comment]
Replace the use of `websocketbridge.js` with a new javascript file providing the equivalent functionality. The new file would be part of the `django-plotly-dash` distribution, removing the need to use a specific version of the `channels` library.

**Comment by GibbsConsulting** [comment]
Released as v1.2.0
