### ISSUE TITLE
Support for Clientside Callbacks in Dash 0.41.0

### ISSUE THREAD

**Issue by jchang10** [GibbsConsulting/django-plotly-dash#149]
The latest release of Dash 0.41.0 has a nifty feature called clientside callbacks. This is a great add-on.

I looked to see if there was an easy hook, but I failed to find one on initial inspection. The actual Dash code is super simple. They just slot in a new callback to be dispatched to the client. However, the way DPD wraps Dash, it was not obvious how to make this work. It feels like this should be a a simple add. I hope!

I removed the docstring which was 3x longer than the actual code itself.

https://community.plot.ly/t/dash-0-41-0-released/22131
https://github.com/plotly/dash/blob/ac10b2df1e49a153de00fc78b07242f439bb0b99/dash/dash.py#L983-L999

```
    def clientside_callback(self, clientside_function, output, inputs=[], state=[]):
        self._validate_callback(output, inputs, state)
        callback_id = _create_callback_id(output)


        self.callback_map[callback_id] = {
            'inputs': [
                {'id': c.component_id, 'property': c.component_property}
                for c in inputs
            ],
            'state': [
                {'id': c.component_id, 'property': c.component_property}
                for c in state
            ],
            'clientside_function': {
                'namespace': clientside_function.namespace,
                'function_name': clientside_function.function_name
            }
        }
```

**Comment by GibbsConsulting** [comment]
Closing as #165 addresses this.
