### ISSUE TITLE
Dash Datatable not rendering in Django plotly dash 

### ISSUE THREAD

**Issue by nd823** [GibbsConsulting/django-plotly-dash#150]
Hello!

First, great job on the package, it has been really useful!

I have been trying to use Dash Datatables in my Plotly dashboard, but nothing renders. The graphs are all working fine.

To reproduce the issue, I had started up a new Django app and tried to render the sample table given on the Dash Datatables site:

```import dash
import dash_table
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/solar.csv')

app = dash.Dash(__name__)

app.layout = dash_table.DataTable(
    id='table',
    columns=[{"name": i, "id": i} for i in df.columns],
    data=df.to_dict('records'),
)
```

The resulting page is completely blank. 

I have Dash 0.42.0 installed, which is the compatible version with Dash Datatable. I also installed the newest release of Django-Plotly-Dash.

Thank you so much for all your help, and please let me know what other information you need.

**Comment by delsim** [comment]
Not had a chance yet to try Dash v0.42.0, so this is more of a guess than anything else: did you add the appropriate components(`dash_table`, by the looks of things) to `PLOTLY_COMPONENTS` in the settings file and then update the static files; see the [configuration documentation](https://django-plotly-dash.readthedocs.io/en/latest/configuration.html) for an example of setting this variable.

If you look in a debugging console in your browser, you might be able to determine which files (if any) are not being loaded.

In passing, that example code doesn't use a `DjangoDash` instance. Not critical right now, but might be relevant if we need to dig deeper.

**Comment by nd823** [comment]
Thank you so much for the quick reply!

I'm sorry for the omission, but I did initialize a `DjangoDash` instance for the data table.

I added `dash_table` to `PLOTLY_COMPONENTS` and then ran `python manage.py collectstatic`, and now the table is displayed!
