### ISSUE TITLE
STATICFILES_FINDERS issue

### ISSUE THREAD

**Issue by qicqic99** [GibbsConsulting/django-plotly-dash#152]
I have downloaded all the files, and tried several times to run the server. But i got the error "No module named 'django_plotly_dash.finders" as the figure 1. There is the module as you can see in the figure 2. How to solve the problem? Thanks.

![f1](https://user-images.githubusercontent.com/39325813/57444730-60b0ea00-7283-11e9-8178-f62c499a3b6f.jpg)

![f2](https://user-images.githubusercontent.com/39325813/57444549-fbf58f80-7282-11e9-9a31-85e900e45656.jpg)

**Comment by GibbsConsulting** [comment]
Did you follow all of the installation instructions? It looks like `django_plotly_dash` is not on the python path.

**Comment by qicqic99** [comment]
I did install the django_plotly_dash, and tried to execute the migration command in demo. Did I miss something?

**Comment by GibbsConsulting** [comment]
Have you followed all of the steps described in [the installation instructions](https://django-plotly-dash.readthedocs.io/en/latest/installation.html)? Or did you follow [the development ones](https://django-plotly-dash.readthedocs.io/en/latest/development.html)?

The latter do look a bit dated but should still work. At what point do you get an error?

**Comment by qicqic99** [comment]
I have followed the installation instructions but created the new env. It successfully started the server with new env. Thanks you. @GibbsConsulting
