### ISSUE TITLE
Static Files Serve Locally Required v0.9.9+

### ISSUE THREAD

**Issue by VenturaFranklin** [GibbsConsulting/django-plotly-dash#153]
The static files seem to be required to be served locally now in a debug environment. With v0.9.8 and below I did not need to serve them locally, with v0.9.9+ the plotly_footer template tag seems to only load the locally served files, which I am not serving.

I am using:
```
Django==2.0.9
dash==0.42.0
plotly==3.9.0
```

It looks like in: https://github.com/GibbsConsulting/django-plotly-dash/blob/master/django_plotly_dash/util.py

for the `serve_locally` function it is assumed to match `settings.DEBUG`, but for me, while DEBUG is True, I don't want to serve locally.

The work around I needed was in my settings.py
```
PLOTLY_DASH = {
    'serve_locally': False
}
```

I don't know how you want to address, but I would guess most people would want the serve locally to be initially false and only set true if they know what they are doing.

Overall, thank you for your work. I appreciate it!

**Comment by GibbsConsulting** [comment]
Thanks @VenturaFranklin , you raise a good point. There wasn't much thought given to what the default value should be - after all, the main interest was in being able to switch at all! - and it should really default in a way that causes the minimal amount of hassle when upgrading.

If you want to dress up the change as a pull request, that would be most welcome - and would also make github recognise your contribution. If not, no worries - it will get added in the next batch of work pushed into the master branch one way or another.
