### ISSUE TITLE
demo.py not functioning

### ISSUE THREAD

**Issue by eddy-ojb** [GibbsConsulting/django-plotly-dash#16]
The demo that comes with the package does not work. Specifically, Demo 3 and 4 do not work with the respective end screen states shown in the image below.

My environment is on Windows and has all the packages installed as per requirements.txt and dev_requirements.txt.

<img width="958" alt="django_plotly_dash_capture" src="https://user-images.githubusercontent.com/26047714/43028629-decc2bd0-8c78-11e8-8e0c-20026716413e.PNG">

<img width="957" alt="django_plotly_dash_demo4" src="https://user-images.githubusercontent.com/26047714/43028636-e2f79104-8c78-11e8-93d4-ca74320ee377.PNG">

**Comment by delsim** [comment]
It looks like you have an older version of the Dash libraries. The button timestamp property is a recent addition. On my desktop I have:
```
(env) mark@mark-4x12 ~/local/django-plotly-dash $ pip freeze | grep dash
dash==0.21.1
dash-core-components==0.24.1
dash-html-components==0.11.0
dash-renderer==0.12.1
[info about local install of django-plotly-dash]
```
and a more recent install has even newer versions for dash-renderer and dash-core-components.

Are you in a position to report what versions you have? If they are older, then updating these using
```
pip install -U dash-renderer dash-html-components dash dash-core-components
```
should fix your immediate problem. That would still leave an issue as to why the requirements files aren't imposing minimum versions.

**Comment by eddy-ojb** [comment]
I have tried with the package versions you have and more recent versions:

- demo 4 works mostly but I haven't tried the Redis part - I am assuming this functionality is fine.
- demo3  stalls on the "loading..." section.

Another issue that I have noticed is that if working offline and clearing the cache, no demo page runs. Do I have to state somewhere to run offline?

I am now in the process of playing around and inserting my own examples to see what I can make work etc.

**Comment by delsim** [comment]
With 'demo3' are there any messages in the browser console or errors reported in the Django server session? And is it possible for you to also look and see if any files are not loading (other than logo.svg, which is missing from the repo still) using browser tools.

Which browser, btw? I do find that clearing the browser cache is sometimes necessary, especially when moving to new versions.

Running offline should work - you will need to add `serve_locally=True` to every DjangoDash constructor call.

**Comment by eddy-ojb** [comment]
I have been looking out for browser console errors. Happy to post my console if useful.
I see no errors (Dash is bad at returning errors so I am in awe that you wrote a package working with it) apart from a minor "'Not found: favicon.ico'" error.

Lots of missing sources in the browser console (see below) - this must be it. I haven't had time just yet to see where the connections are going wrong. Just to re-iterate, I haven't got Redis setup but I am assuming this shouldn't matter for JS content.

I use Chrome but I have also tried in Edge.

Thanks for the "clear cache" tip - that has previously caught me out big time and now I "ctrl + refresh" all the time.

![image](https://user-images.githubusercontent.com/26047714/43104031-e9cefa7a-8ec7-11e8-81d0-1ab3d4984003.png)

**Comment by delsim** [comment]
I think this is caused by some of the dash files not being on the path. At the end of the demo `settings.py` file there is this code to allow Django to serve locally the dash components when in debug mode:
```
# In order to serve dash components locally - not recommended in general, but
# can be useful for development especially if offline - we add in the root directory
# of each module. This is a bit of fudge and only needed if serve_locally=True is
# set on a DjangoDash instance.

if DEBUG:

    import importlib

    for dash_module_name in ['dash_core_components',
                             'dash_html_components',
                             'dash_renderer',
                             'dpd_components',
                            ]:

        module = importlib.import_module(dash_module_name)
        STATICFILES_DIRS.append(("dash/%s"%dash_module_name, os.path.dirname(module.__file__)))
```
I suspect you need this (or something similar), to use `manage.py collectstatic`, and perhaps also to add `dash` to the list of modules.

**Comment by eddy-ojb** [comment]
I sorted my issue by adding 'dash' to the list of dependencies, running the `collectstatic` command and making sure the assets were actually served for the django app.
