### ISSUE TITLE
Accessibility of Dash apps.

### ISSUE THREAD

**Issue by bgreenawald** [GibbsConsulting/django-plotly-dash#162]
One of the enticing things about embedding Dash in Django is being able to use Dash behind Django's security models (for visualizations of sensitive data). I'm not sure if this is a feasible idea, but restricting access to the underlying Dash visualization would be very powerful. That is to say, I can have authentication on the page hosting the embedded Dash app, but the visualization can still be accessed independently of that by going straight to the visualization URL. If the visualization could be injected straight into the webpage (i.e, using the plotly_direct tag), and then just removing access to the underlying visualization altogether, then Dash could securely be embedded.

**Comment by GibbsConsulting** [comment]
There is a [view decorator](https://django-plotly-dash.readthedocs.io/en/latest/configuration.html#view-decoration) that can be used for access control. The setting specifies a python function, so you can have as much (or as little) control as for any Django view.

**Comment by bgreenawald** [comment]
This is exactly what I needed, thanks!
