### ISSUE TITLE
How to setup the server on LAN

### ISSUE THREAD

**Issue by qicqic99** [GibbsConsulting/django-plotly-dash#172]
I've modified the ALLOWED_HOSTS = ['*'] in settings.py.
After that, restart the server with "manage.py runserver 0.0.0.0:8000 ".
Other devices in the same private network also can't reach the server.

**Comment by GibbsConsulting** [comment]
It is somewhat hard to diagnose what is going on given the limited information supplied.

The first thing to establish is if this is a network issue, or a django server configuration issue.

One way of checking the network would be to attempt access from the local machine, and also to validate access to the server machine using tools such as telnet and ping.

Django server configuration issues, such as incorrect ALLOWED_HOSTS, should manifest as errors either reported back to the client or by the server.
