### ISSUE TITLE
How to access template initial_arguments from dash app?

### ISSUE THREAD

**Issue by MikeZ77** [GibbsConsulting/django-plotly-dash#173]
For example I have the template.html:

`{% extends "dashboards/base_generic.html" %}
{% block content %}
{% load plotly_dash %}
{% plotly_app name="descriptive" ratio=0.75 initial_arguments='{"vehicle_data":{"make":"{{Make}}","model":"{{Model}}","year":"{{Year}}"}}' %}
{% endblock %}`

And in dash_app.py I have:
`app = DjangoDash(name='descriptive', id='vehicle_data')`

Kind of confused what method I would use to access 'vehicle_data'? Hopefully this is the right usage, new to Django and Dash.

**Comment by GibbsConsulting** [comment]
The initial arguments should match the identifier and property names in the application.

From your example, you'll probably run into problems trying to construct strings in this way within a Django template. It might be easier to construct the initial arguments within your view code rather than in the template.

**Comment by MikeZ77** [comment]
Hello, thanks for the response.

I understand now how to access the initial argument. I am using these values to query a database, clean/modify the data in a data frame, and then return a Graph object or similar. Right now I have a hidden drop down which is the Input for the callback. From what I understand callbacks are fired on page load so this should be fine. My problem right now is what you mentioned with the template. Adding a simple string works fine but I have not been able to use a variable. 

**View**
`
def dashboard_display(request,make,model,year):

    context = {'data':'\'{"vehicle_data":{"value":"'+make+' '+model+' '+year+'"}}\''}
    return render(request,'dashboards/descriptive_tmp.html',context)
`
**Template**
`
{% extends "dashboards/base_generic.html" %}
{% block content %}
{{data}}
{% load plotly_dash %}
{% plotly_app name="descriptive" ratio=0.75 initial_arguments=data %}
{% endblock %}
`
Tried a few different variations of this but nothing has worked. Given how you implemented this tag is it possible to do? I don't see any similar examples in the demo. Should I try using session variables instead? Thanks.

**Comment by MikeZ77** [comment]
Never mind, just had to remove the escaped characters which was causing issues with the Json parsing.

**Comment by jfrostburke** [comment]
@MikeZ77 could you paste your successful code here, especially your `dash_app.py` and final view and template? I'm also trying to access initial_arguments from my dash app but haven't seen any finished code on how to do it (although I've seen it mentioned in multiple issues).

**Comment by jfrostburke** [comment]
Result from me random-walking to the solution. For context, I was trying to access the id of a target in my database in an app that plots astronomical spectra.

### Views.py

My `views.py` was already returning a context about, so I just added to it. This set the layers to unpack (`dash_context`, `target_id`, `value`):
```python
context['dash_context'] = {'target_id': {'value': self.get_object().id}}
```

### template.html

In my template I had to pass that new context to the app:
```html
{% plotly_app name="Spectra" ratio=1.0 initial_arguments=dash_context %}
```

### dash_app.py

I did this when I defined the app:
```python
app = DjangoDash(name='Spectra', id='target_id')
```

When I defined the layout of the app I passed the target id in as a hidden input. The filler text got immediately overwritten so it's not the most elegant:
```python
app.layout = html.Div([
    . . .
    dcc.Input(id='target_id', type='hidden', value='filler text'),
    . . .
```

Then I had to pass in the value (the end goal that I wanted to access) in the callback:
```python
 @app.expanded_callback(
    . . .
    Input('target_id', 'value')])
def display_output(. . . value):
    print(value)
```

Hopefully this is helpful to anyone trying to solve this in the future.

**Comment by rmaranhao** [comment]
As I understand this allows us to set properties as in example demo two (https://djangoplotlydash.com/demo-two). Is there a way to pass a variable to a plotly app?
I have a situation where I allow the user to click on a link to product details. On the detail screen I don't want the product selector, so passing a property if of little use. So far, I have data as a dictionary, containing my product_id:

`def app_detalhamento(request, produtoempresa_id):
    data = {'data':{'produtoempresa_id':produtoempresa_id}}
    return render(request, 'precificacao/app_detalhamento.html', data)
`

I can print the data on the template:
`{% block content %}
<div id="apresenta">
		Dicionário com os dados: {{ data }}
		<div class="clearfix">
			{% plotly_app name="app_detalhamento" initial_arguments=data  %}
		</div>
</div>
{% endblock content %}
`

What I'd like to be able to do is to show the product ID (this is a bare bones example), something like this (I am terribly sorry for the number of lines as this could be a two liner, but it helps me debugging):
`app = DjangoDash('app_detalhamento', external_stylesheets=['https://codepen.io/chriddyp/pen/bWLwgP.css'])

layout = html.Div('Detalhamento do produto código:' + str(produtoempresa_id))
app.layout =  layout`

It seems agonizingly close, but I still cannot solve it. Thanks in advance for any ideas.

**Comment by nikhilnaregal** [comment]
> Result from me random-walking to the solution. For context, I was trying to access the id of a target in my database in an app that plots astronomical spectra.
> 
> ### Views.py
> My `views.py` was already returning a context about, so I just added to it. This set the layers to unpack (`dash_context`, `target_id`, `value`):
> 
> ```python
> context['dash_context'] = {'target_id': {'value': self.get_object().id}}
> ```
> 
> ### template.html
> In my template I had to pass that new context to the app:
> 
> ```
> {% plotly_app name="Spectra" ratio=1.0 initial_arguments=dash_context %}
> ```
> 
> ### dash_app.py
> I did this when I defined the app:
> 
> ```python
> app = DjangoDash(name='Spectra', id='target_id')
> ```
> 
> When I defined the layout of the app I passed the target id in as a hidden input. The filler text got immediately overwritten so it's not the most elegant:
> 
> ```python
> app.layout = html.Div([
>     . . .
>     dcc.Input(id='target_id', type='hidden', value='filler text'),
>     . . .
> ```
> 
> Then I had to pass in the value (the end goal that I wanted to access) in the callback:
> 
> ```python
>  @app.expanded_callback(
>     . . .
>     Input('target_id', 'value')])
> def display_output(. . . value):
>     print(value)
> ```
> 
> Hopefully this is helpful to anyone trying to solve this in the future.

I tried this solution but, the input element still not updating

**Comment by pperum002c** [comment]
@nikhilnaregal - I also have similar requirement and I wasn't able to find any solution for passing input from Django to Dash. However I found a workaround - that suits my requirement. Please check if its useful in your case.


**views.py**

```
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request, 'entry_ui_portion/home.html')

```

**home.html**

```
{%load plotly_dash%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Release Plan</title>
</head>

<body>
    {%plotly_app name="ReleasePlanning" ratio=0.75%}
</body>

</html>
```

Now In the actual dash layout file - call django model and iterate thru the query - DOING JUST THIS WILL NOT FIX THE ISSUE (Instead - In the dash layout file use live updates with this method: https://dash.plotly.com/live-updates

**example_dash_file.py**

```
from <app_name>.models import <modelname>
other imports....
...

app = DjangoDash(name='ReleasePlanning', suppress_callback_exceptions=True)

def getContent():
    datadf = []
    for rows in <modelname>.objects.all():
        da = {}
        da['fname'] = rows.fname
        da['lname'] = rows.lname
        da['experience'] = float(rows.experience)
        da['domain'] = rows.domain

        datadf.append(da)
    return datadf

def serve_layout():

    resultdf = getContent()

    return html.Div(children=[
        html.Div(children=[
            html.H1('Heading')
        ], style={'font-family': 'Verdana', 'text-align': 'center', 'padding-down': '20px'}),

app.layout = serve_layout

#callbacks below if any - if datadf used in any callback - call getContent again
```

This may not be an effective solution, but it served the purpose of what a data feed from django to dash does is cleared in this method.
