### ISSUE TITLE
django dash

### ISSUE THREAD

**Issue by osasblack** [GibbsConsulting/django-plotly-dash#175]
Please i'll love to setup a simple plotly dash app on django. Can you help me out?

**Comment by GibbsConsulting** [comment]
In the documentation the [installation](https://django-plotly-dash.readthedocs.io/en/latest/installation.html) section describes how to install this package.

The [README](https://github.com/GibbsConsulting/django-plotly-dash/blob/master/README.md) file in the github repository also describes how to run the demo application.

If you're looking for commercial help, then use the contact form on our website.
