### ISSUE TITLE
Tabbed Dash App (Run from Index.py) Compatibility?

### ISSUE THREAD

**Issue by privacc** [GibbsConsulting/django-plotly-dash#176]
Hi there,

Love the library and I think this is a phenomenal way to integrate Dash and Django for a project I'm working on. I've rendered the demo as well as a basic app successfully. When trying to import a tabbed dash app (that runs successfully on it's own), that utilizes the index.py file instead of the app.py to run, I receive the following error: 

NoLayoutException at /dashboards/index/

Which leads me to believe the issue is where the module that sets the layout is being pointed to. Any idea on this particular issue? Or support/nuances/changes that I can integrate to run from index instead of app within the django-plotly-dash framework? 

Thanks so much! 

-K

**Comment by GibbsConsulting** [comment]
It is a bit hard to comment without more information about your application structure. Are you in a position to give more detail?

**Comment by privacc** [comment]
<img width="288" alt="Screen Shot 2019-10-03 at 8 33 39 AM" src="https://user-images.githubusercontent.com/45473535/66126927-93ec7080-e5b8-11e9-8e5d-deca76a245eb.png">

- app.py
- index.py
- callbacks.py
- tabs/layouts folder 

Absolutely, thank you for the quick response; I've attached a screencap from Atom that shows the file structure. To give a bit more detail, the dash app is contained in the 'dash_apps_folder'. 

I know using an index file instead of the app file to run the app is unconventional, and may conflict with DPD so I wanted to see if that could be part of the problem. 

My initial thought was that I could import the functions that serve up the layout into app.py from index.py if the index file issue persists, but I haven't been able to successfully do so. 

Any thoughts and any more information I can provide? 

Best, 

-K

**Comment by GibbsConsulting** [comment]
The names of the files should not matter; the key requirement is that the one containing the main app content is imported.

This will be a file that imports `django_plotly_dash` and contains something along the lines of `app = DjangoDash(...)`. The content of this app would be a good place to start looking for the cause of the problem - it sounds like some component is generating URLs in a way that might not be compatible with dpd.

**Comment by privacc** [comment]
Completely understood, follow up question to the compatibility, do you know if any tabbed Dash Apps have successfully been integrated with DPD? And if so, any examples? 

The files are stored in a distributed nature; 'app.layout = (...)' is defined within the Index.py file (along with the callback for each tab-layout to be returned), whilst the 'app = DjangoDash(...)' component is defined in the app.py file. 
I have both files importing all components from one another, which I thought would solve the issue, but is it possible that the 'app = ...' & 'app.layout = ...' need to both be defined in the same file for DPD compatibility?

Aside from that, I'm unsure about how one of the components could be generating incompatible URLs, but it may take a lot of troubleshooting from my end.

**Comment by GibbsConsulting** [comment]
The files used should not matter, as long as they are imported.

Without any detail on the app in question, it is not really possible to comment on compatibility. One of the goals of this project is to have the widest possible range of Dash apps functional within Django, albeit with recognition that this range is unlikely to cover everything.

**Comment by privacc** [comment]
Thank you for your help!! I figured out that the distributed nature was the issue, got everything packed into the app.py file and it works flawlessly, very much appreciate you! 

As as aside, I'm sure you're familiar with 'Font Awesome' should that be imported just as bootstrap would be? Unsure if local or CDN should be used. Thanks so much!
