### ISSUE TITLE
How to implement a initially variative layout? 

### ISSUE THREAD

**Issue by scythargon** [GibbsConsulting/django-plotly-dash#177]
Hello!
Imagine that my initial layout depends on the logged in user. I know that `app.layout` can be passed a function, but seems there are no any arguments passed to it.
I mean before any callback are fired.

**Comment by scythargon** [comment]
I managed to do it like this:
```
app.layout = html.Div(id='layout')


@app.callback(
    Output('layout', 'children'),
    [Input('layout', 'id')]
)
def output_layout(*args, user, **kwargs):
```
but now when this function renders my layout - it does not get filled with data - no callbacks called

**Comment by GibbsConsulting** [comment]
You can't rely on `app.layout` being called once per use of the app, so adding a callback is definitely they way to go. However, you then need some way of triggering the callback, as they are not called until something changes. Perhaps adding an interval component with a short timeout to force invocation of some sort of initiation callback, followed by changing the interval to a very long one during this initiation, would work.
