### ISSUE TITLE
Passing data from django to dash

### ISSUE THREAD

**Issue by abskalana** [GibbsConsulting/django-plotly-dash#178]
Hi,
Thanks for your app. I appreciate it.

Currently, i'm using django and dash.  And I want to pass data (dataframe loading from database in django view) to dash for ploting. All example, I see does not work.

Could you explain me ?
`def main(request):
    data = ....
    return render(request, 'prediction.html', {'data': data})
`
And in Dash

`
app = DjangoDash('SimpleExample')

load data here

])

@app.callback(
    dash.dependencies.Output('output-color', 'children'),
    [dash.dependencies.Input('dropdown-color', 'value')])
def callback_color(dropdown_value):
    return "The selected color is %s." % dropdown_value

@app.callback(
    dash.dependencies.Output('output-size', 'children'),
    [dash.dependencies.Input('dropdown-color', 'value'),
     dash.dependencies.Input('dropdown-size', 'value')])
def callback_size(dropdown_color, dropdown_size):
or here load data here
    return "The chosen T-shirt is a %s %s one." %(dropdown_size,
                                                  dropdown_color)

`
The kward contain in the demo are empty on my side.
Thanks for your help.

**Comment by GibbsConsulting** [comment]
See the comments in #186 - the approach suggested there should work for you also.
