### ISSUE TITLE
KeyError with example from the docs

### ISSUE THREAD

**Issue by apiljic** [GibbsConsulting/django-plotly-dash#181]
Hello, 

I am trying to test django-plotly-dash.

I installed it with:

> pip install django_plotly_dash

Added to settings.py:
```
INSTALLED_APPS = [
    ...
    'django_plotly_dash.apps.DjangoPlotlyDashConfig',
    ...
    ]
```

Added to urls.py: 
```
urlpatterns = [
    ...
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
]
```

Ran:
> ./manage.py migrate

From the docs, Simple usage, I used the following code and saved it in dash_apps.py:

```
import dash
import dash_core_components as dcc
import dash_html_components as html

from django_plotly_dash import DjangoDash

app = DjangoDash('SimpleExample')   # replaces dash.Dash

app.layout = html.Div([
    dcc.RadioItems(
        id='dropdown-color',
        options=[{'label': c, 'value': c.lower()} for c in ['Red', 'Green', 'Blue']],
        value='red'
    ),
    html.Div(id='output-color'),
    dcc.RadioItems(
        id='dropdown-size',
        options=[{'label': i,
                  'value': j} for i, j in [('L','large'), ('M','medium'), ('S','small')]],
        value='medium'
    ),
    html.Div(id='output-size')

])

@app.callback(
    dash.dependencies.Output('output-color', 'children'),
    [dash.dependencies.Input('dropdown-color', 'value')])
def callback_color(dropdown_value):
    return "The selected color is %s." % dropdown_value

@app.callback(
    dash.dependencies.Output('output-size', 'children'),
    [dash.dependencies.Input('dropdown-color', 'value'),
     dash.dependencies.Input('dropdown-size', 'value')])
def callback_size(dropdown_color, dropdown_size):
    return "The chosen T-shirt is a %s %s one." %(dropdown_size,
                                                  dropdown_color)
```

I created a simple HTML template containing:
```
{% load plotly_dash %}
{% plotly_app name="SimpleExample" %}
```

I added the url to urls.py:
`url(r'^dash-test-initial/$', TemplateView.as_view(template_name="records/dash_test_initial.html")),`

Opening of the page gives me:

> Traceback (most recent call last):
>   File "/home/alen/django_epi3/venv/lib/python3.6/site-packages/werkzeug/middleware/dispatcher.py", line 66, in __call__
>     return app(environ, start_response)
>   File "/home/alen/django_epi3/venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
>     response = self.get_response(request)
>   File "/home/alen/django_epi3/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
>     response = self._middleware_chain(request)
>   File "/home/alen/django_epi3/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 36, in inner
>     response = response_for_exception(request, exc)
>   File "/home/alen/django_epi3/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
>     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
>   File "/home/alen/django_epi3/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
>     response = get_response(request)
>   File "/home/alen/django_epi3/venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
>     response = response or self.get_response(request)
>   [...]
>   File "/home/alen/django_epi3/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 36, in inner
>     response = response_for_exception(request, exc)
>   File "/home/alen/django_epi3/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
>     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
>   File "/home/alen/django_epi3/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
>     response = get_response(request)
>   File "/home/alen/django_epi3/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 145, in _get_response
>     response = self.process_exception_by_middleware(e, request)
>   File "/home/alen/django_epi3/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 143, in _get_response
>     response = response.render()
>   File "/home/alen/django_epi3/venv/lib/python3.6/site-packages/django/template/response.py", line 106, in render
>     self.content = self.rendered_content
>   File "/home/alen/django_epi3/venv/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
>     content = template.render(context, self._request)
>   File "/home/alen/django_epi3/venv/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
>     return self.template.render(context)
>   File "/home/alen/django_epi3/venv/lib/python3.6/site-packages/django/template/base.py", line 171, in render
>     return self._render(context)
>   File "/home/alen/django_epi3/venv/lib/python3.6/site-packages/django/test/utils.py", line 96, in instrumented_test_render
>     return self.nodelist.render(context)
>   File "/home/alen/django_epi3/venv/lib/python3.6/site-packages/django/template/base.py", line 937, in render
>     bit = node.render_annotated(context)
>   File "/home/alen/django_epi3/venv/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
>     return self.render(context)
>   File "/home/alen/django_epi3/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
>     return compiled_parent._render(context)
>   File "/home/alen/django_epi3/venv/lib/python3.6/site-packages/django/test/utils.py", line 96, in instrumented_test_render
>     return self.nodelist.render(context)
>   File "/home/alen/django_epi3/venv/lib/python3.6/site-packages/django/template/base.py", line 937, in render
>     bit = node.render_annotated(context)
>   File "/home/alen/django_epi3/venv/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
>     return self.render(context)
>   File "/home/alen/django_epi3/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
>     result = block.nodelist.render(context)
>   File "/home/alen/django_epi3/venv/lib/python3.6/site-packages/django/template/base.py", line 937, in render
>     bit = node.render_annotated(context)
>   File "/home/alen/django_epi3/venv/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
>     return self.render(context)
>   File "/home/alen/django_epi3/venv/lib/python3.6/site-packages/django/template/library.py", line 214, in render
>     _dict = self.func(*resolved_args, **resolved_kwargs)
>   File "/home/alen/django_epi3/venv/lib/python3.6/site-packages/django_plotly_dash/templatetags/plotly_dash.py", line 76, in plotly_app
>     da, app = _locate_daapp(name, slug, da, cache_id=cache_id)
>   File "/home/alen/django_epi3/venv/lib/python3.6/site-packages/django_plotly_dash/templatetags/plotly_dash.py", line 43, in _locate_daapp
>     da, app = DashApp.locate_item(name, stateless=True, cache_id=cache_id)
>   File "/home/alen/django_epi3/venv/lib/python3.6/site-packages/django_plotly_dash/models.py", line 196, in locate_item
>     dash_app = find_stateless_by_name(ident)
>   File "/home/alen/django_epi3/venv/lib/python3.6/site-packages/django_plotly_dash/models.py", line 76, in find_stateless_by_name
>     dash_app = get_stateless_by_name(name)
>   File "/home/alen/django_epi3/venv/lib/python3.6/site-packages/django_plotly_dash/models.py", line 36, in get_stateless_by_name
>     return get_local_stateless_by_name(name)
>   File "/home/alen/django_epi3/venv/lib/python3.6/site-packages/django_plotly_dash/dash_wrapper.py", line 82, in get_local_stateless_by_name
>     raise KeyError("Unable to find stateless DjangoApp called %s"%name)
> KeyError: 'Unable to find stateless DjangoApp called simpleexample'

I was wondering if someone could let me know what I am missing here?

**Comment by deniskristak** [comment]
@apiljic Hi, would you help out with providing your solution for the future? I know it's been a long time, but believe me or not, I came across the same problem running the initial example from `README`

**Comment by apiljic** [comment]
Hi. I don't remember any longer what the issue was (it was a while back). But since I haven't put any comments here, it means the problem was definitely on my end and the example from the docs should work. 
The only thing I notice missing is importing/registering the app in your main urls.py file. There should be something like 
`import django_plotly_dash.dash_apps`
if your django app is called django_plotly_dash and the file in it is dash_apps.py.
