### ISSUE TITLE
Passing arguments from views.py or a template to Dash

### ISSUE THREAD

**Issue by apiljic** [GibbsConsulting/django-plotly-dash#186]
Hello,

I was able to create a basic chart using a .csv file with this package.
Now, I'd like to use the real data and feed it into the dash app. The data is dynamically generated and which dataset is used depends on the ID.

I created my view in views.py and a template test_chart.html. This can be viewed at a url like this:
` /test_chart/<id>/`

The data is available at the following url:
`/test_chart/data/<id>/`

The dash app is in dash_apps.py. As long as I use the data from a static .csv file, I can get the chart. However, I was wondering how I could pass the ID argument from the views.py, template or url to dash_apps.py, so I can define the data endpoint using the ID and feed the real data into the dash app?

Does somebody have an idea?

Cheers!

**Comment by GibbsConsulting** [comment]
Pass something - eg the `id` - in as an initial variable to the `plotly_dash` template, or have your view code set up an instance of `django_plotly_dash.models.DashApp` with this information.

You will need to create something, such as a hidden `Div` element, in the layout to hold this information, which you can then access in a callback.

An alternative approach is to populate the session with the desired information, but this doesn't scale well, such as when the user opens multiple browser tabs to view multiple charts.

**Comment by apiljic** [comment]
Thanks!

> Pass something - eg the id - in as an initial variable to the plotly_dash template

How exactly would I do that? I am looking in the documentation, but I don't understand how to do it?

**Comment by apiljic** [comment]
Similar issue/solution as https://github.com/GibbsConsulting/django-plotly-dash/issues/173.
