### ISSUE TITLE
Manipulation of chart size

### ISSUE THREAD

**Issue by apiljic** [GibbsConsulting/django-plotly-dash#189]
Hello,

In the plotly_app template tag, I see I can set the ratio. This defines the padding-bottom property.

However, I'd like to have responsive charts that change slightly in width, depending on browser size. While dash supports that (I can fix the height and width will be auto), due to padding-bottom, I still have empty space below the chart.

Is there a way to manipulate this when resizing the browser?

Thanks!

**Comment by delsim** [comment]
The template tags use [these templates](https://github.com/GibbsConsulting/django-plotly-dash/tree/master/django_plotly_dash/templates/django_plotly_dash) - perhaps you could change or overload these.

Is the padding-bottom property you mention the one on the iframe element or the dash-generated content inside?

**Comment by apiljic** [comment]
Thanks @delsim. Good idea. I'll try playing with a custom template. The padding-bottom property is on the parent div of the iframe. It only becomes an issue with responsiveness.

**Comment by jasonyctam** [comment]
Hi @apiljic would you be able to share what you did to get around this? I have encountered a similar problem and would very much appreciate a quick solution to this rather than exploring alternatives on interactive maps, as plotly-dash really has a lot of amazing visuals to offer. Thanks in advance

**Comment by apiljic** [comment]
Hi @jasonyctam. In the end I switched from plotly_app to plotly_direct and then made it work from there. With plotly_direct, there were some minor issues (in my case), which I could solve by overriding the original properties. For example, I would add in my .html: 
```
<style>
.dash-table-container .dash-spreadsheet-container .dash-spreadsheet-inner td div.dash-cell-value.cell-markdown p {
    margin-bottom: 0px;
}
</style>
```
Which templatetag do you use? If possible, give plotly_direct a try.

**Comment by jasonyctam** [comment]
Hi @apiljic thanks for your tip. I initially couldn't get it working because there were some styling conflicts that I couldn't locate. but its working now thanks.
I am just building my first website which will include some dashboards, and it has been quite smooth with the help from
https://bootswatch.com/
however there has been quite a few bottlenecks along the way, but with your help they seem to be behind me now, thanks again.
