### ISSUE TITLE
Move some extended callback functionality to the base callback

### ISSUE THREAD

**Issue by delsim** [GibbsConsulting/django-plotly-dash#191]
Some of the functionality of the extended callback, such as saving on change, could be moved to the base callback function.

Anything that doesn't require extended arguments to be passed to the callback function can be handled in this way.

**Comment by GibbsConsulting** [comment]
There is not a lot to be gained by doing this. Using any enhanced feature switches all callbacks for that component to the extended variant.

A better approach is to make all callbacks compatible with the extended format by providing a `**kwargs` argument.
