### ISSUE TITLE
Give iframe parent div an id based on app name

### ISSUE THREAD

**Issue by eddy-ojb** [GibbsConsulting/django-plotly-dash#20]
I have noticed an issue with injecting a dpd iframe in to a page where the parent div is restricting the iframe:

<img width="960" alt="iframe_1" src="https://user-images.githubusercontent.com/26047714/43197480-3552a8f2-9003-11e8-980d-f440a5003fb3.PNG">

If amending the parent div height from 0 to X pixels, this resolves the issue:

<img width="506" alt="iframe_2" src="https://user-images.githubusercontent.com/26047714/43197527-5ae42140-9003-11e8-9760-e5f460b589f9.PNG">

<img width="960" alt="iframe_3" src="https://user-images.githubusercontent.com/26047714/43197542-622e1406-9003-11e8-8750-775267cd6ffe.png">

Perhaps each parent div should be given an id that is a function of the DjangoDash name property a standard? This way, we can apply our own css to size the iframe container.

For example, in plotly_items.html:

```
<div id={{app.name}}   style="{{dstyle}}">
  <iframe src="{{app.base_url}}" style="{{istyle}}"frameborder="{{fbs}}"></iframe>
</div>

```

**Comment by delsim** [comment]
Makes sense to me. Should the id be something like `{{app.name}}-{{counter}}` for some counter of the number of appearances of that app on the page (maybe only when the counter is bigger than 1), so that we can have multiple instances of the same app?

**Comment by eddy-ojb** [comment]
That sounds good to me, though what springs to mind is whether the same app instance counter will be assigned to an instance you care about if a co-developer comes in and adds code before or after, adding an instance of their own. 

This could upset the css and has the potential to be annoying working on a project as part of a team. If consistency can't be enforced then a possibility is to explicitly assign a counter e.g.: DjangoDash(instance_counter=1).

**Comment by GibbsConsulting** [comment]
Pull request #28 hopefully provides enough flexibility to address this.
