### ISSUE TITLE
AttributeError: 'DjangoDash' object has no attribute 'config'

### ISSUE THREAD

**Issue by apiljic** [GibbsConsulting/django-plotly-dash#200]
Hello,

I am trying to assign a callback to a component that is generated by other callbacks (and therefore not in the initial layout).

As explained in Dash documentation, I try to suppress the exception:
`app.config.suppress_callback_exceptions = True`

But then get:
AttributeError: 'DjangoDash' object has no attribute 'config'

Any ideas how to fix this?

Thanks!

**Comment by apiljic** [comment]
Found it here: https://github.com/GibbsConsulting/django-plotly-dash/issues/161.

**Comment by vinodagouda** [comment]
Hey @apiljic, Please add your piece of code which helped you to fix this error. I am stuck with this issue for couple of days now.

**Comment by vinodagouda** [comment]
#161 Didn't help me much, Details piece of code would be apricated.

**Comment by apiljic** [comment]
Hi. I am no longer using such a setup, but when I faced the issue of **AttributeError: 'DjangoDash' object has no attribute 'config'**, then the solution was to do something like described in the issue I cited:
```
dashapp = DjangoDash(name='my_dash_app',
serve_locally=False,
expanded_callbacks=True,
add_bootstrap_links=False,
suppress_callback_exceptions = True,
routes_pathname_prefix='/dashapp/'
)
```

Adding **suppress_callback_exceptions = True** should fix the error.
I hope this helped.

**Comment by vinodagouda** [comment]
@apiljic Thanks for your time for answering this. Will try to use this.
