### ISSUE TITLE
Performance questions

### ISSUE THREAD

**Issue by interrogator** [GibbsConsulting/django-plotly-dash#203]
Hey, great work with this, it might be a lifesaver for me.

I just wanted to know if you see much of a performance hit inside the dash app once it's inside django, just in terms of how fast responses are and so on.

And related to this: I have an ever-growing set of datasets. In terms of performance, would you imagine there would be an issue if each dataset was served up in a unique Dash app? Meaning, there could be hundreds of different dash apps. Can you foresee any issues if I were to go that way?

**Comment by GibbsConsulting** [comment]
We've not seen any performance issue from using Django. It is good practice to use a good wsgi or asgi server (we favour gunicorn) behind a reverse proxy like nginx and this will offload some of the workload.

Scaling issues are likely to arise from CPU usage rising with the number of concurrent running apps. Dash apps maintain their state on the client side so the number in existence doesn't really matter but the number in use at any point in time will.

**Comment by interrogator** [comment]
OK, thanks so much for the feedback. I'll close this, and reopen if anything performance related pops up during development.
