### ISSUE TITLE
app.config.suppress_callback_exceptions does not exist

### ISSUE THREAD

**Issue by nuthiev** [GibbsConsulting/django-plotly-dash#204]
This paragraph is taken from dash plotly:
```python
# Since we're adding callbacks to elements that don't exist in the app.layout,
# Dash will raise an exception to warn us that we might be
# doing something wrong.
# In this case, we're adding the elements through a callback, so we can ignore
# the exception.
app.config.suppress_callback_exceptions = True
```
I encountered an issue about suppress_callback_exceptions as described above.

**Comment by GibbsConsulting** [comment]
There's already been some work (#42 to address #36) regarding this. Are you in a position to share more details, such as how the error arises?

**Comment by nuthiev** [comment]
Ok. Thanks for the reply.

The error is the same as in #36 written as.

```
If you are assigning callbacks to components
that are generated by other callbacks
(and therefore not in the initial layout), then
you can suppress this exception by setting
`app.config['suppress_callback_exceptions']=True`.
```

**Comment by GibbsConsulting** [comment]
What happens when you pass `suppress_callback_exceptions=True` to the DjangoDash constructor?

**Comment by nuthiev** [comment]
Passing `suppress_callback_exceptions=True` to the DjangoDash constructor solved the error. Thanks.
