### ISSUE TITLE
Handle dash.exceptions.PreventUpdate

### ISSUE THREAD

**Issue by GibbsConsulting** [GibbsConsulting/django-plotly-dash#206]
As reported in #205, when a callback raises PreventUpdate the wrapper code does not handle it.

A change in [views.py](https://github.com/GibbsConsulting/django-plotly-dash/blob/master/django_plotly_dash/views.py) should allow these exceptions to be handled. The `update` function needs to catch this exception and return an empty response with a status code of 204; this is how the underlying [dash](https://github.com/plotly/dash/blob/2d735aa250fc67b14dc8f6a337d15a16b7cbd6f8/dash/dash.py#L381) code handles this response.

**Comment by interrogator** [comment]
Note that this is actually related to #205, not #204

**Comment by GibbsConsulting** [comment]
Well spotted. I was getting the issue number and the status code mixed up! Updated the summary.

**Comment by GibbsConsulting** [comment]
Merged into master and released in v1.1.2
