### ISSUE TITLE
Media files don't serve properly when in DEV mode

### ISSUE THREAD

**Issue by l0rb** [GibbsConsulting/django-plotly-dash#209]
This is nearly the same issue as https://github.com/GibbsConsulting/django-plotly-dash/issues/62 but about the `ExternalRedirectionMiddleware` this time. It has the same problem. The exception is thrown from https://github.com/GibbsConsulting/django-plotly-dash/blob/master/django_plotly_dash/middleware.py#L136

**Comment by GibbsConsulting** [comment]
Thanks for reporting. Is it the same exception, ie an `AttributeError`, that is raised?

**Comment by l0rb** [comment]
Yes, it is the same exception.

```AttributeError('This FileResponse instance has no `content` attribute. Use `streaming_content` instead.')```

**Comment by GibbsConsulting** [comment]
@l0rb this should now be fixed in the v1.1.3 release. Are you able to validate this?

**Comment by l0rb** [comment]
I can confirm that version v1.1.3 does not have this bug.
