### ISSUE TITLE
Upgrade dpd to work with latest Dash version

### ISSUE THREAD

**Issue by delsim** [GibbsConsulting/django-plotly-dash#21]
Reported by user tabre on the [plotly forum](https://community.plot.ly/t/django-and-dash-eads-method/7717/38) - a new attribute in Dash v0.22.0 `register_blueprint` is not provided by `PseudoFlask`.

In general, need to validate dpd against this version of Dash.

**Comment by T4rk1n** [comment]
I used `register_blueprint` to create a static handler for the assets system. I think just adding the method to `PseudoFlask` with pass is gonna work for this, but the assets won't work.

**Comment by GibbsConsulting** [comment]
v0.5.2 contains a first cut of a fix. It only provides a stub for the `register_blueprint` function so, as per @T4rk1n 's comment above, it doesn't attempt to use the supplied assets.

**Comment by GibbsConsulting** [comment]
#97 should go a long way towards handling extra assets

**Comment by GibbsConsulting** [comment]
Closing this issue as `django-plotly-dash` is working with current released versions, including the 1.0 1.5 and 1.6 series. Not all of the underlying dash functionality is available, but this is not a project goal and is probably neither possible or desirable.

If any compatibility issues arise, please open new issues.
