### ISSUE TITLE
dash.callback_context.triggered is only available from a callback!

### ISSUE THREAD

**Issue by interrogator** [GibbsConsulting/django-plotly-dash#212]
Inside my callback I tried to access `dash.callback_context.triggered`, but got:

```
dash.exceptions.MissingCallbackContextException: dash.callback_context.triggered is only available from a callback!
```

I am assuming that this could be caused by your wrapper somehow? i.e. somehow dash can no longer recognise that this is a callback function?

Using this `callback_context` is now the best way to determine which `Input` triggered the callback. It seems like a very useful feature, so ideally django-plotly-dash can preserve it.

Full traceback:

```
Traceback (most recent call last):
  File "/home/danny/venv/benv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/danny/venv/benv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/danny/venv/benv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/danny/venv/benv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/danny/venv/benv/lib/python3.7/site-packages/django_plotly_dash/views.py", line 74, in update
    return _update(request, ident, stateless, **kwargs)
  File "/home/danny/venv/benv/lib/python3.7/site-packages/django_plotly_dash/views.py", line 101, in _update
    resp = app.dispatch_with_args(request_body, arg_map)
  File "/home/danny/venv/benv/lib/python3.7/site-packages/django_plotly_dash/dash_wrapper.py", line 562, in dispatch_with_args
    res = self.callback_map[target_id]['callback'](*args, **argMap)
  File "/home/danny/venv/benv/lib/python3.7/site-packages/dash/dash.py", line 1337, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "/home/danny/work/buzzword/explorer/parts/callbacks.py", line 176, in _new_search
    trigger = dash.callback_context.triggered[0]
  File "/home/danny/venv/benv/lib/python3.7/site-packages/dash/_callback_context.py", line 15, in assert_context
    ).format(getattr(func, '__name__'))
dash.exceptions.MissingCallbackContextException: dash.callback_context.triggered is only available from a callback!
```

**Comment by GibbsConsulting** [comment]
The issue is that dash puts some request information into a global `callback_context` variable. It is possible to both add this to the wrapper (so current code works) and/or add it as an extra callback argument (which is cleaner, but not compatible with pure dash callbacks).

Created #213 for this - there is a need to consider other work, such as asynchronous callbacks, which would not be compatible with a global variable approach.

**Comment by Dylan-Cunningham** [comment]
Would love to see this soon! My current workaround is to store a timestamp of each triggered button click. Then my callback displays the view of whichever was clicked most recently based on the stored timestamp. However, I believe this workaround is slowing my app significantly. Also, to get this functionality, I've had to add a callback for each button, and I had to add a hidden storage for each.

Anyone have a better workaround?

**Comment by GibbsConsulting** [comment]
PR #254 should address this.

**Comment by sorenwacker** [comment]
I still get this error with Django 3.2.13 and Dash 2.5.1 and django-plotly-dash 2.0.0.

**Comment by delsim** [comment]
@sorenwacker not sure if you are seeing exactly the same issue, in that the previous problem was that there was a need to set a global variable. Can you provide a small example - ideally in a new issue so that it can be tracked.

**Comment by sorenwacker** [comment]
I got it. When using django-plotly-dash the usual context function cannot be used, but it is passed as a kwarg argument.
________________________________

**Comment by PawanHarsha** [comment]
i understand about passing it as a kwargs argument, but i am unable to get my head around it, can you help me with an example?

**Comment by Enriquez97** [comment]
@sorenwacker I have the same problem using django-plotly-dash, can you give me an example? the documentation is not understandable to me.

**Comment by sorenwacker** [comment]
If I reconstruct this correctly, you have to write your callbbacks with `**kwargs`:

```
@a2.callback(
    dash..Output('output-one','children'),
    [dash.dependencies.Input('dropdown-one','value')]
    )
def callback_c(*args,**kwargs):
    da = kwargs['dash_app']
    
   ctx = kwargs['callback_context']  # try this

    return "Args are [%s] and kwargs are %s" %(",".join(args), kwargs)
    
```

then the content should be availabe as


    
![image](https://github.com/GibbsConsulting/django-plotly-dash/assets/3391614/9dc02093-ade6-45e2-954c-f4d78566dac4)
