### ISSUE TITLE
add full request object to arg_map

### ISSUE THREAD

**Issue by jadeiX** [GibbsConsulting/django-plotly-dash#216]
Hello, 
I was wondering if it is possible to change the `_update` function in `views.py` such that it sends the full request object to the callback function. like so:
```
arg_map = {'dash_app_id': ident,
                   'dash_app': dash_app,
                   'user': request.user,
                   'request': request,
                   'session_state': app_state}
```
instead of the current code which only sends the user object

from testing I have done, it seems to be working well. 
The reason I would like to have the request object is that it allows a callback to access the request meta and other information. 
created pull request

**Comment by GibbsConsulting** [comment]
Thanks for the PR - #217 is now merged into master. This will be in the next package release, which should be in the next day or so.

**Comment by jadeiX** [comment]
I tried to add the ‘request’ to the table in the documentation [extended callback](https://github.com/GibbsConsulting/django-plotly-dash/blob/master/docs/extended_callbacks.rst) but it ends up breaking the table. Please help add this to the docs

**Comment by GibbsConsulting** [comment]
@jadeiX just spotted your comment about the documentation - have now added a brief note as part of PR #254
