### ISSUE TITLE
getting the clickCallback in tableOptions for dash_pivottable

### ISSUE THREAD

**Issue by aboulang** [GibbsConsulting/django-plotly-dash#223]
I am lost on just how to set this up. Is it the same way as the example callbacks?

**Comment by GibbsConsulting** [comment]
Callbacks work essentially the same as in the underlying dash library, with the option of adding in extended arguments if desired. So anything that works with dash should work with django-plotly-dash.

Is there something specific about what you're doing that makes you think it is non-standard?

**Comment by aboulang** [comment]
I think I should have submitted the issue with plotly dash?  

From https://github.com/plotly/react-pivottable/issues/40, at the javascript level, the call looks something like:
<PivotTable data={ props.data } tableOptions={ { clickCallback: (e, value, filters, pivotData) => { alert('hello world') }) } } />

The question is how can/is this exposed by dash or django-plotly-dash?

Let me know if you need more info.

Albert

**Comment by GibbsConsulting** [comment]
This is an issue with the underlying plotly/react-pivottable component itself - it needs to pass on events that it wishes to make available through dash.

Once that is done, anything that is added for use with a dash callback should be available to django-plotly-dash; if at this point something strange is happening then either reopen this issue or create a new one.
