### ISSUE TITLE
Using my CSS files

### ISSUE THREAD

**Issue by mybox2003** [GibbsConsulting/django-plotly-dash#228]
I want to change the font style and size on the charts, for this I added the 'assets' folder containing CCS to the folder with the django_plotly_dash application. I read the documentation section of 'Local assets', when I set 'serve_locally' to True, I see the inscription 'Loading'. Please write in more detail how I can solve my problem.

**Comment by GibbsConsulting** [comment]
Is this something that breaks when you add assets, or when you set `serve_locally=True`, or something else? It would help if you could identify what step(s) caused your application to stop working, or otherwise provide a way of replicating the issue.
