### ISSUE TITLE
rending dash-bootstrap-components in Django plotly dash not working

### ISSUE THREAD

**Issue by coe-team** [GibbsConsulting/django-plotly-dash#229]
Hi,
the below code will work fine in my desktop IDE.

import dash
import dash_bootstrap_components as dbc
import dash_html_components as html

app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = dbc.Navbar(
dbc.Container(
[
dbc.NavbarBrand(
[
html.Span("A", style={"color": "red"}),
html.Span("B", style={"color": "green"}),
html.Span("C", style={"color": "blue"}),
]
),
dbc.Nav(
[
dbc.NavItem(dbc.NavLink("Item 1", href="#")),
dbc.NavItem(dbc.NavLink("Item 2", href="#")),
],
navbar=True,
),
]
)
)

if name == "main":
app.run_server(debug=True)

However,

once I do
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output, State
from django_plotly_dash import DjangoDash
import dash_bootstrap_components as dbc

app = DjangoDash('test', [dbc.themes.BOOTSTRAP])

and then a dbc. whatever widget in the app I get

Django version 3.0.4, using settings ‘UPS.settings’
Starting ASGI/Channels version 2.4.0 development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
HTTP GET /test/ 200 [0.13, 127.0.0.1:60098]
HTTP GET /django_plotly_dash/app/test/ 200 [0.03, 127.0.0.1:60098]
HTTP GET /django_plotly_dash/app/test/_dash-component-suites/dash_bootstrap_components/_components/dash_bootstrap_components.v0_9_0m1585057943.min.js 302 [0.01, 127.0.0.1:60098]
Not Found: /static/dash/component/dash_bootstrap_components/_components/dash_bootstrap_components.min.js
HTTP GET /static/dash/component/dash_bootstrap_components/_components/dash_bootstrap_components.min.js 404 [0.02, 127.0.0.1:60098]
HTTP GET /django_plotly_dash/app/test/_dash-layout 200 [0.05, 127.0.0.1:60098]
HTTP GET /django_plotly_dash/app/test/_dash-dependencies 200 [0.07, 127.0.0.1:60099]

It seems Django skips the files pip install dash-bootstrap-components installs? Maybe I am wrong.

I embedded a djangdash app as a tag in Django. Without bootstrapping I can do everything. With it, I the page is stuck on load. Are there any knowns issues or docs I can check?

**Comment by GibbsConsulting** [comment]
You need to use
```
add_bootstrap_links=True
```

in your `DjangoDash` constructor. #230 exists as the documentation is not that clear on this point.

**Comment by coe-team** [comment]
Hi, I appreciate your comment. However, I am still receiving a lot of 404 errors. Maybe I did something obviously wrong? I ran into all the errors below with the new change. Page still isn't loading




HTTP GET /static/channels/js/websocketbridge.js 404 [0.02, 127.0.0.1:49999]
HTTP GET /static/channels/js/websocketbridge.js 404 [0.05, 127.0.0.1:49999]
HTTP GET /django_plotly_dash/app/test/ 200 [0.06, 127.0.0.1:50022]
HTTP GET /django_plotly_dash/app/test/_dash-component-suites/dash_renderer/polyfill@7.v1_2_2m1584363799.7.0.min.js 302 [0.02, 127.0.0.1:49999]
HTTP GET /django_plotly_dash/app/test/_dash-component-suites/dash_renderer/react@16.v1_2_2m1584363799.8.6.min.js 302 [0.04, 127.0.0.1:50006]
HTTP GET /django_plotly_dash/app/test/_dash-component-suites/dpd_static_support/bootstrap.v0_1m1585059079.min.css 302 [0.07, 127.0.0.1:50022]
HTTP GET /django_plotly_dash/app/test/_dash-component-suites/dash_renderer/react-dom@16.v1_2_2m1584363799.8.6.min.js 302 [0.07, 127.0.0.1:50000]
HTTP GET /django_plotly_dash/app/test/_dash-component-suites/dash_html_components/dash_html_components.v1_0_2m1584363809.min.js 302 [0.01, 127.0.0.1:50000]
HTTP GET /django_plotly_dash/app/test/_dash-component-suites/dash_core_components/dash_core_components.v1_8_1m1584363801.min.js 302 [0.03, 127.0.0.1:50022]
HTTP GET /django_plotly_dash/app/test/_dash-component-suites/dash_core_components/dash_core_components-shared.v1_8_1m1584363801.js 302 [0.04, 127.0.0.1:50006]
HTTP GET /django_plotly_dash/app/test/_dash-component-suites/dash_renderer/prop-types@15.v1_2_2m1584363799.7.2.min.js 302 [0.04, 127.0.0.1:49999]
HTTP GET /django_plotly_dash/app/test/_dash-component-suites/dash_table/bundle.v4_6_1m1584363843.js 302 [0.02, 127.0.0.1:50022]
HTTP GET /django_plotly_dash/app/test/_dash-component-suites/dpd_components/bundle.v0_1_0m1584365267.js 302 [0.03, 127.0.0.1:50000]
HTTP GET /django_plotly_dash/app/test/_dash-component-suites/dash_bootstrap_components/_components/dash_bootstrap_components.v0_9_0m1585057943.min.js 302 [0.04, 127.0.0.1:49999]
HTTP GET /django_plotly_dash/app/test/_dash-component-suites/dash_renderer/dash_renderer.v1_2_2m1584363799.min.js 302 [0.04, 127.0.0.1:50022]
HTTP GET /static/dash/component/dpd_static_support/bootstrap.min.css 404 [0.08, 127.0.0.1:50006]
HTTP GET /static/dash/component/dash_renderer/polyfill@7.7.0.min.js 404 [0.07, 127.0.0.1:50000]
HTTP GET /static/dash/component/dash_renderer/react@16.8.6.min.js 404 [0.03, 127.0.0.1:50034]
HTTP GET /static/dash/component/dash_renderer/react-dom@16.8.6.min.js 404 [0.02, 127.0.0.1:50034]
HTTP GET /static/dash/component/dash_renderer/prop-types@15.7.2.min.js 404 [0.04, 127.0.0.1:50000]
HTTP GET /static/dash/component/dash_html_components/dash_html_components.min.js 404 [0.05, 127.0.0.1:50034]
HTTP GET /static/dash/component/dpd_components/bundle.js 404 [0.06, 127.0.0.1:50006]
HTTP GET /static/dash/component/dash_core_components/dash_core_components.min.js 404 [0.07, 127.0.0.1:50022]
HTTP GET /static/dash/component/dash_core_components/dash_core_components-shared.js 404 [0.07, 127.0.0.1:49999]
HTTP GET /static/dash/component/dash_table/bundle.js 404 [0.07, 127.0.0.1:50035]
HTTP GET /static/dash/component/dash_renderer/dash_renderer.min.js 404 [0.04, 127.0.0.1:50034]
HTTP GET /static/dash/component/dash_bootstrap_components/_components/dash_bootstrap_components.min.js 404 [0.06, 127.0.0.1:50000]
HTTP GET /django_plotly_dash/app/test/_dash-component-suites/dash_core_components/dash_core_components-shared.v1_8_1m1584363801.js 302 [0.01, 127.0.0.1:50022]
HTTP GET /static/dash/component/dash_core_components/dash_core_components-shared.js 404 [0.02, 127.0.0.1:50022]
HTTP GET /django_plotly_dash/app/test/_dash-component-suites/dash_html_components/dash_html_components.v1_0_2m1584363809.min.js 302 [0.01, 127.0.0.1:50022]
HTTP GET /static/dash/component/dash_html_components/dash_html_components.min.js 404 [0.01, 127.0.0.1:50022]
HTTP GET /django_plotly_dash/app/test/_dash-component-suites/dpd_components/bundle.v0_1_0m1584365267.js 302 [0.01, 127.0.0.1:50022]
HTTP GET /static/dash/component/dpd_components/bundle.js 404 [0.02, 127.0.0.1:50022]
HTTP GET /django_plotly_dash/app/test/_dash-component-suites/dash_table/bundle.v4_6_1m1584363843.js 302 [0.01, 127.0.0.1:50022]
HTTP GET /static/dash/component/dash_table/bundle.js 404 [0.01, 127.0.0.1:50022]
HTTP GET /django_plotly_dash/app/test/_dash-component-suites/dash_bootstrap_components/_components/dash_bootstrap_components.v0_9_0m1585057943.min.js 302 [0.01, 127.0.0.1:50022]
HTTP GET /static/dash/component/dash_bootstrap_components/_components/dash_bootstrap_components.min.js 404 [0.01, 127.0.0.1:50022]
HTTP GET /django_plotly_dash/app/test/_dash-component-suites/dash_renderer/dash_renderer.v1_2_2m1584363799.min.js 302 [0.01, 127.0.0.1:50022]
HTTP GET /static/dash/component/dash_renderer/dash_renderer.min.js 404 [0.02, 127.0.0.1

**Comment by coe-team** [comment]
Actually, that was serving it locally. If I just add add_bootstrap_links=True

then I only receive
HTTP GET /test/ 200 [0.08, 127.0.0.1:50127]
HTTP GET /static/channels/js/websocketbridge.js 404 [0.02, 127.0.0.1:50127]
HTTP GET /static/channels/js/websocketbridge.js 404 [0.03, 127.0.0.1:50127]
HTTP GET /django_plotly_dash/app/test/ 200 [0.04, 127.0.0.1:50128]
HTTP GET /django_plotly_dash/app/test/_dash-component-suites/dash_bootstrap_components/_components/dash_bootstrap_components.v0_9_0m1585057943.min.js 302 [0.01, 127.0.0.1:50128]
HTTP GET /static/dash/component/dash_bootstrap_components/_components/dash_bootstrap_components.min.js 404 [0.01, 127.0.0.1:50128]
HTTP GET /django_plotly_dash/app/test/_dash-layout 200 [0.07, 127.0.0.1:50128]
HTTP GET /django_plotly_dash/app/test/_dash-dependencies 200 [0.08, 127.0.0.1:50127]

**Comment by aurashn** [comment]
@coe-team @GibbsConsulting I am seeing the same issue with adding add_bootstrap_links=True.
I have followed the configuration steps in the documentation as far as adding django-bootstrap- components in PLOTLY_COMPONENTS.

Is it possible to use DBC components without serve_locally?

**Comment by GibbsConsulting** [comment]
@aurashn serve_locally should not be needed.
Tagging also @coe-team 
As per the comments in #230, could one or both of you do the following:
(a) run a collectstatic step eg
```
./manage.py collectstatic
```
and report if this generates any errors
(b) then go to wherever you have set `STATIC_ROOT` and see if it contains the file `dash/component/dash_bootstrap_components/_components/dash_bootstrap_components.min.js`

**Comment by aurashn** [comment]
@GibbsConsulting I can confirm that without serve locally it does work if your static files are correctly being served. I was able to discover that I had issues with updating during deployment. 

It seems that for local development, it is also necessary to collectstatic and run "runserver" with the ---nostatic option or else you will run into 404's for the missing files and see:

"Error: dash_bootstrap_components/_components was not found"

I was not use to this flow in local development for Django Plotly Dash which was likely the source of initial confusion.

**Comment by coe-team** [comment]
Hi,

both of you are far far more knowledgeable than me. When I type runserver" with the ---nostatic I am THEN able to see the button. I included what I get when I run it.
If I use this app in production what do I have to do now to factor in this nonstatic issue? Yes, I did run collectstatic prior.

Thank you all!
Anthony


Not Found: /static/channels/js/websocketbridge.js # this has something to do with the latest version purposely missing this file I believe
HTTP GET /static/channels/js/websocketbridge.js 404 [0.04, 127.0.0.1:50605]  # this has something to do with the latest version purposely missing this file I believe
Not Found: /static/channels/js/websocketbridge.js  # this has something to do with the latest version purposely missing this file I believe
HTTP GET /static/channels/js/websocketbridge.js 404 [0.07, 127.0.0.1:50605]  # this has something to do with the latest version purposely missing this file I believe
HTTP GET /django_plotly_dash/app/test/ 200 [0.09, 127.0.0.1:50606]
HTTP GET /django_plotly_dash/app/test/_dash-component-suites/dash_bootstrap_components/_components/dash_bootstrap_components.v0_9_0m1585135585.min.js 302 [0.01, 127.0.0.1:50606]
HTTP GET /static/dash/component/dash_bootstrap_components/_components/dash_bootstrap_components.min.js 304 [0.01, 127.0.0.1:50606]
HTTP GET /django_plotly_dash/app/test/_dash-dependencies 200 [0.18, 127.0.0.1:50605]
HTTP GET /django_plotly_dash/app/test/_dash-layout 200 [6.39, 127.0.0.1:50606]
HTTP POST /django_plotly_dash/app/test/_dash-update-component 200 [0.16, 127.0.0.1:50606]
HTTP POST /django_plotly_dash/app/test/_dash-update-component 200 [0.15, 127.0.0.1:50605]
HTTP POST /django_plotly_dash/app/test/_dash-update-component 200 [0.20, 127.0.0.1:50607]
HTTP POST /django_plotly_dash/app/test/_dash-update-component 200 [0.10, 127.0.0.1:50607]
HTTP POST /django_plotly_dash/app/test/_dash-update-component 200 [0.30, 127.0.0.1:50606]
HTTP POST /django_plotly_dash/app/test/_dash-update-component 200 [0.09, 127.0.0.1:50610]
________________________________

**Comment by aurashn** [comment]
@coe-team it depends on how you are serving your application in production. Along with that, how are your static files being served in production?

**Comment by GibbsConsulting** [comment]
Serving static files is something to address for Django as a whole.

For reference:
- Django documentation on serving [static files](https://docs.djangoproject.com/en/3.0/howto/static-files/)
- Whitenoise [documentation](http://whitenoise.evans.io/en/stable/)

**Comment by GibbsConsulting** [comment]
Documentation updated in #255 and released as version 1.4.1
