### ISSUE TITLE
Demo 4 not Rendering

### ISSUE THREAD

**Issue by 8ball030** [GibbsConsulting/django-plotly-dash#232]
Hi, 
I am having an issue with the demo, 
I am able to get the server running, however when I try demo 4, I am not seeing rendered charts.

Opening the dev tools console shows me that the request;

curl 'http://127.0.0.1:8000/static/channels/js/websocketbridge.js' -H 'Connection: keep-alive' -H 'Sec-Fetch-Dest: script' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36' -H 'DNT: 1' -H 'Accept: */*' -H 'Sec-Fetch-Site: same-origin' -H 'Sec-Fetch-Mode: no-cors' -H 'Referer: http://127.0.0.1:8000/demo-four' -H 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8' -H 'Cookie: sessionid=l1p2qyrh5m9zgr74ju4i08nctsnkza57' --compressed

Is failing

I can confirm that this file is not present on the server, so i think that it should be a dependency install from some where?
Any help would be hugely appreciated :)
Kindest regards,
Tom

**Comment by GibbsConsulting** [comment]
Assuming that you didn't get any errors when installing and running the setup scripts, this is probably due to the version of the channels package. This is described in issue #148 

Are you using Django 3.0 or later? If so then changing to 2.2 should fix the problem.

**Comment by 8ball030** [comment]
Thanks for the advice on this one, I was able to follow the advice from the referenced comment, Additionally, I have containerised the demo application and frozen the requirements.
I would imagine you will be doing some more work before switching to django3 so I havent bothered to push my docker-compose across, but i think that this will act as a stop gap.
