### ISSUE TITLE
Heroku loading time

### ISSUE THREAD

**Issue by nuthiev** [GibbsConsulting/django-plotly-dash#247]
How to make the loading time faster in heroku? My app loads relatively faster locally. But it loads about 10 - 15s in heroku than about 1 to 3s locally. I am currently running on Hobby with 

> web: gunicorn appname.wsgi

 in Procfile.

Has anyone experienced putting web and worker in Procfile?
Do you get a significant loading time for 1 additional worker?

**Comment by GibbsConsulting** [comment]
Is this a more general Heroku question, or specific to `django-plotly-dash`?

It would not be a surprise to learn that a Hobby instance is resource constrained. Does the problem persist when you run on a more powerful Dyno?

**Comment by nuthiev** [comment]
It's for both.
For heroku side question, I would like to know the loading time difference if anyone has an experience on running powerful dyno or with at least 1 worker.
For django-plotly-dash side, I would like to know how to implement the worker configuration in heroku to perform dash app calculation in the background.

I am not running in powerful dyno because I am not sure if this will improve the background process of dash app.

I need a feedback on this from those who had experienced.

**Comment by GibbsConsulting** [comment]
No experience of using Heroku so others will have to comment on the loading time difference. From the documentation it appears that each load of the app includes a `collectstatic` call, which might be relevant.

For Heroku configuration, a quick google yields [this](https://elements.heroku.com/buttons/heroku/channels-example) which contains a configuration for running `channels` - this may be a good starting point if not the complete solution. The linked blog post describes the app and its configuration in detail.

**Comment by nuthiev** [comment]
Thanks for the reply and the link.
While waiting for others' reply who have similar experience, I'll investigate more about this loading time difference issue.
I'll get back if I have a better solution.

**Comment by nuthiev** [comment]
I solved the slow loading time by optimizing the code.
I reduced the actual page loading time of django-dash app (with expensive calculation) into ~1s.
