### ISSUE TITLE
Demo 4

### ISSUE THREAD

**Issue by rmaranhao** [GibbsConsulting/django-plotly-dash#248]
Hello and congratulations on this package.

I have an issue and I'm looking for help.
All my demos work, except demo4.
AFAIK I have no errors on the server side. Whenever a button is clicked, I only get one page on my terminal:
HTTP POST /django_plotly_dash/app/LiveInput/_dash-update-component 200 [0.75, 127.0.0.1:59018]

I can see that the online demo loads makes four requests when a button is clicked, but I could not fix it.

Thanks in advance, 
Roberto.

**Comment by GibbsConsulting** [comment]
Is redis running locally? See the `prepare_redis` script in the root of the git repository.

**Comment by rmaranhao** [comment]
Thanks for the response. That was it!
