### ISSUE TITLE
Static file location not updated correctly to file server url

### ISSUE THREAD

**Issue by DavWinkel** [GibbsConsulting/django-plotly-dash#251]
I am having a problem with the **location of the static .js file** of dash_bootstrap_components.
Important to note is that I also use 
`STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'`

**Without** using the storages.backends.s3 the dash_bootstrap_components.js is served correctly (from localhost) and my application **is working correctly**.

Since I am moving now to production using NGINX I wish to use the external fileserver of s3. Looking up the HTML code I noticed that all the **other static files** in my django templates (which had before the location "localhost:8000/static/....") are now **turned into urls** that directly link to the s3 fileserver and served correctly.
Only with dash_bootstrap_components.js the linking is still to "localhost:8000/static..." and I get the following error:
`GET http://localhost:8000/static/dash/component/dash_bootstrap_components/_components/dash_bootstrap_components.min.js net::ERR_ABORTED 404 (Not Found)` 
(The dash_bootstrap_components.min.js file is still at the localhost location, but NGINX is not allowed to access this location any more since I want it to be served from a file server)

I **would like to have dash to refer to the file at a file server location** such as 
`https://your-bucket.s3.eu-central-1.amazonaws.com/dash/component/dash_bootstrap_components/_components/dash_bootstrap_components.min.js`

A snippet from my settings.py is:

```

INSTALLED_APPS = [
    ....
    'django_plotly_dash.apps.DjangoPlotlyDashConfig',
    'storages',
    'bootstrap4',
    ...
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django_plotly_dash.middleware.BaseMiddleware',
    'django_plotly_dash.middleware.ExternalRedirectionMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

STATICFILES_LOCATION = 'static'
STATIC_URL = '/static/'
STATIC_ROOT = 'static'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'django_frontend/static')
]

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',

    'django_plotly_dash.finders.DashAssetFinder',
    'django_plotly_dash.finders.DashComponentFinder',
    'django_plotly_dash.finders.DashAppDirectoryFinder'
]

PLOTLY_COMPONENTS = [
    'dash_core_components',
    'dash_html_components',
    'dash_bootstrap_components',
    'dash_renderer',
    'dpd_components'
]

```

Thanks for your time and any suggestions?

**Comment by GibbsConsulting** [comment]
The bootstrap links are a special case - the `dpd_static_support` package covers this. Do you have that installed? Its not in your snippet above.

[Documentation here](https://django-plotly-dash.readthedocs.io/en/latest/local_assets.html#additional-components) - it is not the clearest at the moment unfortunately - and it covers all, not just local, serving of the assets.

**Comment by DavWinkel** [comment]
Unfortunately the `dpd_static_support` package did not resolve my problem.
An updated snippet from my header looks now like:

```
INSTALLED_APPS = [
    ....
    'django_plotly_dash.apps.DjangoPlotlyDashConfig',
    'storages',
    'bootstrap4',
    'dpd_static_support',
    ...
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django_plotly_dash.middleware.BaseMiddleware',
    'django_plotly_dash.middleware.ExternalRedirectionMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

STATICFILES_LOCATION = 'static'
STATIC_URL = '/static/'
STATIC_ROOT = 'static'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'django_frontend/static')
]

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',

    'django_plotly_dash.finders.DashAssetFinder',
    'django_plotly_dash.finders.DashComponentFinder',
    'django_plotly_dash.finders.DashAppDirectoryFinder'
]

PLOTLY_COMPONENTS = [
    'dash_core_components',
    'dash_html_components',
    'dash_bootstrap_components',
    'dash_renderer',
    'dpd_components',
    'dpd_static_support'
]

```

A look at the footer of the created HTML file of my application shows:
```

        <footer>
            <script id="_dash-config" type="application/json">{"url_base_pathname": "/django_plotly_dash/app/Dashboard/", "requests_pathname_prefix": "/django_plotly_dash/app/Dashboard/", "ui": false, "props_check": false, "show_undo_redo": false}</script>
            <script src="https://unpkg.com/@babel/polyfill@7.8.7/dist/polyfill.min.js"></script>
            <script src="https://unpkg.com/react@16.13.0/umd/react.production.min.js"></script>
            <script src="https://unpkg.com/react-dom@16.13.0/umd/react-dom.production.min.js"></script>
            <script src="https://unpkg.com/prop-types@15.7.2/prop-types.min.js"></script>
            <script src="https://unpkg.com/dash-core-components@1.9.0/dash_core_components/dash_core_components.min.js"></script>
            <script src="https://unpkg.com/dash-core-components@1.9.0/dash_core_components/dash_core_components-shared.js"></script>
            <script src="https://unpkg.com/dash-html-components@1.0.3/dash_html_components/dash_html_components.min.js"></script>
            <script src="/django_plotly_dash/app/Dashboard/_dash-component-suites/dash_bootstrap_components/_components/dash_bootstrap_components.v0_9_2m1590763687.min.js"></script>
            <script src="https://unpkg.com/dash-renderer@1.3.0/dash_renderer/dash_renderer.min.js"></script>
            <script id="_dash-renderer" type="application/javascript">var renderer = new DashRenderer();</script>
        </footer>
``` 
All files except the dash_bootstrap_components file are served from a CDN. To my knowledge dash_bootstrap components is not on a CDN yet ([source](https://github.com/facultyai/dash-bootstrap-components/issues/263)). Unfortunately also with the `dpd_static_support` package django still tries to read the dash_bootstrap_components.min.js from localhost and I still get the same error.

The documentation for the `dpd-static-support` package says:
`This can be avoided by use of the dpd-static-support package, which supplies mappings to locally served versions of these assets.`
My initial understanding was that this package actually makes django avoid using external sources and always using locally served assets (from localhost)?

**Comment by GibbsConsulting** [comment]
I think that 'serve locally' should really be thought of as 'serve like any other django static file' and in turn this would (ideally) work with the various storage backends. However, this may not be the case at the moment.
Are you setting `serve_locally` to `True` at the moment?

**Comment by DavWinkel** [comment]
Thank you for the suggestion. Indeed my `serve_locally` was set to its default value `False`.
When setting `serve_locally` to `True` the effect was that all the files (also those which were prior served by a CDN) are now served from localhost. It seems that `django-storages` is not changing the links correctly and they remain to refer to the localhost (all the other static links in my django templates are changed correctly and refer to a S3 source).

As you already noted it looks like the support of backend storage is not fully functional yet.

I found a non-django workaround that might be relevant for people using `NGINX`. Add the following to your `NGINX` .conf file:

```
location = /static/dash/component/dash_bootstrap_components/_components/dash_bootstrap_components.min.js {
	proxy_pass https://name-of-your-bucket.s3.eu-central-1.amazonaws.com/path/to/your/file/dash_bootstrap_components.min.js;
    }

```
This will proxy pass directly to my S3 bucket always when the server is hit with a `GET /static/dash/component/dash_bootstrap_components/_components/dash_bootstrap_components.min.js`

To make this work you have to set the file `dash_bootstrap_components.min.js` in your S3 bucket to **public-read**.

**Comment by GibbsConsulting** [comment]
@DavWinkel don't you already have a `location` element in your nginx configuration anyway? In general we insert one such directive for all static files as there is no need to go through Django for them.

**Comment by DavWinkel** [comment]
@GibbsConsulting I was unaware that it is best practice to include all the static files in the nginx configuration already. Thanks a lot for the hint.
The only downside I see with this pure nginx approach is that I have to set all my static files in the S3 bucket to `public readable`. In contrast by using the links provided by `django-storages` there is a token included in each link which ensures that only authorized users are able to access the static files in my S3 bucket. This way I do not have to set the entire static files bucket to `public readable`.

**Comment by GibbsConsulting** [comment]
So to be clear, in our (fairly standard, I think) setup:
- nginx is a reverse proxy for Django
- it is configured to statically serve (and not delegate to Django) all of the static files; we do this with a single `location` directive to nginx, covering everything under `/static`
- Django templates, django-plotly-dash, etc generate URLs that all go through nginx

For some reason, based on my understanding of what you've said, you're trying to do something different, namely have the Django etc generated URLs talk directly to S3; this would require the S3 bucket to be readable by anyone who should be able to successfully visit your site.

However, this doesn't seem to work for some of the dpd files, so you're looking at having nginx reverse proxy the S3 files (which would require the nginx process, and not the world, have read access to your S3 bucket). This is going to double your bandwidth requirements (every file served by nginx will also have to be fetched from S3) and its not clear why you would want to do this - surely just having nginx serve the files from its local storage would be faster and halve the bandwidth requirement.

One other possibility would be for nginx to send redirects to the files stored on S3, rather than proxy serve them. I don't know your motivation for serving from S3 so I can't comment further, but it sounds like it should be a reasonably common general use case for nginx. This does also require world read access to the S3 bucket.

Incidentally, presumably your S3 access concerns, if they persist in whatever configuration you end up with, could be resolved by splitting your bucket into two buckets - one globally readable for this content, and the other containing the rest.

**Comment by DavWinkel** [comment]
@GibbsConsulting Your understanding of my problem is totally correct. All the routes to the static dpd files **except** the ones from `dash_bootstrap_components` are assigned an authentication token (for some reason the `dash_bootstrap_components` static files seem not to be identified as static files by `django-storages`). Routes to static files with an assigned authentication token can be accessed by django in the S3 bucket (although the bucket is set to private).

You made a compelling argument by stating that I can halve my bandwidth requirements using the standard setup. I will follow your advice and set up two S3 buckets, `a private bucket` for the sensitive static files in my application and `a globally readable bucket` for the non-sensitive static files such as for the ones from dpd.
Thanks a lot for your great help I learnt a lot about Django best practices!

**Comment by GibbsConsulting** [comment]
@DavWinkel this issue appears to be resolved, so closing. If not, then either reopen or create a new issue as appropriate.
