### ISSUE TITLE
I am getting the following issue when I run your code

### ISSUE THREAD

**Issue by swarnas89** [GibbsConsulting/django-plotly-dash#258]
AttributeError: module 'time' has no attribute 'clock'
I could'nt trace out the file that needs to be changed

**Comment by GibbsConsulting** [comment]
@swarnas89 are you able to add any information about your issue? For example, the actual error message, the steps you took that led to the error, and a brief description of your environment are all pretty essential components of any report.

As outlined in the [documentation](https://django-plotly-dash.readthedocs.io/en/latest/development.html#bug-reports-and-other-issues) having a clear path to replicating an issue is very helpful.
