### ISSUE TITLE
can't change height of dashTable, can't appene_css

### ISSUE THREAD

**Issue by brainsid** [GibbsConsulting/django-plotly-dash#259]
DashTable has a height of 1400px. Adding style_table: {'height': 100} do nothing. 

a2.css.append_css({'relative_package_path': 'static/css/main.css'}) results in an error:
```
File "/home/comp036/Python/anchorWizDjango/venv/lib/python3.7/site-packages/dash/dash.py", line 571, in _collect_and_register_resources
    self.registered_paths[resource["namespace"]].add(rel_path)
KeyError: 'namespace' 
```

**Comment by GibbsConsulting** [comment]
@brainsid It is not clear if this is a `django-plotly-dash` issue or something else. You'll need to give something more concrete for any further comment; for example there are some comments [here](https://django-plotly-dash.readthedocs.io/en/latest/development.html#bug-reports-and-other-issues) on what makes for a good bug report.
