### ISSUE TITLE
Embedding multiple stateless app into an HTML page using plotly_direct

### ISSUE THREAD

**Issue by Pritesh-Inexture** [GibbsConsulting/django-plotly-dash#261]
I have a function created which dynamically registers the plotly dash apps and then I use these stateless apps in my Django template using the `{% plotly_direct name="asdf" %}` tag. The problem is when I have single app registered it works but as soon as I register more than one app only the first one loads and others keep showing loading...

This happens only with the plotly_direct tag I have tried using the `plotly_app_bootstrap` and in that case, both apps is visible on the page.

Here is my code snippet of Django HTML template

```
{% load plotly_dash %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dash with django</title>
    {% plotly_header %}
</head>
<body>

{% for dash in dash_names %}
    {% plotly_direct name=dash %}
{% endfor %}

</body>
{% plotly_footer %}
</html>
```

Please note that if I replace `{% plotly_direct name=dash %}` with `{% plotly_app_bootstrap name=dash %}` every stateless app will appear on the page. I am not sure how can I fix this issue or what I am doing wrong here.

**Comment by GibbsConsulting** [comment]
As described in the [documentation](https://django-plotly-dash.readthedocs.io/en/latest/template_tags.html#the-plotly-direct-template-tag), the `plotly_direct` tag can only be used once on a page. This is because, unlike the alternatives, it does not isolate the Dash app; the other tags do this by embedding it in an iframe.

Is there a specific reason why you are using this instead of the `plotly_app` or `plotly_app_bootstrap` tags?

**Comment by Pritesh-Inexture** [comment]
I do not want it in an iframe. I am trying to display multiple dash app in a page inside multiple divs and then the user will be able to save them as pdf and or print from browser

**Comment by GibbsConsulting** [comment]
@Pritesh-Inexture only running a single app per page is a Dash restriction. Tags like `plotly_app` and `plotly_app_bootstrap` get around this by embedding apps in iframes. Is there some specific part of your approach that prevents it working with content embedded in iframe tags?

**Comment by Pritesh-Inexture** [comment]
Not really, I do not like using iframes so I was wondering if there is any workaround. Also, would you be able to help if I wanted to render apps dynamically using ajax calls? I am not really sure where to start. I will be really thankful if you can show my simple steps of achieving that, couldn't find anything like that in the docs

**Comment by GibbsConsulting** [comment]
Short of rewriting Dash, I can't see any way of avoiding iframes if you want multiple apps on the same page. And I have to admit I find it hard to think of any compelling reason to do so.

As for ajax calls, see #163
