### ISSUE TITLE
Use of wildcard callbacks (id==dict)

### ISSUE THREAD

**Issue by ndedman** [GibbsConsulting/django-plotly-dash#262]
I've switched to using wildcard callbacks for dynamic range filters in my app. Sadly, it doesn't work with django_wrapper, throwing exceptions:

`/venv/lib/python3.7/site-packages/django_plotly_dash/dash_wrapper.py", line 419, in augment_initial_layout
    reworked_data = self.walk_tree_and_replace(baseData, initial_arguments)`

`/venv/lib/python3.7/site-packages/django_plotly_dash/dash_wrapper.py", line 456, in walk_tree_and_replace
    replacements = self._replacements.get(thisID, {})
TypeError: unhashable type: 'dict'`

Have I missed something in my implementation or is feature not implemented yet?

Thanks!

Django==2.2
django-plotly-dash==1.4.2

**Comment by GibbsConsulting** [comment]
@ndedman it is not implemented at the moment, and at the moment there aren't any definite plans for this feature. I've added #264 

Pull requests are always most welcome, and [commercial support](https://gibbsconsulting.ca/) is always available, for both existing features and for accelerating new development.

**Comment by GibbsConsulting** [comment]
This should now have been resolved as part of v1.6.0
