### ISSUE TITLE
Unable to find stateless DjangoApp called simpleexample

### ISSUE THREAD

**Issue by jsguerrero** [GibbsConsulting/django-plotly-dash#263]
Why does it not allow to use Dash applications with a different name?

I don't know what I've done wrong.

`http://localhost:8080/sima/data_exploration`
![imagen](https://user-images.githubusercontent.com/13953486/87320288-6130ba80-c4f0-11ea-80fd-1070c6bc1c0f.png)

`http://localhost:8080/django_plotly_dash/app/bubble/`
![imagen](https://user-images.githubusercontent.com/13953486/87320355-76a5e480-c4f0-11ea-8c44-6f354998ad6b.png)

My idea is to integrate several types of graphs (bubble, boxplot, lines) within the same page.

Note: if I change the name of the Dash application to SimpleExample then it works, but I can't understand how to change it.

`http://localhost:8080/sima/data_exploration`
![imagen](https://user-images.githubusercontent.com/13953486/87321087-65110c80-c4f1-11ea-88fe-02ee060204bc.png)

Thanks.

**Comment by GibbsConsulting** [comment]
@jsguerrero see [this post](https://community.plotly.com/t/django-plotly-dash-unable-to-find-stateless-djangoapp-called-simpleexample/42417) on the plotly forum; essentially you give a name to each app that you create, and this name is used in the template tag to determine which app to render.

**Comment by jsguerrero** [comment]
Thanks for the reply.

I don't know exactly what happened (or what I did wrong), but even changing the app name this showed the error, what I did was from the django admin, delete the SimpleExample app and then it worked.

Regards.
