### ISSUE TITLE
Add support for wildcard callbacks

### ISSUE THREAD

**Issue by GibbsConsulting** [GibbsConsulting/django-plotly-dash#264]
Dash now permits the use of wildcards in callbacks. This issue is a placeholder for investigating the work needed to extend support to cover this feature and for any resultant implementation.

If you are interested in sponsoring this work please reach out [here](https://gibbsconsulting.ca/).

**Comment by radupm** [comment]
It's a pity we can't use the [pattern matching callbacks](https://dash.plotly.com/pattern-matching-callbacks) :disappointed: . Hopefully this will be added soon :pray:

**Comment by GibbsConsulting** [comment]
These should now be supported in v1.6.0 onwards
