### ISSUE TITLE
./make_env continues even if virtualenv is not installed

### ISSUE THREAD

**Issue by schlich** [GibbsConsulting/django-plotly-dash#272]
Hi,

I was trying to run the demo application and the script continued to install all of the dependencies even though i didnt have virtualenv configured, despite outputting the following two errors:
`./make_env: line 5: virtualenv: command not found`
`./make_env: line 7: env/bin/activate: No such file or directory`

**Comment by GibbsConsulting** [comment]
That is a bit annoying. It is listed as a prerequisite but we can do better at handling error cases in this script.

**Comment by bastiaan85** [comment]
I've ran into this issue as well, it continues running pip so it will install the requirements to your system environment instead... As make_env is a Bash script, all it needs is a `set -e` at the start to let it stop when any command returns a non-zero return code.

**Comment by GibbsConsulting** [comment]
@bastiaan85 thanks for the reminder about this. PR #340 merged to the main branch, which contains an updated script.
@schlich this should fix things. It also permits user selection of the python version now.
