### ISSUE TITLE
JSONDecodeError at /django_plotly_dash/app/SimpleExample/_dash-update-component

### ISSUE THREAD

**Issue by aayushaggarwal** [GibbsConsulting/django-plotly-dash#276]
Hi 

I am new to DPD, Plotly and Dash. I am trying to integrate a dash app with Django using dpd. 

Dash app is running perfectly when ran using Flask. But when integrated it with Django showing "JSONDecodeError". Attached error traceback. I have configured Django as mentioned in Dpd Docs.

Any pointers on how to resolve this error?

-----------
Internal Server Error: /django_plotly_dash/app/SimpleExample/_dash-update-component
Traceback (most recent call last):
  File "/Users/aayushaggarwal/Desktop/code/django/app_env3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/aayushaggarwal/Desktop/code/django/app_env3/lib/python3.7/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/aayushaggarwal/Desktop/code/django/app_env3/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/aayushaggarwal/Desktop/code/django/app_env3/lib/python3.7/site-packages/django_plotly_dash/views.py", line 74, in update
    return _update(request, ident, stateless, **kwargs)
  File "/Users/aayushaggarwal/Desktop/code/django/app_env3/lib/python3.7/site-packages/django_plotly_dash/views.py", line 93, in _update
    resp = view_func()
  File "/Users/aayushaggarwal/Desktop/code/django/app_env3/lib/python3.7/site-packages/django_plotly_dash/dash_wrapper.py", line 560, in dispatch
    return self.dispatch_with_args(body, argMap=dict())
  File "/Users/aayushaggarwal/Desktop/code/django/app_env3/lib/python3.7/site-packages/django_plotly_dash/dash_wrapper.py", line 622, in dispatch_with_args
    if c['property'] == component_registration['property'] and c['id'] == component_registration['id']:
TypeError: list indices must be integers or slices, not str

**Comment by GibbsConsulting** [comment]
What versions of DPD and Dash are you using? This looks like it could be due to a recent change in an underlying library.

**Comment by aayushaggarwal** [comment]
django-plotly-dash is 1.4.2  and dash is 1.14.0

**Comment by aayushaggarwal** [comment]
@GibbsConsulting  any suggestions on how can we resolve this error ?

**Comment by GibbsConsulting** [comment]
@aayushaggarwal  you could try running with an earlier version of Dash to see if that is the source of the problem. Otherwise, you will have to share some more details; in particular the decorators applied to the app's callback function(s).

Are you trying to use wildcard callbacks? They're not supported (at least for the moment).

**Comment by aayushaggarwal** [comment]
@GibbsConsulting  I tried  running with older version but receiving the same error.Here is snapshot of app's callback function
We have created a states variable which have  static and dynamic variables like 'goal_name',goal_val, 'goal_per' and 'goal_type'
STATES = [State('mon_spen', 'value'), State('mon_sav', 'value'), State('tot_sav', 'value'),
          State({'type': 'goal_name', 'index': ALL}, 'value'), State({'type': 'goal_val', 'index': ALL}, 'value'),
          State({'type': 'goal_per', 'index': ALL}, 'value'), State({'type': 'goal_type', 'index': ALL}, 'value')]


@app.callback(Output('output', 'children'), [Input('submit', 'n_clicks')], STATES)
def generate_output(n_clicks, mon_spen, mon_sav, tot_sav, goal_name, goal_val, goal_per, goal_type):

    if n_clicks == 0:
        return None
    return graph_generator(mon_spen, mon_sav, tot_sav, goal_name, goal_val, goal_per, goal_type)


Is dynamic ids are supported for the moment ?

**Comment by GibbsConsulting** [comment]
@aayushaggarwal as per the comment above and also #264 wildcards are not supported at the moment.

One way forward would be to alter your app to not use wildcards. Our experience so far is that this is always possible, and as a result there hasn't been much of a push to add this feature.

**Comment by kvivek18** [comment]
@GibbsConsulting can you help me with the same problem, when the number of states of a call back function change dynamically. I used pattern matching callbacks which makes it possible in Dash. 

How to implement the same functionality in Django-Dash where dynamic ids are not supported.

I would make my problem clearer, number of States in my callback function change dynamically and I don't know how many parameters to pass in the callback function.

Thankyou!

**Comment by GibbsConsulting** [comment]
@kvivek18 as per above, you're trying to use something that is not supported at the moment. The recommended solution right now is to change your application to not use wildcards.

Any contributions towards moving #264 are most welcome!

**Comment by kvivek18** [comment]
@GibbsConsulting thanks for your help. Hope wildcards feature get added soon !
