### ISSUE TITLE
Pass initial argument from django to django dash app

### ISSUE THREAD

**Issue by havanaDimi** [GibbsConsulting/django-plotly-dash#279]
I want to pass a variable from django view to DjangoDash application. In details, I want to use the id that I receive from get method in Django view to the DjangoDash in order to make some plots with filtered data based on that id.

I followed this approach https://github.com/GibbsConsulting/django-plotly-dash/issues/173 which was very helpful, but still can't have access of the variable in the DjangoDash.

views.py

```
def getID(request):

queryid= request.GET['queryid']

context = {'data':{"query_id":queryid}}

template_name="djangoDash.html"
return render(request, template_name, context)
```
In order to use the DjangoDash with initial arguments with the content data from the view.

djangoDash.html

```
.....
{% plotly_app name='djangoDash' ratio=0.45 initial_arguments=data %}
....
```
When I define the djangoDash app I use this

`app = DjangoDash('djangoDash', id='query_id', serve_locally=False,  suppress_callback_exceptions=True)`
And I use this id as an input over my layout to use it for the queries with the bellow callback.

```
layout = html.Div([
                   dcc.Input(id='query_id'),
                   html.Div(id='result'),
                  ])

@app.expanded_callback(dash.dependencies.Output('result', 'children'),
                       [dash.dependencies.Input('query_id', 'value')])
def display_output(query_id):
    result= query_id
    return result
```
The error I get when I load the page is

  ```
File "/home/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
response = get_response(request)
 File "/home/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/.local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/.local/lib/python3.6/site-packages/django_plotly_dash/views.py", line 74, in update
    return _update(request, ident, stateless, **kwargs)
  File "/home/dimicham/.local/lib/python3.6/site-packages/django_plotly_dash/views.py", line 102, in _update
    resp = app.dispatch_with_args(request_body, arg_map)
  File "/home/.local/lib/python3.6/site-packages/django_plotly_dash/dash_wrapper.py", line 647, in dispatch_with_args
    res = self.callback_map[target_id]['callback'](*args, **argMap)
  File "/home/.local/lib/python3.6/site-packages/dash/dash.py", line 994, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
TypeError: display_page() got an unexpected keyword argument 'dash_app_id'
HTTP POST /djangoDash/app/djangoDash/initial/dpd-initial-args-52e61040fc9b4edd9519db95eadaa6bc/_dash-update-component 500 [0.17, 160.40.70.30:49439]
  File "/home/.local/lib/python3.6/site-packages/django_plotly_dash/dash_wrapper.py", line 647, in dispatch_with_args
    res = self.callback_map[target_id]['callback'](*args, **argMap)
  File "/home/.local/lib/python3.6/site-packages/dash/dash.py", line 994, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
TypeError: display_page() got an unexpected keyword argument 'dash_app_id'
```

**Comment by GibbsConsulting** [comment]
The error message is about a different callback (`display_page` rather than `display_output`) but the resolution is the same; you should add `**kwargs` to the signature of the callback function as the `expanded_callback` decorator will cause extra information to be added to the function call.

See the [extended callback documentation](https://django-plotly-dash.readthedocs.io/en/latest/extended_callbacks.html#extended-callback-syntax) for more details.

**Comment by havanaDimi** [comment]
I don't have a callback function named display_page and I took a look to the documentation for the proper configuration of the expanded_callback but still facing the same issue. 

Is there any complete example for using the initial arguments to the DjangoDash with expanded_callback??

**Comment by GibbsConsulting** [comment]
From the demos, [demo 2](https://github.com/GibbsConsulting/django-plotly-dash/blob/master/demo/demo/templates/demo_two.html)uses initial arguments and [demo 3](https://github.com/GibbsConsulting/django-plotly-dash/blob/master/demo/demo/templates/demo_three.html) extended callbacks.

The code part of the extended callback example is in the [plotly_apps.py](https://github.com/GibbsConsulting/django-plotly-dash/blob/master/demo/demo/plotly_apps.py#L99) file in the demo folder.

The error you report comes from a callback being invoked; what version of Dash are you using?

**Comment by havanaDimi** [comment]
Thank you very much. Probably I should take a closer look because it's not clear enough or to follow other approach to get the variable from django to the Djangodash app.

dash version: dash-1.16.1.

**Comment by joannehc** [comment]
Hi, I followed this post and another post https://github.com/GibbsConsulting/django-plotly-dash/issues/173 but still face an error "Dash() got an unexpected keyword argument 'id'".  The idea is to filter the default data using a user attribute,e .g. user.company. I added **kwargs. I am not sure what else is missing. 

views.py 
```
    class ChartView(TemplateView):
        template_name = 'chart.html'    

    default_website = ...
    def dashboard_display(request,default_website):
        context = {'data': {'default_website': default_website}}
        return render(request,'dashboard/chart',context) 

```
chart.html
```
...
{% plotly_app name='chart' initial_arguments=data ratio=0.6 %}
...
```
app.py

```
app = DjangoDash(name='chart', id='default_website', external_stylesheets=external_stylesheets)

app.layout = html.Div([
    dcc.Input(id='default_website'),
    html.Label('Website'),
    dcc.Dropdown(
        id='site-dropdown',
        options=[
            {'label': site, 'value': site}
            for site in df['site_id'].unique()
        ],
    ),
@app.expanded_callback(
    Output('site-dropdown', 'children'),
    [Input('default_website', 'value')])
def display_output(default_website, **kwargs):
    result = default_website
    return result
```

**Comment by nikhilnaregal** [comment]
@havanaDimi  Can you please tell the solution??

**Comment by havanaDimi** [comment]
> @havanaDimi Can you please tell the solution??

The solution I figured out is:

You can define the DjangoDash app 
`app = DjangoDash('djangoDash', serve_locally=True,  suppress_callback_exceptions=True)`

and to retrieve and use the value of queryid just declare hidden object in your dash app (sug. encrypted)
`dcc.Input(id="queryid", style={"display": "none"},
                   value=" "),`

Hope I helped!

**Comment by KuechlerO** [comment]
Puh, took me some while to understand how to use the **_initial_arguments_** thingy, so here are my steps that made it work for me:

1.) When you render and pass a context with Django, then also create a dash_context, e.g.:
```
return render(request, self.template_name, {"normal_context": context_data,
                                                    "dash_context": {"dropdown1": {"value": value1, "label1": label1},
                                                                     "dropdown2": {"value": value2, "label": label2}
                                                                     }})
```

2.) Pass plotly-context to plotly-dash-app in your template:
```
                {% load plotly_dash %}
                {% plotly_app_bootstrap name="Example" initial_arguments=dash_context aspect="16by9" %}
```
3.) The corresponding dash-elements with ids "dropdown1" and "dropdown2" are going to receive the given values as initial values. Make sure that a "value"-attribute and maybe also a "persistence"-attribute is included, otherwise it might be buggy.

Example element:
`dcc.Input(id="diseases_dropdown2", persistence=False, value="test")`

4.) Enjoy!

**Comment by sofiadie17** [comment]
@KuechlerO THANKS! After days of studying and trying with absolutely no results this is the way I found to pass URL parameters to Dash app, since calling it by constructing a JSON and loading the parameter as a template tag such as:

`{% plotly_app name='my_app' ratio=0.7  initial_arguments= {"id": {"value": "{{ id }}" }}%}`

wasn't working for me, since {{ id }} was directly read as an string and not getting the actual value. Instead, building the JSON at view's return worked perfectly for me!!

Thank you very much! :)

**Comment by redtensor22** [comment]
@KuechlerO could you give more code for your actual app? I have followed the exact logic but cant get the value to actually show up in the dash. My template (for simplicity) has:

`{%plotly_app name="tutorial_1" initial_arguments='{"target_id": {"value": "67"}}' %}`

And my app is:

`app = DjangoDash('tutorial_1')



app.layout = html.Div([
    dcc.Input(id='target_id', persistence=False, value="test"),
    html.Div(id="output-one")
    ])

@app.expanded_callback(
    dash.dependencies.Output('output-one','children'),
    [dash.dependencies.Input('target_id','value')]
    )
def callback_c(*args,**kwargs):
    print(value)
    return value

if __name__ == '__main__':
    app.run_server(debug=True)`

but i cannot get the number '67' to pop up in the text pane

**Comment by KuechlerO** [comment]
> @KuechlerO could you give more code for your actual app? I have followed the exact logic but cant get the value to actually show up in the dash. 

I think you have an exta apostrophe in your code, which is causing the error.

Instead of 
`{%plotly_app name="tutorial_1" initial_arguments='{"target_id": {"value": "67"}}' %}`

try:
`{%plotly_app name="tutorial_1" initial_arguments= {"target_id": {"value": "67"}}  %}`
