### ISSUE TITLE
Unable to access page session variable

### ISSUE THREAD

**Issue by duguarun** [GibbsConsulting/django-plotly-dash#282]
Unable to access any of the **request.session/POST/GET** variable inside Dash app. Is there way to pass the these variables to the Dash app?

**Comment by GibbsConsulting** [comment]
Take a look at the [extended callback](https://django-plotly-dash.readthedocs.io/en/latest/extended_callbacks.html) documentation and also several of the apps in the [demo](https://github.com/GibbsConsulting/django-plotly-dash/tree/master/demo/demo) use this data.

You will need to be clear about the information you pass when starting a Dash app in a template (ie initial app state) versus information you extract during the app's lifetime (like the current session state).
