### ISSUE TITLE
Dash app not loading

### ISSUE THREAD

**Issue by ad15665** [GibbsConsulting/django-plotly-dash#290]
Hi, my application worked perfectly and then I tried to deploy my app onto azure.  When I was going through the process of deploying, I chose to update all of my python packages (disaster).  All other aspects of my app work fine except for the dashboard. When I click onto the page, I get a "Loading..." displayed in the top left-hand corner and then the page goes blank.  I have no errors within my terminal.  The only error I can find is after clicking "Inspect" on Chrome:
<img width="1088" alt="Screenshot 2020-11-20 at 11 14 28" src="https://user-images.githubusercontent.com/35807667/99794116-9cd43480-2b21-11eb-9bbd-ec8159c47ed0.png">

Any direction on how to diagnose would be really helpful.  Thank you!

requirements.txt:
aioredis==1.3.1
asgiref==3.3.1
async-timeout==3.0.1
attrs==20.3.0
autobahn==20.7.1
Automat==20.2.0
Brotli==1.0.9
cffi==1.14.3
channels==3.0.2
channels-redis==3.2.0
click==7.1.2
constantly==15.1.0
cryptography==3.2.1
daphne==3.0.1
dash==1.17.0
dash-core-components==1.13.0
dash-html-components==1.1.1
dash-renderer==1.8.3
dash-table==4.11.0
Django==3.1.3
django-cleanup==5.1.0
django-crispy-forms==1.10.0
django-plotly-dash==1.4.2
django-private-storage==2.2.2
dpd-components==0.1.0
Flask==1.1.2
Flask-Compress==1.8.0
future==0.18.2
fuzzywuzzy==0.18.0
hiredis==1.1.0
hyperlink==20.0.1
idna==2.10
incremental==17.5.0
itsdangerous==1.1.0
Jinja2==2.11.2
MarkupSafe==1.1.1
msgpack==1.0.0
numpy==1.19.4
pandas==1.1.4
Pillow==8.0.1
plotly==4.12.0
psycopg2==2.8.6
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
PyHamcrest==2.0.2
pyOpenSSL==19.1.0
python-dateutil==2.8.1
python-Levenshtein==0.12.0
pytz==2020.4
retrying==1.3.3
service-identity==18.1.0
six==1.15.0
SQLAlchemy==1.3.20
sqlparse==0.4.1
Twisted==20.3.0
txaio==20.4.1
Werkzeug==1.0.1
zope.interface==5.2.0

**Comment by muhamrii** [comment]
i have the same problem, i have done a lot but still there is no solution for this issue. I hope there will be an answer to this issue.

**Comment by GibbsConsulting** [comment]
@ad15665 @muhamrii this sounds like package (or python) version incompatibility. Are the packages the same versions for the local and cloud environments? What versions of python are being used?

**Comment by ad15665** [comment]
Hi, I haven't actually got the cloud version up and running yet. In my local environment, I'm using Python 3.8.2 within pycharm on a macbook pro 2018... Thanks for helping!

**Comment by pgchj** [comment]
Hi, try this:
In settings.py, goto INSTALLED_APPS list,

comment out the "channels" and only use "channels_redis"

**Comment by ad15665** [comment]
Hi, okay thank you, will try now.

**Comment by ad15665** [comment]
Yes that worked!!!!!!!!!!!!!!!!  Thank you thank you. How did you know to do that?

**Comment by pgchj** [comment]
> Yes that worked!!!!!!!!!!!!!!!! Thank you thank you. How did you know to do that?

i guess the development server cannot handle the asynchronous connection well, so just removing the channel implementation...

**Comment by GibbsConsulting** [comment]
@pgchj @ad15665 @muhamrii v1.5.0 is now available. This should resolve the problem by using a version of channels < 3.0
