### ISSUE TITLE
Is it possible to still use the Flask decorators like @app.server.before_first_request in dpd?

### ISSUE THREAD

**Issue by Ascarin** [GibbsConsulting/django-plotly-dash#298]
What I read from the code is that we do have a Pseudo Flask class which overwrites the method. 
`    def before_first_request(self, *args, **kwargs):
        pass`

That causes the annotation not to work, but I find it very useful when starting an app initial loaded data.
Is there a better workaround than to call the functions in the app.urls.py file?
Thanks!

**Comment by GibbsConsulting** [comment]
The PseudoFlask class provides enough underlying Flask functionality to make dpd work, which doesn't extend to things like this function - any per-process initialization needed in a Django app can (should?) be achieved as you note during the import of the app's urls.py file.

Its not clear if a before_first_request function can provide anything over and above this anyway - is there something in particular you're looking to do other than some initialization?

**Comment by Ascarin** [comment]
No not really. Good to hear that is actually the way to go. Thanks a lot!
