### ISSUE TITLE
How to log user activity on certain callbacks

### ISSUE THREAD

**Issue by johanvergeer** [GibbsConsulting/django-plotly-dash#300]
We would like to log user activity when they perform certain actions. E.g. Viewing a report, creating something or deleting something.

First we thought to just add user information to the standard logs, but that doesn't help us very much since the logs don't really output very useful information. 

```
{"event": "\"POST /django_plotly_dash/app/actions-create/_dash-update-component HTTP/1.1\" 200 43", "timestamp": "2021-01-12T12:59:57.432964Z"}
{"event": "\"POST /django_plotly_dash/app/actions-create/_dash-update-component HTTP/1.1\" 200 91", "timestamp": "2021-01-12T12:59:57.466981Z"}
{"event": "\"POST /django_plotly_dash/app/actions-create/_dash-update-component HTTP/1.1\" 200 91", "timestamp": "2021-01-12T12:59:57.574979Z"}
{"event": "\"POST /django_plotly_dash/app/actions-create/_dash-update-component HTTP/1.1\" 204 0", "timestamp": "2021-01-12T12:59:57.606969Z"}
{"event": "\"POST /django_plotly_dash/app/actions-create/_dash-update-component HTTP/1.1\" 200 43", "timestamp": "2021-01-12T12:59:57.744538Z"}
{"event": "\"POST /django_plotly_dash/app/actions-create/_dash-update-component HTTP/1.1\" 200 697", "timestamp": "2021-01-12T12:59:57.963686Z"}
{"event": "\"POST /django_plotly_dash/app/actions-create/_dash-update-component HTTP/1.1\" 200 697", "timestamp": "2021-01-12T12:59:58.213345Z"}
{"event": "\"POST /django_plotly_dash/app/actions-create/_dash-update-component HTTP/1.1\" 200 697", "timestamp": "2021-01-12T12:59:58.653034Z"}
```

These logs were created while opening a page, entering some data and saving the data.

Adding a user here is not very hard, but it still wouldn't show us what the user did. Aside from that the database would be called for each an every request, and there are a lot of them.

We need to know which user performed what operation on a certain timestamp.

**Comment by GibbsConsulting** [comment]
Django has extensive [logging](https://docs.djangoproject.com/en/3.1/topics/logging/) capabilities and this may be your easiest way forward.

If that is not enough, you can probably get what you want with some custom Django middleware - the items in the middleware stack get invoked on every call, so you can select on `django-plotly-dash` paths and then log (or otherwise capture) the information you're after.

**Comment by johanvergeer** [comment]
Thanks for your fast response @GibbsConsulting.

The solution you provided still leads to logging every single GET and POST request, which is a lot, while we would like to have more fine-grained control. Every event that is logged points to the same URL, so how are we supposed to know whether someone just opened the `actions-create` page or actually clicked the `Save` button on the page?

**Comment by GibbsConsulting** [comment]
So somewhere you will have to capture the idea of what subset of calls you want to log. If the standard Django logging doesn't allow the needed level of fine-grained control then you'll have to capture the calls in middleware and then conditionally output whatever information you want to see.

It sounds like your condition for logging will involve the callback url as well as some of the parameters in it - this will include which callback along with the names and values of the properties passed to it.

**Comment by johanvergeer** [comment]
Thanks for your advice @GibbsConsulting 

We ended up by creating a custom decorator called `log_event` that we can put on a callback function. 

That gives us more flexibility over the stuff we want to log for each callback function.
