### ISSUE TITLE
Can django-plotly-dash handle multiple callback outputs for clientside_callback ?

### ISSUE THREAD

**Issue by sdementen** [GibbsConsulting/django-plotly-dash#301]
I am using a clientside callback with multiple output.
It raises an exception NotImplementedError("django-plotly-dash cannot handle multiple callback outputs at present") due to https://github.com/GibbsConsulting/django-plotly-dash/blob/master/django_plotly_dash/dash_wrapper.py#L547.
When commenting the line, I have the impression it works properly. Is this correct ? or does it work only partially ?

**Comment by GibbsConsulting** [comment]
It hasn't been tested, but it could well be only partially - the first thing to validate would be the storage of the returned callback values. The [application state](https://django-plotly-dash.readthedocs.io/en/latest/models_and_state.html#the-dashapp-model) section of the documentation notes how certain parts of the application state can be persisted using the Django ORM.

**Comment by sdementen** [comment]
As the callback is running on the client without calling the server, I guess the server can't do much in terms of storing state, right?

**Comment by GibbsConsulting** [comment]
Aplogies, I missed the 'clientside' part of the callback! For sure, the server won't be storing state. The line you located dates from when all callbacks were server side. It should be possible to skip this test for clientside callbacks without adverse consequences.

**Comment by GibbsConsulting** [comment]
Created #303 to resolve this for client-side callbacks

**Comment by GibbsConsulting** [comment]
Now released as part of v1.6.0
