### ISSUE TITLE
Remove multiple return value check for clientside_callbacks

### ISSUE THREAD

**Issue by GibbsConsulting** [GibbsConsulting/django-plotly-dash#303]
As reported in #301 there is a check to prevent use of multiple server-side callback values as this is not handled at present.

However, the check appears to also prevent the use of client-side callbacks with multiple return values, and should be relaxed to not prevent this use case.

**Comment by sdementen** [comment]
as a side note, it may be worth to switch from the `super(StatelessApp, self).save(*args, **kwargs)` form to `super().save(*args, **kwargs)` everywhere in the code
