### ISSUE TITLE
[question] How to make more responsive of the layout when in small screen

### ISSUE THREAD

**Issue by miaoz2001** [GibbsConsulting/django-plotly-dash#310]
Hi,

I have a question to ask...
I am making a layout using bootstrap, so i do
`{%plotly_app name="SimpleExample"%}`   or `{%plotly_app_bootstrap name="SimpleExample" aspect="16by9"%}`

but both of them use a ratio (0.4, 0.5... 16by9) which make it ok in big screen (width is bigger than height), but when it comes to a small screen/phone, I would like the ratio to be 1.x, or 2.X (width is smaller than height).

Is it possible to achieve this? I can dynamically update the ratio but it is troublesome, i think it is not a good solution.
I hope there is a better solution.

Is it possible not using the ratio at all? 
Thanks

**Comment by GibbsConsulting** [comment]
You could try adapting the template used by the `plotly_app_bootstrap` tag - the one in the [package](https://github.com/GibbsConsulting/django-plotly-dash/blob/master/django_plotly_dash/templates/django_plotly_dash/plotly_app_bootstrap.html) can be [overridden](https://docs.djangoproject.com/en/3.1/howto/overriding-templates/) like any other Django template.

**Comment by miaoz2001** [comment]
thanks, will have a try
