### ISSUE TITLE
static files referenced in plotly_header/footer redirect to /static, why not directly /static

### ISSUE THREAD

**Issue by sdementen** [GibbsConsulting/django-plotly-dash#323]
I have noticed that the     {% plotly_header %} and {% plotly_footer %} command in the template generates reference of the form:
- /static/path/to/file
- https://some-external-site
- /django_plotly_dash/instance/... => this will redirect to an asset hosted on /static
Example in the header
```
<link rel="stylesheet" href="/static/dpd/assets/simulation/dashapps/vizualizer/layout.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<link rel="stylesheet" href="/django_plotly_dash/instance/visualizer-pb8qnxg-nazykxn/_dash-component-suites/dpd_static_support/bootstrap.v0_1m1608548852.min.css">
```
In the footer, they are all of the form `/django_plotly_dash/instance/...`.
This latter form is problematic as I do not see how to serve those files efficiently as static files. Each asset will make a call through django (with all the middleware/etc) before returning a 302 redirecting to /static (which can easily be managed as static files).

Is that the expected behavior ?
Can this be changed to avoid the performance penalty when loading the app ?

**Comment by GibbsConsulting** [comment]
@sdementen the indirection is present as Dash apps generate urls relative to their own base url; this in turn is only determined at runtime. If it is introducing too much overhead - not something that I've noticed, but I haven't explicitly looked for it - then we'd have to do something along the lines of rewriting the urls inside Dash when they're first generated.

**Comment by sdementen** [comment]
For my app, I have 17 js files that are requested after the index page has been loaded (of which 14 are referenced from the index file).
This adds quite a bit of latency as for each of these files Django needs to process the request and then return a 302 pointing to the static asset.
Would you see some easy way I could "patch" the current DashWrapper or DjangoDash class to avoid this ? So I could test in practice the difference of performance when loading the app

**Comment by GibbsConsulting** [comment]
One way could be to explicitly serve those referenced from the index file as static assets in Django - ie change the template itself.
Another would be to reduce the number of files, for example combining the 14 into 1.
At the moment, DjangoPlotlyDash uses string substitution in middleware - see for example the [middleware](https://github.com/GibbsConsulting/django-plotly-dash/blob/master/django_plotly_dash/middleware.py) - and it is probably possible to leverage this somehow.
