### ISSUE TITLE
Passing variable from Django to Dash TypeError: Dash() got an unexpected keyword argument

### ISSUE THREAD

**Issue by joannehc** [GibbsConsulting/django-plotly-dash#327]
Hi, I followed this post https://github.com/GibbsConsulting/django-plotly-dash/issues/279 and another post https://github.com/GibbsConsulting/django-plotly-dash/issues/173 but still face an error "Dash() got an unexpected keyword argument 'id'".  The idea is to filter the default data using a user attribute,e .g. user.company. I added **kwargs. I am not sure what else is missing. 

views.py 
```
    class ChartView(TemplateView):
        template_name = 'chart.html'    

    default_website = ...
    def dashboard_display(request,default_website):
        context = {'data': {'default_website': default_website}}
        return render(request,'dashboard/chart',context) 

```
chart.html
```
...
{% plotly_app name='chart' initial_arguments=data ratio=0.6 %}
...
```
app.py

```
app = DjangoDash(name='chart', id='default_website', external_stylesheets=external_stylesheets)

app.layout = html.Div([
    dcc.Input(id='default_website'),
    html.Label('Website'),
    dcc.Dropdown(
        id='site-dropdown',
        options=[
            {'label': site, 'value': site}
            for site in df['site_id'].unique()
        ],
    ),
......

@app.expanded_callback(
    Output('site-dropdown', 'value'),
    [Input('default_website', 'value')])
def display_output(default_website, **kwargs):
    result = default_website
    return result
```

I also tried to just load a static value in initial_arguments. The page template loads but Dash part shows "Error loading layout". 

`{% plotly_app name='chart' initial_arguments='{"site-dropdown": {"value": "SITE"}}' ratio=0.6 %}`

**Comment by gabegrand** [comment]
@joannehc Your latter solution should work, but there's currently a bug with `initial_arguments` in the latest release (https://github.com/GibbsConsulting/django-plotly-dash/issues/328). If you downgrade to `django-plotly-dash==1.6.0` it should work.

**Comment by joannehc** [comment]
@gabegrand , I downgraded to 1.6.0. The error disappeared but the value is still not passed. The page loads fine just with no default value in the dropdown. 

I tried to isolate the issue by using only static value in initial_arguments like before. 
{% plotly_app name='chart' initial_arguments='{"site-dropdown": {"value": "SITE"}}' ratio=0.6 %}
The page loads fine too but also with no default value in dropdown.

**Comment by gabegrand** [comment]
I'm glad that the downgrade to 1.6.0 fixed the error. It sounds like the remaining issue may just be a problem with the configuration of the Dash components. I would recommend trying a simpler component like a `dcc.Input` and see if you can get the `initial_arguments` to work there.

**Comment by AngelaMorenoPrado** [comment]
In case you still haven't solved the problem, this has worked for me. I downgraded Dash to 1.6.0 by `django-plotly-dash==1.6.0`.

On views.py:
`dash_context = {'target_id': {'value': cuenta}}`
being 'cuenta' the variable I had to pass to Dash, and the layers to unpack `dash_context`, `target_id`, `value`.

HTML:
`{% plotly_app name='female_graphs' ratio=1 initial_arguments=dash_context %}`

Graphs.py:

1. `app = DjangoDash(name='female_graphs', id='target_id')`
2. Add the dcc.Input to the app.layout: `app.layout = html.Div(children=[ dcc.Input(id='target_id', type='hidden', value=''),`
3. Add Input to @app.expanded_callback `Input('target_id', 'value'),`
4. `def female_graphs(value...`



Hope this helps!
