### ISSUE TITLE
Multipage Dash Plotly app is not rendering from Django app

### ISSUE THREAD

**Issue by vinodagouda** [GibbsConsulting/django-plotly-dash#333]
**Hi team,
I am NOT able to render the multipage dash app. Below is the piece of code which is the entry point for multipage dash app.**

File name is _simpleexample.py_

`import dash
import dash_bootstrap_components as dbc
from django_plotly_dash import DjangoDash

import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output

from . apps import log_predictor

external_stylesheets = ['../assets/app.css', dbc.themes.BOOTSTRAP]

app = DjangoDash(name = 'SimpleExample', suppress_callback_exceptions = True)

app.layout = html.Div([
    dcc.Location(id='url', refresh=False),
    html.Div(id='page-content')
])

@app.expanded_callback(Output('page-content', 'children'),
              Input('url', 'pathname'))
def display_page(pathname):
    if pathname == '/apps/log_predictor':
        return log_predictor.layout
    elif pathname == '/':
        return log_predictor.layout
    else:
        return '404'`
        
 **Inside Django template, this is how I am trying to render Dash app**
 
 `<html>
<body>
{% block content %}
<p>Get Dash code here first</p>
    {% load plotly_dash %}
    <div class="{% plotly_class name='SimpleExample' %} card" style="height: 100%; width: 100%">
    {% plotly_app name='SimpleExample' ratio=0.45 %}
    </div>
	<br>
    {{ plot1 | safe }}

{% endblock %}

</body>
</html>`

**I am also attaching the folder structure image of app. Please check the below image**
<img width="291" alt="Folder_structure" src="https://user-images.githubusercontent.com/29706348/115710189-b3600f80-a38f-11eb-9162-81b4d98be66c.PNG">

**Comment by GibbsConsulting** [comment]
You're trying to return a layout from a callback. That won't work. You can either use a single app with [url-related components](https://dash.plotly.com/urls) to handle the `url.pathname` property, or let Django handle it with multiple `DjangoDash` instances; the best way forward is very much dependent on your application.

**Comment by vinodagouda** [comment]
Thanks for the reply. Will try that.

**Comment by AashkaVijapura** [comment]
@vinodagouda did you figure out , how to make that multipage dash application work, I am facing the same issue
