### ISSUE TITLE
using dash-leaflet  renders no map

### ISSUE THREAD

**Issue by kirodh** [GibbsConsulting/django-plotly-dash#339]
Hi there

trying to avoid django-leaflet by using dash-leaflet. However, the map does not render when using leaflet components. 

`
import dash_leaflet as dl
from django_plotly_dash import DjangoDash
import dash_html_components as html

url = 'https://tiles.stadiamaps.com/tiles/alidade_smooth_dark/{z}/{x}/{y}{r}.png'
attribution = '&copy; <a href="https://stadiamaps.com/">Stadia Maps</a> '

app = DjangoDash('dash_integration_id')

app.layout = html.Div([html.Div("hi there"),
    dl.Map(dl.TileLayer(url=url, maxZoom=20, attribution=attribution))
], style={'width': '100%', 'height': '50vh', 'margin': "auto", "display": "block", "position": "relative")

if __name__ == '__main__':
    app.run_server(debug=True)`

If you comment out the dl.Map, the hi there shows. 

Tried using dash deck package, and the maps do show, not sure why dash leaflet does not show. Can you please have a look?

Thanks in advance.

**Comment by GibbsConsulting** [comment]
@kirodh are there any error messages or warnings, either from the Django server process (you need to test using Django, not by trying to directly run the app) or the web console?

**Comment by kirodh** [comment]
Hi there

I managed to solve this issue and the map now shows.

There was an error, thanks for pointing me in the right direction. I was using docker and then checked the logs there at run time. Seems like it doesnt find static files (I put the error i got below). I installed the dash-leaflet package. Found out where the files **dash_leaflet.min.js** and **dash_leaflet.dev.js** lies. and copied them to exactly where the error asked for the files to appear : **/staticroot/dash/component/dash_leaflet/dash_leaflet.min.js**. Note that I had to create the **dash_leaflet** folder. I tested a few of the examples in the dash leaflet examples [https://dash-leaflet.herokuapp.com/#us_states](here) and they worked (except the second one where stadiamaps was used as the map tile, that one did not display, but the outer shell for the map and its controls were present).

_nginx_1   | 2021/06/01 13:07:15 [error] 6#6: *12 open() "/staticroot/dash/component/dash_leaflet/dash_leaflet.min.js" failed (2: No such file or directory), client: ..., server: , request: "GET /static/dash/component/dash_leaflet/dash_leaflet.min.js HTTP/1.1", host: "...", referrer: "..."_

**Comment by GibbsConsulting** [comment]
A note for anyone who comes across a similar issue - the [configuration](https://django-plotly-dash.readthedocs.io/en/latest/configuration.html#configuration-options) section of the documentation covers a number of settings, including setting up Django's static file handling to locate files in dash components.
