### ISSUE TITLE
Accessing Initial Data in global data outside of layout and callbacks

### ISSUE THREAD

**Issue by murphej** [GibbsConsulting/django-plotly-dash#344]
Most often in plotly DASH examples, expensive queries are performed only once in the global rather than through a callback. 

If I want to pass only a pk for example to some Django model entry to the initial_data dictionary, and then perform the query upon accessing the dash app. How would I go about accessing the pk outside of the layout and callbacks?

**Comment by GibbsConsulting** [comment]
@murphej as a rule, arrange for the work to be performed elsewhere in Django, and store it somehow, and then pass it to the Dash app instance; it sounds like this is what you're trying to do by mentioning the pk.

One direct approach is to provide the dash app with initial arguments that suffice to locate the results of the work. An example of this is [demo two](https://github.com/GibbsConsulting/django-plotly-dash/blob/master/demo/demo/templates/demo_two.html) in the codebase.

**Comment by nikhilnaregal** [comment]
Can we send multiple initial arguments to one single dash app?

**Comment by GibbsConsulting** [comment]
@nikhilnaregal yes, you can send as many as you want, although a better approach is probably to create a [DashApp](https://django-plotly-dash.readthedocs.io/en/latest/models_and_state.html#the-dashapp-model) model instance in your view, and pass the slug of that to the template. This instance can have as much (or as little) of the dash argument state in as you need.

If you then associate an instance with a user (standard Django ORM relationships etc) then you can just reuse that instance if/when the user returns.

**Comment by murphej** [comment]
@GibbsConsulting Is there any example performing this in practice? It seems like the correct way to go about things, compared to the initial_arguments. 

Is the main data package the base state? - saved as json similar to the initial_arguments?
How would one associate the model instance with the user? - I don't see a FK relationship there.
Can data, e.g. initial dataframe, be passed?
Are the arguments needed to perform an initial query still accessed via hidden fields?

**Comment by nikhilnaregal** [comment]
@GibbsConsulting Can you please show an example for the same??

**Comment by GibbsConsulting** [comment]
The config for the demo includes this [migration](https://github.com/GibbsConsulting/django-plotly-dash/blob/master/django_plotly_dash/migrations/0002_add_examples.py) that creates a number of examples.

@murphej if you want to associate a dash app with a user, just create a new model in Django that links them

**Comment by nikhilnaregal** [comment]
The method which you suggested is a bit confusing for me. Can you please help me to pass multiple initial arguments instead??

in views.py
```
class ABCDetail(DetailView):
    model = ABC
    context_object_name= 'cat' 

    def get_context_data(self, **kwargs):
        context = super( ABCDetail, self).get_context_data(**kwargs)
        context['project_id'] = {'project_id': {'value': '2'}}
        return context
```

In html
`{% plotly_app name='ABC' ratio=0.45 initial_arguments=project_id %}`

Now lets say i want to send other arguments like a=10, b=20 as initial arguments. How do i write "context['project_id'] = {'project_id': {'value': '2'}}" and in html ??

**Comment by GibbsConsulting** [comment]
@nikhilnaregal your initial arguments have to match the component and argument names within your Dash app - these are the pairs passed to `dash.dependencies.Input` and `dash.dependencies.Output` when defining callbacks. You can use (pretty much) any argument to any component.

**Comment by nikhilnaregal** [comment]
You mean
In Views.py
`context['project_id'] = {'project_id': {'value': '2'},'a': {'value': '10'},'b': {'value': '20'}}`

In html
`{% plotly_app name='ABC' ratio=0.45 initial_arguments=project_id %}`

In Dash App
```
app = DjangoDash('ABC',add_bootstrap_links=True , id='project_id')

...
Input("a", "value"),
....
```

**Comment by GibbsConsulting** [comment]
If `project_id`, `a` and `b` are dash components defined in your app's `layout` function, each of which happen to have a `value` property, then that should work.
