### ISSUE TITLE
How to use django models to store input data from dash components to django's database??

### ISSUE THREAD

**Issue by nikhilnaregal** [GibbsConsulting/django-plotly-dash#345]
I have built a dash application and have integrated it into the Django web application. Now i want to save the input data in the database. How do I do it??

**Comment by GibbsConsulting** [comment]
Callbacks run in the same way as any other Django view, so you can just use the ORM. Or you can store values associated with the Dash instance itself, as described in [the documentation](https://django-plotly-dash.readthedocs.io/en/latest/models_and_state.html#django-models-and-application-state)

**Comment by nikhilnaregal** [comment]
Firstly i thank you for your time

below you can find my django files. Please can you tell me how do I store input values for dash components as well as outvalues in django database
-home
--Plotlydashapps
---cbd_app.py
--templates
---base
----cdb.html
--views.py
--urls.py
--admin.py
--models.py

****************************************************************
Dash application in Django folder(cbd_app.py)
```
import dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output
import plotly.graph_objects as go
import dash_daq as daq


text_input1 = dcc.Input(
id='input1',
type="number",
value=1, min=0
),

text_input2 = dcc.Input(
id='input2',
type="number",
value=1, min=0
),

text_input3 = dcc.Input(
id='input3',
type="number",
value=1, min=0
),

text_input4 = dcc.Input(
id='input4',
type="number",
value=1, min=0
),

content= html.Div([
      html.Div([   
          html.Div( "ABC", className="o1a"),
          html.Div( text_input1,className="b1"),),
      html.Div([
      html.Div( text_inpu2,className="b2"),
           html.Div("XYZ",className="o2b"),],className="xyz"),
       html.Div([
          html.Div(text_input3, className="b3"),
          html.Div( "ABC", className="o1a"),),
    html.Div( id='a',className="v1"),
      html.Div( id='b',className="v2"),
], className="grid-container")
from django_plotly_dash import DjangoDash

app = DjangoDash('cbd',add_bootstrap_links=True)

app.css.append_css({ "external_url" : "/static/Styling.css" })


app.layout = html.Div(
    className="app-header",

    children=[
        html.Div([content])
        ]
)


@app.callback(
    [  function
        dash.dependencies.Output('a', 'children'),
        dash.dependencies.Output('b', 'children'),
       
    ],
    [  
        dash.dependencies.Input('input1', 'value'),
        dash.dependencies.Input('input2', 'value'),
        dash.dependencies.Input('input3', 'value'),
        dash.dependencies.Input('input4', 'value'),

     
    ])

def outputTable(value1, value2, value3, value:
   abc=value1*value2
     xyz=value3/value4
     return abc,x
```
****************************************************************
HTML in django (cbd.html)
```
<div class="{% plotly_class name='cbd' %} card" >
  {% plotly_app name='cbd' ratio=0.45 %}
</div>
```

****************************************************************

views in Django(views.py)
```
class CBD(DetailView):
    model = AbcInfo
    context_object_name= 'abc' 
    template_name = "base/cbd.html"

```
****************************************************************
urls.py
```
from django.urls import path, include ,re_path
from django.conf.urls.static import static

from . Plotlydashapps  import cbd_app

from . import views

urlpatterns = [
   re_path(r'home/cb$', CBD.as_view(), name=cb'),

] 
```
****************************************************************

**Comment by GibbsConsulting** [comment]
It depends somewhat on what you're trying to achieve, but in addition to the functionality referenced above you can also import your `models.py` file in your application file, and then manipulate objects during one of your callback functions.

**Comment by nikhilnaregal** [comment]
Thank you, I wanted to also send a primary key value from the URL to callbacks. How can I do that??

**Comment by GibbsConsulting** [comment]
@nikhilnaregal assuming this is a value known during processing of the view that returns a page containing the dash app (eg the CBD view in your code above), then use that value to form [initial_arguments](https://django-plotly-dash.readthedocs.io/en/latest/template_tags.html#the-plotly-app-template-tag) to pass to the `plotly_app` template tag.
