### ISSUE TITLE
Working example to turn stateless app into statefull app?

### ISSUE THREAD

**Issue by sorenwacker** [GibbsConsulting/django-plotly-dash#346]
I cannot find an example for 

https://django-plotly-dash.readthedocs.io/en/latest/models_and_state.html

It seems there are only some boilerplate methods shown and a general outline about what to do. 

Is there a working example somewhere available?

**Comment by GibbsConsulting** [comment]
The [outline](https://django-plotly-dash.readthedocs.io/en/latest/demo_notes.html#session-state-example-walkthrough) in the documentation walks through how demo eight works; the 'dash' part of the code can be found [here](https://github.com/GibbsConsulting/django-plotly-dash/blob/master/demo/demo/bootstrap_app.py).

Feedback on what would help fill in the gaps would be helpful, and any contributions to documentation or code are always most welcome!
