### ISSUE TITLE
Add or extend template to allow more control over window size

### ISSUE THREAD

**Issue by GibbsConsulting** [GibbsConsulting/django-plotly-dash#35]
At present, the ``plotly_app`` tag inserts an iframe that extends to 100% of the width of its parent, and sets its height as some (user controlled) relative fraction of the width.

This needs to be extended (either with more arguments for this tag, or with a different template tag) to allow more user control over the size.

**Comment by Chris3691** [comment]
Is there any update on this one?

I've found that I can tweak the ratio to get the height "right" but when I then looked at the page on a wider screen I ended up with loads of white space below the chart (but within the app frame).

I wonder if combining the ratio with a Max_height may work?

**Comment by GibbsConsulting** [comment]
This one had fallen off the radar. The work needed is to provide an alternative or enhancement to the ``plotly_app`` template, or the [tag](https://github.com/GibbsConsulting/django-plotly-dash/blob/master/django_plotly_dash/templatetags/plotly_dash.py) that calls it.

**Comment by GibbsConsulting** [comment]
Addressed with PR #201 which has been merged into master
