### ISSUE TITLE
"Minified Redux error #14" | Docker stack doesn't work on production. Where should I begin looking? Perhaps nginx?

### ISSUE THREAD

**Issue by afparsons** [GibbsConsulting/django-plotly-dash#355]
Great work and thanks for making this integration available!

My Dash apps display exactly as I expect when I deploy my Docker stack locally. I have two `DjangoDash` apps available at:
- localhost:8001/app1
- localhost:8001/app2

However, when I deploy this same stack to a production server, things go awry for both of these:
- https://our.example.com/dash/app1
- https://our.example.com/dash/app2

I simply see blank pages. If I inspect the page, I can see that all of the HTML elements have loaded. However, I see this in console:

```
dash_renderer.min.js:2 Response is missing header: content-type: application/json
(anonymous) @ dash_renderer.min.js:2

react-dom.production.min.js:125 Error: Minified Redux error #14; visit https://redux.js.org/Errors?code=14 for the full message or use the non-minified dev environment for full errors. 
    at dash_renderer.min.js:2
    at dash_renderer.min.js:2
    at dash_renderer.min.js:2
    at p (dash_renderer.min.js:2)
    at dash_renderer.min.js:2
    at ts (dash_renderer.min.js:2)
    at Bh (react-dom.production.min.js:126)
    at Dj (react-dom.production.min.js:162)
    at unstable_runWithPriority (react.production.min.js:25)
    at Da (react-dom.production.min.js:60)
Me @ react-dom.production.min.js:125

react.production.min.js:24 Uncaught Error: Minified Redux error #14; visit https://redux.js.org/Errors?code=14 for the full message or use the non-minified dev environment for full errors. 
    at dash_renderer.min.js:2
    at dash_renderer.min.js:2
    at dash_renderer.min.js:2
    at p (dash_renderer.min.js:2)
    at dash_renderer.min.js:2
    at ts (dash_renderer.min.js:2)
    at Bh (react-dom.production.min.js:126)
    at Dj (react-dom.production.min.js:162)
    at unstable_runWithPriority (react.production.min.js:25)
    at Da (react-dom.production.min.js:60)
```

"Error 14" notes the following:
> When called with an action of type , the slice reducer for key "" returned undefined. To ignore an action, you must explicitly return the previous state. If you want this reducer to hold no value, you can return null instead of undefined.

I know nearly nothing about the JavaScript world (hence why I'm cobbling together some dashboard components in _Python_ -- I'm simply trying to see visualize some backend data) so I can't really parse the error.

Here is the entrypoint from the docker-compose.yml file:
```yml
...
    entrypoint:
      - gunicorn
      - my_django_application_name.asgi:application
      - --bind
      - "0.0.0.0:8001"
      - --workers
      - "2"
      - -k
      - uvicorn.workers.UvicornWorker
...
```

The only difference between my local environment and the production server is that there is an nginx reverse proxy mapping port 8001 to `/dash/`.

I do not require live state, and so I have the simplest of setups. That is, I did not set up channels, Redis, etc.

Questions:
- does anyone understand the error I see?
- what information can I provide to be most helpful? I didn't want to fill this initial post with useless log outputs.

Thanks in advance!

**Comment by GibbsConsulting** [comment]
@afparsons if it works using the local development server, but not in a production configuration behind a proxy, then the issue is probably one of static files configuration. By default, Django doesn't serve them except in the local development server.

The [Django documentation](https://docs.djangoproject.com/en/3.2/howto/static-files/deployment/) covers this for Django itself, and there are `django-plotly-dash` specific notes [here](https://django-plotly-dash.readthedocs.io/en/latest/configuration.html#configuration-options)

**Comment by leolamoureux** [comment]
I encounter exactly the same error using a flask server with my Dash app. Can someone help me ? Thanks in advance !
