### ISSUE TITLE
Integrated dash-app does not get enough space

### ISSUE THREAD

**Issue by Noskario** [GibbsConsulting/django-plotly-dash#366]
I am integrating a dash-app into django for the first time using `django_plotly_dash`.

I think I am doing it the standard way:

`urls.py`
```
from django.urls import path, include
from . import views

urlpatterns = [
    path('trial',views.trial,name='trial'),
]
```

`views.py`
```
from django.shortcuts import render
from django.http import HttpResponse
import my_first_dash_plotly_app.simple_dash_app
def trial(request):
    return render(request, 'my_first_dash_plotly_app/trial.html')
```

`simple_dash_app.py`
```
import dash_core_components as dcc
import dash_html_components as html
import plotly.express as px
import pandas as pd
from django_plotly_dash import DjangoDash



# assume you have a "long-form" data frame
# see https://plotly.com/python/px-arguments/ for more options
df = pd.DataFrame({
    "Fruit": ["Apples", "Oranges", "Bananas", "Apples", "Oranges", "Bananas"],
    "Amount": [4, 1, 2, 2, 4, 5],
    "City": ["SF", "SF", "SF", "Montreal", "Montreal", "Montreal"]
})

fig = px.bar(df, x="Fruit", y="Amount", color="City", barmode="group")

app = DjangoDash('SimpleExample1')
app.layout = html.Div( children=[
    dcc.Graph(
        id='example-graph-2',
        figure=fig
    )
])


```

`trial.html`
```
{%load plotly_dash%}

{%plotly_app name="SimpleExample1"%}
```

This is just the standard-example from the plotly/dash-introduction.

It works somehow but looks really ugly. You have to scroll to see the plot completely.
[![cut off plot where you to scroll to see it completely][1]][1]

Is there an easy fix? 
In case this is indeed the default and I am not doing something completely wrong: I think this behaviour should not be default; the default should be that each graph gets the size it needs.

EDIT: After having played around in Firefox a bit I found that the problem is the `height: 0;`
![django-plotly-dash-inspected](https://user-images.githubusercontent.com/83504577/141835060-3ea5b475-b83a-42e5-a76b-ab3ab6ceae0e.png)
But I still do not know how to change the missbehaviour in django...

  [1]: https://i.stack.imgur.com/VDH4O.png

**Comment by GibbsConsulting** [comment]
The [template tags](https://django-plotly-dash.readthedocs.io/en/latest/template_tags.html#template-tags) section describes the template tags - you will almost certainly have to choose the size or aspect ratio of something within your layout.
