### ISSUE TITLE
Bug or I'am stupid?

### ISSUE THREAD

**Issue by Nizhurin** [GibbsConsulting/django-plotly-dash#367]
Hey guys!

My problem is quite simple: I want to pass user information from the view to the dash application so i can load the respective user data from my model into the dashboard.

I have read about the extended callback functionality that would allow me to access request and user information from within the callbacks via the **kwargs argument.

The way i understand this that i simply need to add the *kwargs argument to the callback. I did this and also tried the expanded_callback instead. However, the kwargs argument is always empty.

I am using dash 2.0.0 and django-plotly-dash 1.6.5.
(When am using old dash 1.21 and django-plotly-dash 1.6.5  kwargs  is printing)

@app.callback(Output('table_charts', 'children'),
[Input('table_charts', 'children'),
Input('interval-component', 'n_intervals')])
def get_table_charts(vv, vv2, **kwargs):
if kwargs == {}:
return
else:
print(kwargs)
user = kwargs['user']
user_role = kwargs['session_state']['user_role']

Output

None
{}

What am i missing?
Thanks!

**Comment by GibbsConsulting** [comment]
You need to use an older version of dash. The version of `django-plotly-dash` that you're using doesn't correctly restrict this.
If you upgrade to v1.6.6 (the current version as of late Nov 2021) then it will require dash < 1.21

**Comment by Nizhurin** [comment]
> You need to use an older version of dash. The version of `django-plotly-dash` that you're using doesn't correctly restrict this. If you upgrade to v1.6.6 (the current version as of late Nov 2021) then it will require dash < 1.21

Thank, you

**Comment by KuechlerO** [comment]
Wow, that took me a long time to figure out.

@GibbsConsulting Are you planning to establish also further version with support of higher Dash-versions?
