### ISSUE TITLE
in pypi package: static folder missing

### ISSUE THREAD

**Issue by thelittlebug** [GibbsConsulting/django-plotly-dash#368]
i think thats the reason why my browser is not able to find websocketbridge.js

![image](https://user-images.githubusercontent.com/2874956/144436952-6157e525-7cad-4a91-8e4f-c111dc6a3557.png)

**Comment by GibbsConsulting** [comment]
Yes, it used to be part of channels but got removed, and it looks like it is not actually included in our setup/packaging script at the moment (created #369 to remedy this).

Workaround is to grab the file from github and stick it in the right place in one of the static folders of the project, or to use an earlier version of channels prior to its removal.

**Comment by GibbsConsulting** [comment]
This was addressed by #387
