### ISSUE TITLE
Passing local css to Dash when serve_locally=True

### ISSUE THREAD

**Issue by eddy-ojb** [GibbsConsulting/django-plotly-dash#37]
If defining an app with `serve_locally=True`, is there a way to pass locally served css?

```
Dash_app1 = DjangoDash(name='Dash_app1', serve_locally=True, add_bootstrap_links=True)

# and optionally passing some other css
Dash_app1.css.append_css({'external_url': 'http://127.0.0.1:8000/static/demoapp/css/demoapp.css'})
```

This results in errors from Dash such as:

`A local version of ['https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css'] is not available`

I suspect this is a result of the latest version of Dash.

**Comment by eddy-ojb** [comment]
Should add versions: 

```
dash==0.24.0
dash-core-components==0.27.1
dash-html-components==0.11.0
dash-renderer==0.13.0
django-plotly-dash==0.7.0
dpd-components==0.1.0
flask==1.0.2
```

**Comment by GibbsConsulting** [comment]
At the moment, ``serve_locally`` unfortunately doesn't do what one might want - any ``external_url`` entry is suppressed. This happens inside the Dash code, so from this perspective dpd is just following Dash.

As part of the work to not always use an iframe, we're moving towards using the recent Dash functionality that provides for the overall application to be specified in a template. Once that is bedded down, resolving this issue should be straightforward. Until then I fear the closest we have to a workaround is to not serve locally.

**Comment by eddy-ojb** [comment]
Sounds decent. Just as i was getting used to iframes as well :)

An alternative might be to serve the css by inserting a css link in to the iframe from the parent django template with JS.

https://stackoverflow.com/questions/217776/how-to-apply-css-to-iframe

**Comment by GibbsConsulting** [comment]
#133 should now permit this - `serve_locally` is now a global configuration variable
