### ISSUE TITLE
How do we adjust the ratio of the app to different screen sizes?

### ISSUE THREAD

**Issue by jhug12** [GibbsConsulting/django-plotly-dash#370]
I am using plotly_app tag as I need to pass initial arguments so Plotly direct tag is not a option for me.
Right now the are two scroll bars coexisting depending on the screen size.

**Comment by GibbsConsulting** [comment]
There is the [ratio](https://django-plotly-dash.readthedocs.io/en/latest/template_tags.html) argument to the template tag and also the `plotly_app_bootstrap` variant that allows you to supply the ratio in a form such as "4by3" as provided by bootstrap.

Note that width is inherited from the parent.

**Comment by jhug12** [comment]
Thank you for the response. I used the bootstrap variant but now the size is very small and I don't know how to fix this. There is a screenshot for better understanding

This is the code:
<div class="content_abc_analysis">
    <div class="{% plotly_class name='abc_analysis_dash' %} card">
        {% plotly_app_bootstrap name='abc_analysis_dash' aspect="16by9" initial_arguments=Abc_stored_values %}
    </div>
</div>

<img width="1787" alt="Screenshot 2021-12-13 at 11 21 05" src="https://user-images.githubusercontent.com/87663078/145795503-2ae030ef-7d27-4c9e-9b82-59fb8edb4571.png">

**Comment by GibbsConsulting** [comment]
The dash app inherits its width from its parent - this is why only the ratio is set in the template tag - so you should fix the width of the parent element somehow. The examples use bootstrap cards, for example.

**Comment by TheBubblePopped** [comment]
I have the same problem but the only thing i am using is:

```

{%load plotly_dash%}

{%plotly_app_bootstrap name="SimpleExample2"%}

```

yet it looks like [that](https://imgur.com/a/MfPPY8i)..Any clue @GibbsConsulting ?

**Comment by GibbsConsulting** [comment]
As per above - the width is inherited from the parent, which means it comes from your template. I find that using the developer tools within the browser is a good way to work out what is driving things when trying to chase down layout issues.

Another trick is to temporarily replace the plotly_app template tag(s) with a different html component; this can help in diagnosing things.
