### ISSUE TITLE
[FR]: Add scrolling arg to `plotly_app` iframe

### ISSUE THREAD

**Issue by JulianOrteil** [GibbsConsulting/django-plotly-dash#372]
For my application, the `ratio` option does not quite size the iframe around my graph correctly and leaves extra bottom margin. Setting the ratio to match what I need causes the scrollbar to display which is even worse. I believe adding a `scrolling` argument to `plotly_app` would be the best approach (note `scrolling` is a valid property of `iframe`). The default value for this arg would be "auto".

Mimicking the implementation of the `frameborder` property would be ideal:
`{% plotly_app name="SimpleExample" scrolling="no" %}`

Thanks,
Jules

**Comment by Harizliewzw** [comment]
How did you solve this?
