### ISSUE TITLE
`serve_locally=True` produces 404

### ISSUE THREAD

**Issue by JulianOrteil** [GibbsConsulting/django-plotly-dash#375]
Good day, I would like to preface my issue with thanking you and each contributor for the amazing work done in this library. It has accelerated the development of my application immensely while removing the complexity I was expecting, so thank you.

**The Issue:**
Onto the issue. I am building a statistics dashboard that will display a variety of different data collected by some Arduino devices I have (things like humidity, temperature, etc). This server and the client will be in a static IP range that will not have access to the internet, hence my need for `serve_locally=True`. Anyways, the issue I am running into seems to be fairly common considering the amount of issues searching `serve_locally=True` here produces (especially #267). And, as with the others, keeping `serve_locally=False` works just fine.

With that being said, following the directions given by @GibbsConsulting virtually to the letter in #267 and others has still not resulted in an optimal outcome. I have yet to deploy this server in a production environment, so my entire issue revolves around a `DEBUG=True` environment (I plan to run an NGINX + Guvicorn + Redis setup for production; so perhaps this may disappear with that setup?).

**The Code:**
Here is the current relevant code:

[settings.txt](https://github.com/GibbsConsulting/django-plotly-dash/files/7831785/settings.txt)
[server-output.txt](https://github.com/GibbsConsulting/django-plotly-dash/files/7831793/server-output.txt)

**Project Structure:**
![image](https://user-images.githubusercontent.com/23083317/148619376-3999557d-b136-4bd2-827b-f58c11d06819.png)

**The Environment:**
Because I am running AJAX requests separate from Dash, the server is running as ASGI.

`pip freeze:` (Note: some if not many of these I do not use directly)
```
aiohttp==3.8.1
aioredis==1.3.1
aiosignal==1.2.0
alabaster==0.7.12
appdirs==1.4.4
asgiref==3.4.1
async-timeout==4.0.1
attrs @ file:///tmp/build/80754af9/attrs_1620827162558/work
autobahn==21.11.1
Automat==20.2.0
Babel==2.9.1
Brotli==1.0.9
certifi==2021.10.8
cffi==1.15.0
cfgv==3.3.1
channels==3.0.4
channels-redis==3.3.1
charset-normalizer==2.0.9
click==8.0.3
colorama==0.4.4
constantly==15.1.0
coverage @ file:///tmp/build/80754af9/coverage_1614614861224/work
crispy-bootstrap5==0.6
cryptography==36.0.0
daphne==3.0.2
dash==2.0.0
dash-bootstrap-components==1.0.2
dash-core-components==2.0.0
dash-html-components==2.0.0
dash-renderer==1.9.1
dash-table==5.0.0
Deprecated==1.2.13
distlib @ file:///tmp/build/80754af9/distlib_1622544193819/work
Django==4.0
django-async-orm==0.1.8.1
django-crispy-forms==1.13.0
django-ordered-model==3.4.3
django-plotly-dash==1.6.6
django-polymorphic==3.1.0
django-redis==5.2.0
dnspython==2.1.0
docopt==0.6.2
docutils==0.17.1
dpd-components==0.1.0
dpd-static-support==0.0.5
fett==0.3.2
filelock @ file:///tmp/build/80754af9/filelock_1638521398314/work
Flask==2.0.2
Flask-Compress==1.10.1
frozenlist==1.2.0
future==0.18.2
hiredis==2.0.0
hyperlink==21.0.0
identify==2.4.0
idna==3.3
imagesize==1.3.0
importlib-metadata==4.8.2
incremental==21.3.0
iniconfig @ file:///home/linux1/recipes/ci/iniconfig_1610983019677/work
itsdangerous==2.0.1
jeepney==0.7.1
Jinja2==3.0.3
keyring==23.4.0
livereload==2.6.3
loguru==0.5.3
MarkupSafe==2.0.1
msgpack==1.0.3
mssql-django==1.1.1
multidict==5.2.0
mypy-extensions==0.4.3
networkx==2.6.3
nodeenv==1.6.0
numpy==1.21.5
packaging @ file:///tmp/build/80754af9/packaging_1637314298585/work
pandas==1.3.5
pathspec==0.9.0
platformdirs==2.4.0
plotly==5.4.0
pluggy @ file:///tmp/build/80754af9/pluggy_1633715208724/work
pre-commit==2.16.0
py @ file:///tmp/build/80754af9/py_1607971587848/work
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
Pygments==2.10.0
pymongo==3.12.3
pyodbc==4.0.32
pyOpenSSL==21.0.0
pyparsing @ file:///tmp/build/80754af9/pyparsing_1635766073266/work
pytest==6.2.5
pytest-cov @ file:///tmp/build/80754af9/pytest-cov_1637159997573/work
python-dateutil==2.8.2
python-jsonrpc-server==0.3.4
pytz==2021.3
PyYAML==5.4.1
redis==4.1.0
requests==2.26.0
rstcheck==3.3.1
SecretStorage==3.3.1
service-identity==21.1.0
six @ file:///tmp/build/80754af9/six_1623709665295/work
snooty-lextudio==1.11.5
snowballstemmer==2.2.0
Sphinx==4.3.1
sphinx-autobuild==2021.3.14
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
sqlparse==0.4.2
tenacity==8.0.1
toml @ file:///tmp/build/80754af9/toml_1616166611790/work
tomli==1.2.3
tornado==6.1
Twisted==21.7.0
txaio==21.2.1
typing_extensions==4.0.1
ujson==1.35
urllib3==1.26.7
virtualenv @ file:///tmp/build/80754af9/virtualenv_1620977681177/work
watchdog==1.0.2
Werkzeug==2.0.2
whitenoise==5.3.0
wrapt==1.13.3
yarl==1.7.2
zipp==3.6.0
zope.interface==5.4.0
```

Please let me know if I have something misconfigured (most likely) or if you need any further information. I can share pretty much anything, but there are exceptions of course.

Thanks for your time,
Jules

**Comment by GibbsConsulting** [comment]
@JulianOrteil you are running dash version 2.0, which is not supported. Did you get some sort of error or warning during installation of either dash or django-plotly-dash about version conflicts?

Version incompatibility might be the cause, but at the very least we should deal with it first.

What request is generating a 404 error?

**Comment by JulianOrteil** [comment]
> @JulianOrteil you are running dash version 2.0, which is not supported. Did you get some sort of error or warning during installation of either dash or django-plotly-dash about version conflicts?
> 
> Version incompatibility might be the cause, but at the very least we should deal with it first.

@GibbsConsulting Version incompatibility was indeed the issue, everything is working as expected now, thank you.

To answer your questions: I do not recall if I did or not. However, reinstalling `django-plotly-dash` shows the following error from `pip`:
![image](https://user-images.githubusercontent.com/23083317/148784608-f5a5c128-e074-4c35-a131-5f878775cd2e.png)

`dash 1.20.0` doesn't appear to be causing an issue for `django-bootstrap-components` as everything is displaying as expected, but it might throw someone else off regardless. I believe I got myself into this spot because of that error message and because I didn't see any notice of it in your documentation regarding `django-bootstrap-components`.

Perhaps a band-aid approach to fix this is to have `dpd` import dash, check dash's version and raise an ImportError if it is 2.0? Then mention [here](https://django-plotly-dash.readthedocs.io/en/latest/bootstrap.html) that using `dash<2.0` is okay?

> What request is generating a 404 error?

If you look in my issue description (under **The Code**), I provide the server output for most, if not all, files that report 404. All of my static files and those auto-generated by `collectstatic` are found, just not the ones in that file (I believe they all relate to this library).

**Comment by JulianOrteil** [comment]
@GibbsConsulting After a little bit more tinkering, I am happy to report that pip does show an error for dash>=2.0 when attempting to install it.

![image](https://user-images.githubusercontent.com/23083317/149213628-d2639ae8-57ad-4a3f-8405-1105a411c111.png)

However, as this is most definitely not something you can control, pip does install 2.0 even with the error. But, as I said above, a possible band-aid for issues that revolve around dash 2.0 would be to have dpd import dash and raise an `ImportError` if the version is incompatible.
