### ISSUE TITLE
ImportError: cannot import name 'get_current_traceback' from 'werkzeug.debug.tbtools'

### ISSUE THREAD

**Issue by gdalmau** [GibbsConsulting/django-plotly-dash#393]
# Issue

Related issue https://github.com/plotly/dash/issues/1992

This issue was fixed in [dash v2.3.1](https://github.com/plotly/dash/releases/tag/v2.3.1), but since django-plotly-dash still doesn't support dash>=2.0 this fix doesn't apply.

## Workaround

Add `Werkzeug>=2.0,<2.1` in the requirements.

**Comment by GibbsConsulting** [comment]
This workaround has been released as v1.7.1

**Comment by gdalmau** [comment]
@GibbsConsulting This is still not fixed. The workaround implemented in https://github.com/GibbsConsulting/django-plotly-dash/pull/399 changes the `requirements.txt` but the `setup.py` does not make use of this file, so it needs to be changed there. Can you reopen this issue?

**Comment by delsim** [comment]
Ah, thats unfortunate. Thanks for reporting

**Comment by GibbsConsulting** [comment]
PR #400 should fix this.
