### ISSUE TITLE
Compatibility with dash_extensions

### ISSUE THREAD

**Issue by sambaPython24** [GibbsConsulting/django-plotly-dash#395]
Hey, for my app, I am using the ```MultiplexerTransform``` in a ```DashProxy``` app. This gives you the chance to connect the same output to multiple outputs.
You use it by exchanging the initial 
```app = dash.Dash(...)``` by ```app = DashProxy(..., transforms = [MultiplexerTransform()])```

When I exchange ```app``` by ```app = DjangoDash(...)```, is there a way to still use the the ```dash_extensions```?

**Comment by GibbsConsulting** [comment]
This is the proxy from [dash-extensions](https://pypi.org/project/dash-extensions/)? If so then it looks like both work the same way - by internally wrapping around a Dash instance - and so they probably don't work directly together at the moment.
 
However, the multiplexer transform means that the app will somehow pick the result (randomly, presumably) from multiple callbacks for a single output. Is it not possible to simply write a single callback for that output instead?

**Comment by sambaPython24** [comment]
Hey, thank you very much for the work that you put into this project and your support here! 
If you are interested in the discussion, [this](https://community.plotly.com/t/multiple-callbacks-for-an-output/51247/20) would the link and the information, how multiple input callbacks can target the same ouput.
In the discussion, it is suggested to create a workaround with a _combined callback_. 

Maybe dash_extensions will be integrated into dash anyway, but so long it would simplify callbacks if you could open e.g. a material drawer from different buttons.

**Comment by GibbsConsulting** [comment]
I wouldnt call writing a single callback a workaround - rather, it is a bugfix!

If you try to use multiple callbacks, then you have no control over the order in which the results are applied. It is a common error - one that is easily hidden in a toy test server - to assume that callbacks return results in the order in which they are invoked from the frontend.

**Comment by sambaPython24** [comment]
Ok, using the ```MATCH``` and ```ALL``` logic from dash, the app can work as a ```dash.Dash``` app and does not need. 
```dash.DashProxy``` anymore. Unfortunately, the app (after a _Loading_ sign), is displayed as a white space (The ```SimpleExample``` app given in this repository still works.) 

Is django-plotly-dash not compatible with the ```MATCH```, ```ALL``` logic or what could be the problem?

**Comment by GibbsConsulting** [comment]
@sambaPython24 that's a different issue. First check that your app works with callbacks that don't use either `MATCH` or `ALL` and if need be create a new issue.
