### ISSUE TITLE
Enable use of Django 4.0 and higher

### ISSUE THREAD

**Issue by delsim** [GibbsConsulting/django-plotly-dash#403]
Changes in Django for major version 4 need to be accommodated in Dash. This is a placeholder for this work.

**Comment by mhostn3** [comment]
Hello Guys, does django-plotly-dash work with 4.1 Django?

**Comment by TheVinhLuong102** [comment]
hi everyone, may I also enquire if Django 4 support is coming soon?

**Comment by radusuciu** [comment]
I have not yet tried to migrate to 4.0 with a project that depends on django-plotly-dash. Are there many outstanding issues that would prevent support for django 4.0?

**Comment by dcontador** [comment]
I've been using django-plotly-dash in my Django 4.1 project unmodified, just not installing bat copying the source in my project tree. The functions I have tested (only stateless apps at the moment) have been working so far.

**Comment by radusuciu** [comment]
I've created a PR for this: https://github.com/GibbsConsulting/django-plotly-dash/pull/448

**Comment by mhostn3** [comment]
Just to inform you if someone had the same doubt.
I have just upgraded the Django version to 4.2. 
I have got this message (see image), but django-plotly-dash seems to work properly so far.
![django4 2](https://user-images.githubusercontent.com/107844961/231123264-a791d54b-cfc7-4d5c-af52-23793d1450dd.PNG)

**Comment by alejoar** [comment]
So is this abandoned?

**Comment by pcanas** [comment]
I am also interested in this!

**Comment by delsim** [comment]
See PR #455 which builds on the work of @radusuciu in #448

**Comment by GibbsConsulting** [comment]
v2.2.0 has now been released which extends coverage to Django versions 4.x
Please do test and use; any issues should be reported as new issues in this repository
