### ISSUE TITLE
Allow JSON encoder to be set

### ISSUE THREAD

**Issue by GibbsConsulting** [GibbsConsulting/django-plotly-dash#405]
The JSON encoder used to send responses (`plotly.utils.PlotlyJSONEncoder`) does not currently permit the use of lazy string evaluation in Django, such as for translation of messages, as described in #404 

The code in `dash_wrapper.py` needs to use something derived from this encoder that also can leverage the Django lazy text methods.

**Comment by delsim** [comment]
See PR #408

**Comment by GibbsConsulting** [comment]
Now addressed in v2.1.0
