### ISSUE TITLE
Silent failure when adding certain callbacks

### ISSUE THREAD

**Issue by VitalyArtemiev** [GibbsConsulting/django-plotly-dash#409]
I have just started working with plotly-dash, so forgive me if I am totally misunderstanding something, but how is it possible that adding a callback to an element in an app can break another callback without any error output? The worst part is, it only happens sometimes and I can't see the rhyme or reason behind it. Originally I was trying to do two unrelated callbacks, but I've even tried two identical callbacks with just function name changed (see example below). How can I debug this? How do I avoid this type of error in the future?

Steps to reproduce:
1) git clone https://github.com/GibbsConsulting/django-plotly-dash.git 
2) ./django-plotly-dash/make_env && source django-plotly-dash/env/bin/activate
3) cd django-plotly-dash/demo/demo
4) nano dash_apps.py
5) add following code:

```
import json

from dash import dash_table, dcc, html
from dash.dependencies import Input, Output, State
from django_plotly_dash import DjangoDash

app = DjangoDash("Testapp")


app.layout = html.Div(
    [
        dash_table.DataTable(
            id="format-table",
            columns=[
                {"id": "param-name"},
                {"id": "param-type"},
                {"id": "param-unit"},
            ],
            editable=True,
            data=[{"param-name": "", "param-type": "", "param-unit": ""}],
        ),
        html.Button("Add parameter", id="add-row-btn", n_clicks=0),
    ]
)

@app.callback(
    Output("format-table", "data"),
    Input("add-row-btn", "n_clicks"),
    State("format-table", "data"),
    State("format-table", "columns"),
)
def add_row(n_clicks, rows, columns):
    if n_clicks > 0:
        rows.append({c["id"]: "" for c in columns})
    return rows


@app.callback(
    Output("format-table", "data"),
    Input("add-row-btn", "n_clicks"),
    State("format-table", "data"),
    State("format-table", "columns"),
)
def add_row1(n_clicks, rows, columns):
    if n_clicks > 0:
        rows.append({c["id"]: "" for c in columns})
    return rows
```

6) in templates/demo_one.html change app name to "Testapp"
7) python3 manage.py runserver
8) go to http://localhost:8000/demo-one and observe how none of the callbacks are working
9) in dash_apps.py remove the last callback and observe how now the other one is working

**Comment by delsim** [comment]
@VitalyArtemiev In this example, both outputs are to the same element in the dashboard. Does the issue go away if you change one of them to a different table?

**Comment by joshuanunn** [comment]
@VitalyArtemiev - in relation to your question on debugging these sorts of things, and further to the reply from @delsim -- provided it is duplicate callbacks, you would be able to see this in the browser console (e.g. Ctrl-shift-I in Chrome, and click Console).

There should be an error relating to this in the console. If you remove the duplicate callbacks, this error should disappear. You wouldn't see this in the Django server output, which can be confusing.

**Comment by delsim** [comment]
I can replicate the behaviour with two callbacks specifying the same output - the functions register fine with neither Dash or dpd complaining, and then there is an error in the browser console when the front end tries to find a callback to invoke.

Ideally an error would be raised on registration, but that is not the case at the moment.

**Comment by VitalyArtemiev** [comment]
Thanks for your reply.
