### ISSUE TITLE
Extend iframe sandbox permissions and consolidate in a single place

### ISSUE THREAD

**Issue by GibbsConsulting** [GibbsConsulting/django-plotly-dash#412]
The needed list of sandbox permissions for iframes is continually expanding; #411 is the most recent example.

The permissions themselves should be in a single place - and perhaps configurable for anyone who wishes to adjust them - and then used in each template as needed.

**Comment by NickThorne123** [comment]
Also needs **allow-modals** for [dash.ConfirmDialog](https://dash.plotly.com/dash-core-components/confirmdialog)

**Comment by GibbsConsulting** [comment]
This is addressed in v2.1.0
