### ISSUE TITLE
Use Dash Mantine Components with django_plotly_dash

### ISSUE THREAD

**Issue by starsidechimp** [GibbsConsulting/django-plotly-dash#418]
If I use any Dash Mantine Components within my Dash application, it just displays as a large blank page when using dpd, but it loads just fine with the standard dash application. Looking at previous questions, it sounded like custom components should work with dpd. Am I missing a step to use other libraries with this?

**Comment by delsim** [comment]
@starsidechimp custom components indeed should work, but sometimes the path is not completely smooth. There are three ways to get more information about what is going on:
- run Django from the debug console and see if there are any error messages generated when rendering the dpd-containing view
- at the same time, in the browser development tools view the console log and look for messages, particularly errors or warnings
- also in the developer tools, view the network log/tab and look for missing (404) files

If you're able to report on these three points that would be most helpful!

**Comment by GibbsConsulting** [comment]
@starsidechimp when I use dash-mantine-components I get the expected behaviour, ie the components are displayed. I'm going to close this issue - if you still have problems then please open a new one, with some more detail as described above.
