### ISSUE TITLE
Crashing if orjson is installed

### ISSUE THREAD

**Issue by mfriedy** [GibbsConsulting/django-plotly-dash#421]
Hi,

There seems to be an issue in [PR#408](https://github.com/GibbsConsulting/django-plotly-dash/pull/408/files )

In _patches.py 
we have:
```from plotly.io._json import config```

but then later in the code

``` JsonConfig.validate_orjson()```

Which throws an error that JsonConfig doesn't exist

Looking at the plotly code, of course config = JsonConfig...

**Comment by GibbsConsulting** [comment]
Should be resolved as #427 and #428 are now merged and part of the 2.1.2 release
