### ISSUE TITLE
Updates to the dependencies haven't propagated to pypi

### ISSUE THREAD

**Issue by AdrianUlrich** [GibbsConsulting/django-plotly-dash#424]
Hi there,
It seems there is an issue with the pypi manifest (?)

The changes for tag v2.1.0 ( 14be68ade2618595bcef123f91a0f0e92d8bef4bc ) inlcuded "Relax historical constraints" #413 but it seems the dependency changes weren't translated to the setup.py

Straight from the pypi [json ](https://pypi.org/pypi/django-plotly-dash/json):
![image](https://user-images.githubusercontent.com/37381718/200354855-d9452577-3277-4912-ae3f-e7bb8e8355af.png)

> 42       "dash-bootstrap-components (<1)",

This doesn't reflect the changes made in 2.1.0,  unless I'm missing something
(should be:)

> 42       "dash-bootstrap-components",

**Comment by GibbsConsulting** [comment]
@AdrianUlrich thanks for reporting

Until a fix is pushed out, the workaround is to just update the packages by hand, if needed - although messing with dependencies can be a fast way of getting into a mess, so it is probably not something to do unless absolutely necessary

**Comment by GibbsConsulting** [comment]
Should be fixed by the v2.1.1 release
