### ISSUE TITLE
Bypass database calls during callback

### ISSUE THREAD

**Issue by bkolsrud-apr** [GibbsConsulting/django-plotly-dash#438]
Some of my seemingly simple callbacks take more time than I would expect.

For example, a simplified single callback1 below takes about 500ms to complete on my local machine:
```
app = DjangoDash('lightning', external_stylesheets=['https://codepen.io/chriddyp/pen/bWLwgP.css'])
app.layout = html.Div([
    dcc.Input(
        id='x0',
        type='number',
        value=0
    ),
    html.Table([
        html.Tr([html.Td(['x+1']), html.Td(id='x1')]),
    ]),
])

@app.callback(
    Output('x1', 'children'),
    Input('x0', 'value')
)
def callback1(x):
    return x+1
```
I ran cProfile on the code and it's showing the biggest time contributors are related to psycopg2.  This suggests to me the callback is interacting with our postgresql database but I'm not sure why.  Is that a correct interpretation?  If so, is there a way to bypass or tell a callback "this one doesn't need the db", ideally without going to clientside callbacks?
```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        4    0.998    0.249    0.998    0.249 {built-in method psycopg2._psycopg._connect}
       12    0.529    0.044    0.529    0.044 {method 'execute' of 'psycopg2.extensions.cursor' objects}
        4    0.135    0.034    0.135    0.034 {method 'commit' of 'psycopg2.extensions.connection' objects}
        4    0.001    0.000    0.001    0.000 {method 'close' of 'psycopg2.extensions.connection' objects}
```

**Comment by delsim** [comment]
@bkolsrud-apr this does seem rather high. It looks like the time is being spent setting up connections to the database. In general this is something that is pooled and not done per request.

This is likely to be caused by your overall Django configuration. A search along the lines of 'DJango new database connection per request' generates a lot of material.

Out of interest, what is your runtime configuration? In particular what are you using to run Django and what version of the various components and packages, particularly Django, are you using?

Note that performance measurements using the built-in development server are essentially meaningless as that environment is significantly different from any production one. It does a lot of extra work each request, such as spawning new threads and creating new database connections.

**Comment by bkolsrud-apr** [comment]
Thanks for the quick feedback.

Great point regarding the development server.  I was, in fact, running the dev server on my local laptop while connected to our database hosted on AWS.  Running the dash app from our AWS deployment on Elastic Beanstalk does show much better performance - roughly 70ms per callback.  The limiting factor still appears to be db related with a new line item {method 'get' of '_queue.SimpleQueue' objects} as well as the earlier-listed psycopg methods.

I appreciate the hint regarding 'new db connection per request'.  I will have to look into that some more.  I thought adjusting the "CONN_MAX_AGE" might help, but didn't observe any improvement.

I think the 70ms per callback should be adequate for our application in production so long as we keep the total number of (serial) callbacks down.  I'll keep in mind the db hit when it comes to architecture going forward - if serial callbacks can be combined, I will try to do so.  That is, unless you know of a clever way to combine a sequence of callbacks into a single request 'on-the-fly'.

Relevant package versions:
```
dash==2.6.1
dash-daq==0.5.0
dash-bootstrap-components==1.2.1
dash-core-components==2.0.0
dash-html-components==2.0.0
dash-table==5.0.0
django==3.2
django-plotly-dash==2.1.3
django-storages==1.13.1
dpd-components==0.1.0
flask==2.1.3
flask-compress==1.13
importlib-metadata==5.0.0
itsdangerous==2.1.2
jinja2==3.1.2
plotly==5.11.0
psycopg2-binary==2.9.4
sqlparse==0.4.3
tenacity==8.1.0
werkzeug==2.0.3
```

**Comment by bkolsrud-apr** [comment]
I consider this closed.  Issues were mainly related to running with the development server.  Architecturally, anything that doesn't need the db or python could be converted to a client-side callback anyway.
