### ISSUE TITLE
TypeError: i[v][g] is undefined

### ISSUE THREAD

**Issue by zepp133** [GibbsConsulting/django-plotly-dash#451]
I'm currently trying to integrate a functioning stand-alone Dash app into a Django app. I've copied the code over from the stand-alone codebase without any changes to the Dash code.

Now when I try to include the Dash dashboard with the `plotly_direct` tag, I'm getting a rather cryptic error message in my browser when trying to load the dashboard locally:

```
TypeError: i[v][g] is undefined [dash_renderer.min.js:2:94855]
```

I'd appreciate if anybody could point me towards a solution. Thanks :pray:

**Comment by delsim** [comment]
@zepp133 you will have to share a bit more information about what you have (and have not) done. As a first step, what exactly does 'without any changes' mean? Have you for example changed the app constructor from `Dash` to `DjangoDash`?
