### ISSUE TITLE
Integration of Custom Dash Components with DPD

### ISSUE THREAD

**Issue by eddy-ojb** [GibbsConsulting/django-plotly-dash#46]
I am looking to build a custom [popover component](https://reactstrap.github.io/components/popovers/) for Dash. Not all users understand graphs and I think descriptions in popover buttons near graphs will help users understand whats going on without cluttering a UI.

This will take me a while given my inexperience with React.js but before I start this, do you expect custom Dash components to play nicely with dpd? Are there any broad considerations I should be aware of?

**Comment by GibbsConsulting** [comment]
Components should play nicely, in the sense that I don't think anything is being done that should stop them. There is also the [dpd-components](https://github.com/GibbsConsulting/dpd-components) repo, which contains the pipe component to enable push events to be sent to the ``Dash`` front end from ``Django``. This is based on the 'old' component infrastructure and didn't need to do anything out of the ordinary as far as I can recall.

**Comment by eddy-ojb** [comment]
Thanks for this. Closing the issue!
