### ISSUE TITLE
'WrappedDash' object has no attribute '_generate_meta_html' on all examples.

### ISSUE THREAD

**Issue by thomascooper** [GibbsConsulting/django-plotly-dash#460]
Hey,

I pulled the repo today. Updated make_env to python 3.8, then ran make_env, prepare_redis, and prepare_demo.

The intial pages pull with no issue for dpd, but all of the embedded dash apps give me the exact same error:
'WrappedDash' object has no attribute '_generate_meta_html'

Am I missing a step?

**Comment by thomascooper** [comment]
Update:

I have solved this issue by downgrading dash from the auto installed version of 2.10, back to 2.9.3. In 2.10 the _generate_meta_html method has been changed to _generate_meta

To apply the quickfix, change requirements.txt in the root directory
from: dash>=2.0
to: dash>=2.0,<=2.9.3

**Comment by varunm22** [comment]
Same for me! I came to make the same issue with the same fix.

**Comment by anayagaray98** [comment]
Same here!! I created this post on StackOverflow, there's all that I've tried so far.

https://stackoverflow.com/questions/70437314/the-current-path-django-plotly-dash-app-test-didn-t-match-any-of-these 

I'm going to try downgrading Dash to 2.9.3 and I'll see what results.

**Comment by GibbsConsulting** [comment]
PR #462 contains a temporary fix; this is now on PyPi as version 2.2.1

**Comment by anayagaray98** [comment]
Downgrading Dash to 2.9.3 solved my case.
