### ISSUE TITLE
Error running demo example

### ISSUE THREAD

**Issue by cchantra** [GibbsConsulting/django-plotly-dash#469]
I got the error on the demo example, e.g.

 
demo-six:87     GET http://127.0.0.1:8000/django_plotly_dash/app/dash_example_1/_dash-component-suites/dash/deps/react@16.v2_0_0m1690704585.14.0.min.js net::ERR_ABORTED 404 (Not Found)
demo-six:86     GET http://127.0.0.1:8000/django_plotly_dash/app/dash_example_1/_dash-component-suites/dash/deps/polyfill@7.v2_0_0m1690704585.12.1.min.js net::ERR_ABORTED 404 (Not Found)
9Refused to execute script from '<URL>' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
demo-six:91     GET http://127.0.0.1:8000/static/dash/component/dash_mantine_components/dash_mantine_components.js net::ERR_ABORTED 404 (Not Found)
demo-six:88     GET http://127.0.0.1:8000/django_plotly_dash/app/dash_example_1/_dash-component-suites/dash/deps/react-dom@16.v2_0_0m1690704585.14.0.min.js net::ERR_ABORTED 404 (Not Found)
dash_bootstrap_components.v0_13_1m1682118482.min.js:31 Uncaught TypeError: Cannot read properties of undefined (reading 'Component')
    at Object.<anonymous> (dash_bootstrap_components.v0_13_1m1682118482.min.js:31:24909)
    at n (dash_bootstrap_components.v0_13_1m1682118482.min.js:1:142)
    at Object.<anonymous> (dash_bootstrap_components.v0_13_1m1682118482.min.js:31:45059)
    at n (dash_bootstrap_components.v0_13_1m1682118482.min.js:1:142)
    at Object.<anonymous> (dash_bootstrap_components.v0_13_1m1682118482.min.js:6:877)
    at n (dash_bootstrap_components.v0_13_1m1682118482.min.js:1:142)
    at Module.<anonymous> (dash_bootstrap_components.v0_13_1m1682118482.min.js:31:67901)
    at n (dash_bootstrap_components.v0_13_1m1682118482.min.js:1:142)
    at dash_bootstrap_components.v0_13_1m1682118482.min.js:1:941
    at dash_bootstrap_components.v0_13_1m1682118482.min.js:1:951
(anonymous) @ dash_bootstrap_components.v0_13_1m1682118482.min.js:31
n @ dash_bootstrap_components.v0_13_1m1682118482.min.js:1
(anonymous) @ dash_bootstrap_components.v0_13_1m1682118482.min.js:31
n @ dash_bootstrap_components.v0_13_1m1682118482.min.js:1
(anonymous) @ dash_bootstrap_components.v0_13_1m1682118482.min.js:6
n @ dash_bootstrap_components.v0_13_1m1682118482.min.js:1
(anonymous) @ dash_bootstrap_components.v0_13_1m1682118482.min.js:31
n @ dash_bootstrap_components.v0_13_1m1682118482.min.js:1
(anonymous) @ dash_bootstrap_components.v0_13_1m1682118482.min.js:1
(anonymous) @ dash_bootstrap_components.v0_13_1m1682118482.min.js:1
bundle.v0_1_0m1690690942.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'Component')
    at Object.<anonymous> (bundle.v0_1_0m1690690942.js:1:3070)
    at Object.<anonymous> (bundle.v0_1_0m1690690942.js:1:3229)
    at t (bundle.v0_1_0m1690690942.js:1:126)
    at Object.<anonymous> (bundle.v0_1_0m1690690942.js:1:369)
    at t (bundle.v0_1_0m1690690942.js:1:126)
    at bundle.v0_1_0m1690690942.js:1:213
    at bundle.v0_1_0m1690690942.js:1:218
(anonymous) @ bundle.v0_1_0m1690690942.js:1
(anonymous) @ bundle.v0_1_0m1690690942.js:1
t @ bundle.v0_1_0m1690690942.js:1
(anonymous) @ bundle.v0_1_0m1690690942.js:1
t @ bundle.v0_1_0m1690690942.js:1
(anonymous) @ bundle.v0_1_0m1690690942.js:1
(anonymous) @ bundle.v0_1_0m1690690942.js:1
demo-six:93     GET http://127.0.0.1:8000/django_plotly_dash/app/dash_example_1/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_0_0m1690704584.min.js net::ERR_ABORTED 404 (Not Found)
demo-six:94     GET http://127.0.0.1:8000/django_plotly_dash/app/dash_example_1/_dash-component-suites/dash/dcc/dash_core_components.v2_0_0m1690704585.js net::ERR_ABORTED 404 (Not Found)
demo-six:96     GET http://127.0.0.1:8000/django_plotly_dash/app/dash_example_1/_dash-component-suites/dash/html/dash_html_components.v2_0_0m1690704585.min.js net::ERR_ABORTED 404 (Not Found)
demo-six:95     GET http://127.0.0.1:8000/django_plotly_dash/app/dash_example_1/_dash-component-suites/dash/dcc/dash_core_components-shared.v2_0_0m1690704585.js net::ERR_ABORTED 404 (Not Found)
demo-six:97     GET http://127.0.0.1:8000/django_plotly_dash/app/dash_example_1/_dash-component-suites/dash/dash_table/bundle.v5_0_0m1690704584.js net::ERR_ABORTED 404 (Not Found)
demo-six:97 Uncaught ReferenceError: DashRenderer is not defined
    at demo-six:97:203
(anonymous) @ demo-six:97

My versions:

dash                               2.0.0
dash-bootstrap-components          0.13.1
dash-canvas                        0.1.0
dash-core-components               2.0.0
dash-html-components               2.0.0
dash-mantine-components            0.12.1
dash-renderer                      1.6.0
dash-table                         5.0.0
django-plotly-dash                 1.1.4

django-allauth                     0.54.0
django-bootstrap4                  23.2
django-crispy-forms                2.0
django-phone-field                 1.8.1
django-phonenumber-field           7.1.0
django-plotly-dash                 1.1.4
django-redis                       5.3.0
django-utils-six                   2.0

Can you suggest any solution?

Regards

**Comment by delsim** [comment]
@cchantra that is a very old version of `django-plotly-dash` - is there a reason to not use something up-to-date?
