### ISSUE TITLE
Using dash-tradingview dash_tvlwc breaks the app in Django

### ISSUE THREAD

**Issue by notgonnamakeit** [GibbsConsulting/django-plotly-dash#477]
Hi, I have a functioning Dash app using [dash_tvwlc](https://github.com/tysonwu/dash-tradingview) that works fine if I run it on its own. When I try to display it in Django, I get an error that its JS file can't be downloaded from unpkg.com:

<img width="933" alt="image" src="https://github.com/GibbsConsulting/django-plotly-dash/assets/149114346/983ff9b0-f03c-4540-b751-d7dd21db1f1f">

When I run the app on its own outside of Django, it serves the JS locally. Any idea how I can make that work?

**Comment by delsim** [comment]
@notgonnamakeit what [configuration parameters(https://django-plotly-dash.readthedocs.io/en/latest/configuration.html#configuration) do you have - in particular the `STATICFILES_FINDERS` and `PLOTLY_COMPONENTS` ones?

**Comment by notgonnamakeit** [comment]
@delsim I didn't have any set, and didn't know I had to. It works now that I've configured it like this:

```
STATICFILES_FINDERS =[
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'django_plotly_dash.finders.DashAssetFinder',
    'django_plotly_dash.finders.DashComponentFinder',
    'django_plotly_dash.finders.DashAppDirectoryFinder',
 ]

PLOTLY_DASH = {
    "serve_locally": True,
}

PLOTLY_COMPONENTS = [
    'dpd_components',
    'dpd_static_support',
    'dash_bootstrap_components',
    'dash_mantine_components',
    'dash_tvlwc',
]
```

Thanks for pointing me in the right direction.
