### ISSUE TITLE
Template tags should add in html file?

### ISSUE THREAD

**Issue by kunduruanil** [GibbsConsulting/django-plotly-dash#48]
hi ,
{%load plotly_dash%}
{%plotly_app name="SimpleExample"%}

where should this tag need to be added ? should i create a new html file and add this as 2 lines?
 that html file need to render in views file ?

**Comment by GibbsConsulting** [comment]
You can use these template tags like any other ones in Django, in any template.

See [this demo page](https://github.com/GibbsConsulting/django-plotly-dash/blob/master/demo/demo/templates/demo_one.html) for an example.

The [base template](https://github.com/GibbsConsulting/django-plotly-dash/blob/master/demo/demo/templates/base.html) for the demos also includes header and footer template tags. It looks like the documentation hasn't kept up with the code with respect to these tags.

**Comment by kunduruanil** [comment]
KeyError at  , Error during template rendering error at line 14
url: path('new/',TemplateView.as_view(template_name='test.html'),name='new'),
below test.html:
{%load plotly_dash%}
{%block content%}
<div class="card bg-light border-dark">
  <div class="card-body">
    <p><span>{</span>% load plotly_dash %}</p>
    <p>&lt;div class="<span>{</span>% plotly_class name="SE"%}">
    <p class="ml-3"><span>{</span>% plotly_app name="SE" %}</p>
    <p>&lt;\div>
  </div>
</div>
<p></p>
<div class="card border-dark">
  <div class="card-body">
    <div class="{%plotly_class name="SE" template_type="div-direct"%}">
      {%plotly_direct name="SE"%}
    </div>
  </div>
</div>
<p></p>
{%endblock%}
dash_ui.py:
import dash
import dash_core_components as dcc
import dash_html_components as html
from django_plotly_dash import DjangoDash   
app = DjangoDash('SE') # replaces dash.Dash

app.layout = html.Div([dcc.RadioItems(id='dropdown-color',options=[{'label': c, 'value': c.lower()} for c in ['Red', 'Green', 'Blue']],value='red'),html.Div(id='output-color'),dcc.RadioItems(id='dropdown-size',options=[{'label': i,'value': j} for i, j in [('L','large'), ('M','medium'), ('S','small˓→')]],value='medium'),html.Div(id='output-size')])

@app.callback(dash.dependencies.Output('output-color', 'children'),[dash.dependencies.Input('dropdown-color', 'value')])
def callback_color(dropdown_value):
    return "The selected color is %s." % dropdown_value

@app.callback(dash.dependencies.Output('output-size', 'children'),[dash.dependencies.Input('dropdown-color', 'value'),dash.dependencies.Input('dropdown-size', 'value')])
def callback_size(dropdown_color, dropdown_size):
    return "The chosen T-shirt is a %s %s one." %(dropdown_size,dropdown_color)


what else i need to add ? i checked demo page and implemented this!

**Comment by GibbsConsulting** [comment]
Do you have an import of the `dash_ui.py` file somewhere? It looks like the template rendering cannot find a dash app by the name of 'SE' which would be the case if the file is not imported.
