### ISSUE TITLE
followed all the docs and checked demo code as well but still something want wrong:

### ISSUE THREAD

**Issue by kunduruanil** [GibbsConsulting/django-plotly-dash#51]
KeyError at /new/  , In template test.html: Error during template rendering error at line 14
#below test.html:
{%load plotly_dash%}
{%block content%}
<div class="card bg-light border-dark">
  <div class="card-body">
    <p><span>{</span>% load plotly_dash %}</p>
    <p>&lt;div class="<span>{</span>% plotly_class name="SE"%}">
    <p class="ml-3"><span>{</span>% plotly_app name="SE" %}</p>
    <p>&lt;\div>
  </div>
</div>
<p></p>
<div class="card border-dark">
  <div class="card-body">
    <div class="{%plotly_class name="SE" template_type="div-direct"%}">
      {%plotly_direct name="SE"%}
    </div>
  </div>
</div>
<p></p>
{%endblock%}

# url:

path('new/',TemplateView.as_view(template_name='test.html'),name='new'),

# dash_ui.py:

import dash
import dash_core_components as dcc
import dash_html_components as html
from django_plotly_dash import DjangoDash   
app = DjangoDash('SE') # replaces dash.Dash

app.layout = html.Div([dcc.RadioItems(id='dropdown-color',options=[{'label': c, 'value': c.lower()} for c in ['Red', 'Green', 'Blue']],value='red'),html.Div(id='output-color'),dcc.RadioItems(id='dropdown-size',options=[{'label': i,'value': j} for i, j in [('L','large'), ('M','medium'), ('S','small˓→')]],value='medium'),html.Div(id='output-size')])

@app.callback(dash.dependencies.Output('output-color', 'children'),[dash.dependencies.Input('dropdown-color', 'value')])
def callback_color(dropdown_value):
    return "The selected color is %s." % dropdown_value

@app.callback(dash.dependencies.Output('output-size', 'children'),[dash.dependencies.Input('dropdown-color', 'value'),dash.dependencies.Input('dropdown-size', 'value')])
def callback_size(dropdown_color, dropdown_size):
    return "The chosen T-shirt is a %s %s one." %(dropdown_size,dropdown_color)

changes in setting.py:
ALLOWED_HOSTS = ['*']

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_plotly_dash.apps.DjangoPlotlyDashConfig',
    'dash',
    'channels',
    'topictrends'
]

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 8080)],
        },
    },
}
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'topictrends/templates/files')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'topictrends.wsgi.application'

ASGI_APPLICATION = "topictrends.routing.application"

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:8080/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient"
        },
        "KEY_PREFIX": "dpd-demo"
    }
}

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [('127.0.0.1', 8080),],
        },
    },
}

what else i need to add ? i checked demo page and implemented this!

**Comment by delsim** [comment]
As per the comment in #48 - its likely that you're not importing `dash_ui` anywhere.

See also the last paragraph of the [usage](https://django-plotly-dash.readthedocs.io/en/latest/simple_use.html) documentation page.

It looks like the error message when an app is not found (even if not the specific problem in this case) could do with improvement.
