### ISSUE TITLE
[DOC] Fix auto build doc

### ISSUE THREAD

**Issue by weber-s** [GibbsConsulting/django-plotly-dash#55]
Hi!

It seems that the doc does not compile anymore. 

    No matching distribution found for Django>=2 

This is due to the virtualenv, which is in python2.7. Django>=2 does not support this version.

You have to put the python interpreter to Cython3.0 via the dashboard of Readthedoc. It should be straightforward as both dash and dajngo-plotly-dash use python3.

**Comment by delsim** [comment]
Thanks for the observation - hadn't spotted this before. I've updated the RTD config.

**Comment by GibbsConsulting** [comment]
RTD has built and pushed out the documentation successfully, so closing this ticket. Thanks again for reporting it.
