### ISSUE TITLE
How to pass URL parameter to Dash app?

### ISSUE THREAD

**Issue by brylie** [GibbsConsulting/django-plotly-dash#57]
How can we send a URL parameter, such as a query string or named router parameter, into the Dash instance? For example, specifying a date range or identifier in the router URL, which could then be used in query logic within the Dash callbacks.

**Comment by GibbsConsulting** [comment]
The [plotly_app](https://django-plotly-dash.readthedocs.io/en/latest/template_tags.html#the-plotly-app-template-tag) template tag allows you to specify initial arguments for the Dash app. This is used in several of the demo pages, including the [second one](https://github.com/GibbsConsulting/django-plotly-dash/blob/master/demo/demo/templates/demo_two.html)

Would this - perhaps coupled to a view/template that extracts the arguments you want to pass from the URL (or somewhere else) - be sufficient? Alternatively, you could create the app instance and set its properties in code.

If you need to pass values after the app is constructed, then something like the ``Pipe`` component might help. This is used in the fourth demo to push updates into a Dash app asynchronously to any user input to the app.

**Comment by delsim** [comment]
The [plotly_app](https://django-plotly-dash.readthedocs.io/en/latest/template_tags.html#the-plotly-app-template-tag) template tag allows you to specify initial arguments for the Dash app. This is used in several of the demo pages, including the [second one](https://github.com/GibbsConsulting/django-plotly-dash/blob/master/demo/demo/templates/demo_two.html)

Would this - perhaps coupled to a view/template that extracts the arguments you want to pass from the URL (or somewhere else) - be sufficient? Alternatively, you could create the app instance and set its properties in code.

If you need to pass values after the app is constructed, then something like the ``Pipe`` component might help. This is used in the fourth demo to push updates into a Dash app asynchronously to any user input to the app.

**Comment by eddy-ojb** [comment]
I also send variables via the request.session variable quite a bit prior to an  dash app load.

I am just about getting to grips with channels so am looking to start using Pipe!

**Comment by brylie** [comment]
@eddy-ojb sounds like an interesting approach. Could you share a code snippet?

**Comment by eddy-ojb** [comment]
The way I send info prior to load is in one of the demos i.e. send context from Django to Dash [via views.py](https://github.com/GibbsConsulting/django-plotly-dash/blob/master/demo/demo/views.py), then receive and do something with it in [callback_test2 in dash_apps.py](https://github.com/GibbsConsulting/django-plotly-dash/blob/master/demo/demo/dash_apps.py) . In the demo, this context is accessed in Dash and output to an html.Div.

**Comment by brylie** [comment]
Could these examples please be added to the documentation, in concise form? I am struggling to get them to work, and don't quite follow the logic when browsing the example files you linked.

**Comment by brylie** [comment]
When I try the session approach, my `kwargs` dict is empty.

**Comment by brylie** [comment]
OK, the difference was to use `expanded_callback`. Please, please, please, add this to the documentation with a full explanation. It is not easy to 'reverse engineer' the demos, particularly when they span multiple files.

**Comment by GibbsConsulting** [comment]
We do have some documentation [here](https://django-plotly-dash.readthedocs.io/en/latest/extended_callbacks.html) so I think the need is twofold - improve it, and also make sure it is easier to find from other parts of the documentation.
Pull requests for either or both of there - or indeed any other improvements - are most welcome, but even just some suggestions as to where the documentation could be usefully cross-referenced would be helpful.

**Comment by brylie** [comment]
One thing that might be useful would be a tutorial. E.g. document the process of building the demo app, showing how things relate. In the case of passing data from django to Dash, even the demo stopped short of using the data in the Dash app (leaving a lot to the reader to figure out).

**Comment by GibbsConsulting** [comment]
There is now also #119 regarding a more complete example, so closing this issue.
