### ISSUE TITLE
Add link to file location question from FAQ

### ISSUE THREAD

**Issue by delsim** [GibbsConsulting/django-plotly-dash#59]
Issue #58 concerns the location of files containing dash code (ie for layout and callbacks and the like). This discussion, or a summary of it, belongs in the FAQ

**Comment by brylie** [comment]
Yes, this would be a great addition to the README. 

I am particularly having difficulty placing callbacks in a file separate from layout and the app instance. I.e. I would like to separate structure, functionality, and the app instance into their own files.
