### ISSUE TITLE
Release version 1.0

### ISSUE THREAD

**Issue by GibbsConsulting** [GibbsConsulting/django-plotly-dash#60]
Create v1.0 release and tag as such in code and RTD.

**Comment by dwinston** [comment]
[Dash 1.0 has been released!](https://github.com/plotly/dash/releases/tag/v1.0.0). There's a [migration guide](https://dash.plot.ly/dash-1-0-migration) with some notes. It seems like it's a good time to re-surface this issue.

**Comment by GibbsConsulting** [comment]
Yes, thanks for the prompt @dwinston - I think we are at the point that we can have a 1.0 release

From a quick read of the migration guide and release notes, it doesn't look like there is anything else needed to be compatible with Dash v1.0, and the current prerelease 0.9.13 was built using it. Please create new issues or comment here if this is not the case.
