### ISSUE TITLE
Create and make available an online version of the demo

### ISSUE THREAD

**Issue by GibbsConsulting** [GibbsConsulting/django-plotly-dash#69]

**Comment by GibbsConsulting** [comment]
There is a prerelease version available for testing at http://68.183.128.171:8000

**Comment by brylie** [comment]
How to get login credentials?

**Comment by GibbsConsulting** [comment]
For the moment, you have to use the github login option. However, there isn't anything (yet) that depends on it.

**Comment by brylie** [comment]
I get a 500 server error on demo six.

**Comment by GibbsConsulting** [comment]
This is now available at https://www.djangoplotlydash.com

Any and all feedback most welcome.
