### ISSUE TITLE
Dependency loading issue when using dash-bootstrap-components with DjangoDash

### ISSUE THREAD

**Issue by brylie** [GibbsConsulting/django-plotly-dash#84]
While building a project with django-plotly-dash, I added the [django-bootstrap-components](https://github.com/ASIDataScience/dash-bootstrap-components) package. For some reason, the django-bootstrap-components are not binding with the `DjangoDash` class, as they are probably looking for the `Dash` class. As a result, my django-plotly-dash app is throwing errors:

> Error loading dependencies

The browser console says:
> Error: "dash_bootstrap_components was not found."

Related issue: https://github.com/ASIDataScience/dash-bootstrap-components/issues/96

**Comment by GibbsConsulting** [comment]
This is related to #21 - there's no easy way at the moment to have Django (or whatever front end proxy is in use) serve up the contents of asset directories.

**Comment by delsim** [comment]
I'm working towards addressing #21, but as a workaround there is an ``add_bootstrap_links`` flag that can be used in the interim.

For example,
```python
dd = DjangoDash("BootstrapApplication",
                add_bootstrap_links=True)

dd.layout = html.Div(
    [
    dbc.Alert("This is an alert", color="primary"),
    dbc.Alert("Danger", color="danger"),
    ]
)
```
works. However, I haven't tried anything more complex.

**Comment by GibbsConsulting** [comment]
@brylie is this still an issue? v0.9.10 onwards should have addressed this.

**Comment by scythargon** [comment]
Still does not work with `django-bootstrap-components`.

**Comment by GibbsConsulting** [comment]
Marking this issue as closed as it has presumably been fixed for some time now. @brylie please reopen if not
