### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by kknckk** [GibbsConsulting/django-plotly-dash#85]
I've got strange issue.. everything works perfectly fine on development django server, but when running on gunicorn i get this error:
Internal Server Error: /django_plotly_dash/instance/kr_2/
Traceback (most recent call last):
  File "/opt/jpk/django_plotly_dash/dash_wrapper.py", line 61, in get_local_stateless_by_name
    return usable_apps[name]
KeyError: 'kr_2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/jpk/venv/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/jpk/venv/lib64/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/jpk/venv/lib64/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/jpk/django_plotly_dash/views.py", line 100, in main_view
    _, app = DashApp.locate_item(ident, stateless, cache_id=cache_id)
  File "/opt/jpk/django_plotly_dash/models.py", line 200, in locate_item
    app = dash_app.as_dash_instance(cache_id=cache_id)
  File "/opt/jpk/django_plotly_dash/models.py", line 162, in as_dash_instance
    dash_app = self.stateless_app.as_dash_app() # pylint: disable=no-member
  File "/opt/jpk/django_plotly_dash/models.py", line 59, in as_dash_app
    dateless_dash_app = get_stateless_by_name(self.app_name)
  File "/opt/jpk/django_plotly_dash/models.py", line 36, in get_stateless_by_name
    return get_local_stateless_by_name(name)
  File "/opt/jpk/django_plotly_dash/dash_wrapper.py", line 91, in get_local_stateless_by_name
    raise KeyError("Unable to find stateless DjangoApp called %s"%name)
KeyError: 'Unable to find stateless DjangoApp called kr_2'

**when running this code:**

uid_counter = 0
usable_apps = {}
def add_usable_app(name, app):
    'Add app to local registry by name'
    name = slugify(name)
    global usable_apps # pylint: disable=global-statement
    usable_apps[name] = app
    return name

def get_local_stateless_by_name(name):
    '''
    Locate a registered dash app by name, and return a DjangoDash instance encapsulating the app.
    '''
    name = slugify(name)
    # TODO wrap this in raising a 404 if not found
    try:
        return usable_apps[name]
    except:
        raise KeyError("Unable to find stateless DjangoApp called %s"%name)

Any ideas what could go wrong?

**Comment by delsim** [comment]
If your app works in debug mode, but not when running with multiple processes, then something to check is the cache configuration. At the moment django-plotly-dash uses the cache to transfer initial arguments.
There is already issue #75 for removing this dependency.

**Comment by GibbsConsulting** [comment]
PR #91 has now been released. Setting the [``initial_arguments``](https://django-plotly-dash.readthedocs.io/en/latest/configuration.html#initial-arguments) configuration flag to ``False`` will store the initial arguments in a session rather than use the cache.

**Comment by GibbsConsulting** [comment]
@kknckk does adjusting the cache configuration and/or upgrading to v0.9.5 or later and using the ``initial_arguments`` setting work?

**Comment by tin-trong-nguyen** [comment]
I had exactly the same problem. 
After reading this issue, I tried:
- upgrading django-plotly-dash to the newest version (0.9.8 at the moment)
- added `PLOTLY_DASH = {'cache_arguments': False}` to `myproject/myproject/settings.py`
- restarted gunicorn server

But the problem still persists.

**Comment by GibbsConsulting** [comment]
By turning off the cache, the initial arguments are now stored in a Django session.
Do you have sessions enabled? If so, which backend are you using?

**Comment by delsim** [comment]
Are you in a position to try running the demo through gunicorn for multiple workers with this setting? From your description the issue sounds like it is driven by state not being shared between workers.
What error message do you get?

**Comment by tin-trong-nguyen** [comment]
You are right. With this setting, trying the 'SimpleExample' app from the documentation works even with multiple workers. There must be something wrong in my app. Here's my error log:

```
[02/Feb/2019 14:30:22] ERROR [django.request:228] Internal Server Error: /django_plotly_dash/app/aba_result/_dash-dependencies
Traceback (most recent call last):
  File "/home/ec2-user/miniconda3/envs/data_interface/lib/python3.7/site-packages/django_plotly_dash/dash_wrapper.py", line 65, in get_local_stateless_by_name
    return usable_apps[name]
KeyError: 'aba_result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/miniconda3/envs/data_interface/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ec2-user/miniconda3/envs/data_interface/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ec2-user/miniconda3/envs/data_interface/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ec2-user/miniconda3/envs/data_interface/lib/python3.7/site-packages/django_plotly_dash/views.py", line 40, in dependencies
    _, app = DashApp.locate_item(ident, stateless)
  File "/home/ec2-user/miniconda3/envs/data_interface/lib/python3.7/site-packages/django_plotly_dash/models.py", line 196, in locate_item
    dash_app = find_stateless_by_name(ident)
  File "/home/ec2-user/miniconda3/envs/data_interface/lib/python3.7/site-packages/django_plotly_dash/models.py", line 76, in find_stateless_by_name
    dash_app = get_stateless_by_name(name)
  File "/home/ec2-user/miniconda3/envs/data_interface/lib/python3.7/site-packages/django_plotly_dash/models.py", line 36, in get_stateless_by_name
    return get_local_stateless_by_name(name)
  File "/home/ec2-user/miniconda3/envs/data_interface/lib/python3.7/site-packages/django_plotly_dash/dash_wrapper.py", line 67, in get_local_stateless_by_name
    raise KeyError("Unable to find stateless DjangoApp called %s"%name)
KeyError: 'Unable to find stateless DjangoApp called aba_result'
```
(aba_result is the name of my Dash app)

Do you have any idea on what I might have done wrong?

**Comment by GibbsConsulting** [comment]
The `StatelessApp` has to be the same when used in different views, so any dynamic part should be within a `DashApp` model as described [here](https://django-plotly-dash.readthedocs.io/en/latest/models_and_state.html#the-dashapp-model). You can then create one of these in a view, and persist it like any other Django model, and it will then be used for the other views.

**Comment by tin-trong-nguyen** [comment]
Thanks for the response. I'm fairly new to Django and Dash in general. Can you help me clarify something:
1. By "state" do you mean the `dash.dependencies.Input`, `dash.dependencies.State` that are used in callback functions?
2. How does a DjangoDash app work in multi-worker setting? Why isn't the whole app get processed by just 1 worker at a time, like how each view in Django is (as far as I'm aware)? Can we customize this behavior?
3. In my project, my Dash app content changes depending on (i) the url (ii) the input data filters (which is also included in the Dash app layout). Can you help check if the following fix is similar to what you suggested in the previous comment? (the one using `DashApp`. I'm using direct html injection and `initial_arguments` is not supported there). So, to build my dynamic DjangoDash app I think I'll have to:

    - Put my whole DjangoDash app definition outside view functions, including `app = DjangoDash(...)`, `app.layout = ...` and callback functions
    - Inside my view, create a `DashApp` instance with correct `stateless_app` key, put the information needed for the dynamic content (from the view's url) inside `base_state`
    - Put any dynamic element in my app inside a callback function, change to use `expanded_callback`, and retrieve information from the url through `dash_app.base_state`
    - Change the html template to use the `da` instead of `name`

Anything else?
Thanks.

**Comment by GibbsConsulting** [comment]
@tin-trong-nguyen wrt your questions:
(1) sort-of; a Dash app has internal state spread throughout the components and these are available as callback arguments through `Input` and `State`, but there is also the possibility to map to other Django application state, eg through an instance of `DjangoDash` or the user's session.
(2) An app is multiple calls to the backend (Django here). One of the main roles of any backend application is managing the state between these calls, and the aim of `django-plotly-dash` is allowing this to be leveraged by a Dash application. Trying to bind a user session to a specific backend worker would be an awful lot of pain for at best no gain.
(3) Instead of what you have here, you could look at using more of the existing state handling in Django and django-plotly-dash.

**Comment by tin-trong-nguyen** [comment]
@GibbsConsulting

So I've tried the state persisting solutions you suggested (to my best knowledge after perusing the doc and the demo), and there are certain problems:

### Method 1: Using `DashApp`
#### 1. What I did 
- In views.py, outside any function:
```python
app = django_plotly_dash.DjangoDash('my_dash_app', suppress_callback_exceptions=True)
app.layout = [...]

@app.expanded_callback(
    dash.dependencies.Output('e2', 'value'),
    [dash.dependencies.Input('e1', 'value')])
def test_callback(e1, **kwargs):
    try:
        da = kwargs['dash_app']
        job_id = da.base_state['job_id']
        return job_id
    except KeyError:
        return ''
```
- Inside the view function:
```python
def job_result(request, job_id):
    stateless_app = django_plotly_dash.models.StatelessApp.objects.get(app_name='my_dash_app')
    da = django_plotly_dash.models.DashApp(stateless_app=stateless_app, base_state=f'{{"job_id": {job_id}}}')
    return render(request, 'my_app/job_result.html', context={'da': da})
```
- Inside html template:
```html
[...]
{% load plotly_dash %}
{% plotly_header %}
{% plotly_direct da=da %}
{% plotly_footer %}
[...]
```

#### 2. The problem:
I got this error
```
da = kwargs['dash_app']
job_id = da.base_state['job_id']
AttributeError: 'DjangoDash' object has no attribute 'base_state'
```
As the [documentation](https://django-plotly-dash.readthedocs.io/en/latest/extended_callbacks.html) says, kwargs['dash_app'] should return a `DashApp` object, which I suppose has the `base_state` attribute, but for some reasons `DjangoDash` object was returned instead.

### Method 2: Using Session
#### 1. What I did
- Inside view function:
```python
[...]
dpd_session_state = request.session.get('django_plotly_dash', {})
dpd_session_state['job_id'] = job_id # job_id is in the web url
request.session['django_plotly_dash'] = dpd_session_state
[...]
```
- Inside callback function (defined in views.py, out of any function):
```python
session_state = kwargs['session_state']
job_id = session_state['job_id']
```

#### 2. The problem:
This works, but the session data get mixed up once a user open different tabs, each tab going to page with different `job_id` (i.e. `domain.com/result/1` and `domain.com/result/2`). For example if they open 1st tab, then open 2nd tab, then interact with the Dash app in the 1st tab, while expecting to see data for `job_id = 1` in this tab, the callback function will return data for `job_id = 2` instead.

### Did I do something wrong or these are expected behaviors? What can one do overcome these issues?

**Comment by delsim** [comment]
@tin-trong-nguyen from a visual scan there are a couple of issues and #119 has been created to try to eliminate some of the confusion, as the documentation is certainly lacking in this area. For example, you're creating a DashApp instance in your view but not saving it to the database before using it.

Its not clear to me if there is an underlying bug in the code - there could well be - but until I've got an example that replicates your error I can't comment further.

**Comment by nadav-har-tzvi** [comment]
Hi, if this is still relevant to anyone, I had a similar issue with gunicorn that I managed to solve.

Again as described above, I deployed my app using gunicorn and some of the requests made to the DjangoDash generated DPD routes (the layout, update component state, etc) would sometimes fail due to a KeyError on the `usable_apps`. 
The KeyError behaviour actually depends on which gunicorn worker receives the request. If by chance the same worker that did the initial rendering receives a request made to one of those DPD endpoints, it would fulfil the request perfectly. If a different worker gets the request, it wouldn't find the DjangoDash instance in the `usable_apps` global dictionary and then DPD would raise a KeyError ([dash_wrapper.py#L87](https://github.com/GibbsConsulting/django-plotly-dash/blob/b1a86eebc6e1ef002a10f964f98952ddd47f862e/django_plotly_dash/dash_wrapper.py#L87))

I solved it by plugging in my own stateless app loader using the `stateless_loader` settings entry, which basically ensured that no matter what, the application would find a correct version of the DjangoDash app.

An example as follows:

```python
# In settings.py
PLOTLY_DASH = {
  ...
  'stateless_loader': 'path.to.module.load_app' # In my case: dashboards.utils.load_app
}

# in my dashboards.utils module (roughly)
from my.concrete.dashboards import dashboard1
from my.concrete.dashboards import dashboard2

def load_app(app_name):
    if app_name == 'my_dashboard_1':
        return dashboard1.create_dashboard_app()  # returns a DjangoDash instance, the same function would be used for the initial rendering.
    elif app_name == 'my_dashboard_2:
        return dashboard2.create_dashboard_app()
```

Does it make sense to anyone?

**Comment by GibbsConsulting** [comment]
@nadav-har-tzvi yes, that is exactly what you would expect to happen - each worker needs to find the appropriate DjangoDash instance, and if you're not storing them somewhere (eg the database) then you'll need to recreate them in each worker.

This is why the `stateless_loader` hook exists - not every use case involves storing these instances. You do need to ensure that your `load_app` function is consistent between workers and in particular doesn't care how many times it is called.
