### ISSUE TITLE
Double trailing slashes in urls (2nd sample/demo-two) impede deployment

### ISSUE THREAD

**Issue by yurman-cc** [GibbsConsulting/django-plotly-dash#88]

**Comment by yurman-cc** [comment]
Some urls generated have consecutive slashes (resulting from empty params?) like the following one from demo-two/second example: /django_plotly_dash/instance/simpleexample-1/initial/dpd-initial-args-fc2fde5f58b64f70805a929e6948bc85//. Replacing them with a single slash will result in 404

While whether it's valid or not is an open question (it's really a gray area), in practice, it makes it near impossible deploying under Apache+Django. The reason being, Apache replaces multiple slash sequences with a single slash and it's not possible to change this behavior through config or mod_rewrite, short of re-compiling. Other deployment options may be problematic too but less severe.

I would suggest adding a test case to cover this in the future

**Comment by yurman-cc** [comment]
For the purpose of better illustration of what is affected, here I reconstructed how the route spec looks for the initial params:

instance/<slug:ident>[/initial/<slug:cache_id>/]/[_dash-*][/<slug:component>/<resource>]

**Comment by delsim** [comment]
I think it is just an extra unwanted slash in the urls used when there are initial arguments. I just added [this](https://github.com/delsim/django-plotly-dash/commit/c424a754575f82b2da1e3f5fdb12cd3ddd413ce6) which will hopefully be pushed out later today.

**Comment by GibbsConsulting** [comment]
Marking this as closed as the fix has been pushed. Please reopen if needed.
