### ISSUE TITLE
no such table: django_plotly_dash_statelessapp

### ISSUE THREAD

**Issue by Motta23** [GibbsConsulting/django-plotly-dash#94]
First of all, many thanks for this package! It looks very promising. 

I am trying to integrate a very easy Dash app in a Django project, but can't seem to make it work. Whenever I run the server, I get an error `no such table: django_plotly_dash_statelessapp`. Is there a table I should add or is there another meaning? 

I have added the following to my project:

**In urls.py:**
`'django_plotly_dash.apps.DjangoPlotlyDashConfig'`
`'django_plotly_dash.middleware.BaseMiddleware'`

**In urls.py:**
`    
from . import example_dash_app
from django.views.generic import TemplateView
path('new/', TemplateView.as_view(template_name='test/home.html')),
`

**In test/home.html:**
`    
{% load plotly_dash %}
{% plotly_app name="SimpleExample" %}
`

**In example_dash_app.py:**
`import dash
import dash_core_components as dcc
import dash_html_components as html

from django_plotly_dash import DjangoDash

app = DjangoDash('SimpleExample')

app.layout = html.Div([
    dcc.RadioItems(
        id='dropdown-color',
        options=[{'label': c, 'value': c.lower()} for c in ['Red', 'Green', 'Blue']],
        value='red'
    ),
    html.Div(id='output-color'),
    dcc.RadioItems(
        id='dropdown-size',
        options=[{'label': i, 'value': j} for i, j in [('L','large'), ('M','medium'), ('S','small')]],
        value='medium'
    ),
    html.Div(id='output-size')

])

@app.callback(
    dash.dependencies.Output('output-color', 'children'),
    [dash.dependencies.Input('dropdown-color', 'value')])
def callback_color(dropdown_value):
    return "The selected color is %s." % dropdown_value

@app.callback(
    dash.dependencies.Output('output-size', 'children'),
    [dash.dependencies.Input('dropdown-color', 'value'),
     dash.dependencies.Input('dropdown-size', 'value')])
def callback_size(dropdown_color, dropdown_size):
    return "The chosen T-shirt is a %s %s one." %(dropdown_size,
                                                  dropdown_color)`

Am I missing something? Many thanks for your help!

**Comment by GibbsConsulting** [comment]
Based on what you've listed, and assuming that the first ``urls.py`` in the above is actually ``settings.py``, I think that all you are missing is running ``manage.py migrate`` to set up the models.

**Comment by Motta23** [comment]
Awesome, I forgot about that one! The simple demo now works, many thanks :). I will close this for now.
