### ISSUE TITLE
Httpresponse or redicts (equivalent to @app.server.route)

### ISSUE THREAD

**Issue by willmendil** [GibbsConsulting/django-plotly-dash#96]
Is there a way to serve csv files from the dash app. Similarly to what can be seen in this link in Flask [https://community.plot.ly/t/allow-users-to-dowload-an-excel-in-a-click/9410](https://community.plot.ly/t/allow-users-to-dowload-an-excel-in-a-click/9410)
That is :

@app.server.route('/download_excel/')
def download_excel():
    ''' prepare excel or csv file '''
    return send_file(...)

Indeed, if I do a `redirect()` from django, I get a successful post from the server but I don't get redirected:

@app.callback(
    Output('hidden-output', 'children'),
    [Input('download_csv', 'n_clicks')])
def redirect_btn(n_clicks):
    to_redirect()
    return 'res'

def to_redirect():
    return redirect('https://example.com/')

am I missing something? Hope there's enough info in this post

**Comment by willmendil** [comment]
Ok I figured it out. The doc infers one can use session state to store JSON in the user session which can then be used in Django. I did struggle to get to pass the data. The doc should be, in my opinion, detailed for use in such an example. For instance, by giving a code snippet.

**Comment by GibbsConsulting** [comment]
Thats a good observation, thanks. Created #100

**Comment by GibbsConsulting** [comment]
Issue #100 now merged as PR #114
